### ISSUE TITLE
Update HidePauseButton (real)

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1001]
### Your mod link

https://github.com/RayDeeUx/HidePauseButton/releases/download/v1.2.0/raydeeux.hidepausebutton.geode

### Your mod source code

https://github.com/RayDeeUx/HidePauseButton/

### Your mod description

Updated to avoid accidentally hiding the pause button sprite with @dankmeme01's Globed mod

also @muhxd please get a life

**Comment by TechStudent10** [comment]
1001, so close

**Comment by altalk23** [comment]
nice ios version

**Comment by altalk23** [comment]
!accept
