### ISSUE TITLE
Update GDDL Integration to version v1.1.0

### ISSUE THREAD

**Issue by B1rtek** [geode-sdk/indexer#1007]
### Your mod link

https://github.com/B1rtek/Geode-GDDLIntegration/releases/download/v1.1.0/b1rtek.gddlintegration.geode

### Your mod source code

https://github.com/B1rtek/Geode-GDDLIntegration

### Your mod description

# v1.1.0
### ***- ANDROID SUPPORT!!!!11***
- The search menu has been replaced by a much better one that allows the user to take full advantage of the GDDL API
- Results in the GDDL Demon Split displayed in the level list after clicking a tier are now accurate according to the data in the GDDL API (that's why the numbers might not match, as the counts are generated using local cache)
- The GDDL Search button can be now moved down (look in settings)
- The GDDL Tier button on the level info page can be replaced again with a label, and it can be moved down (although it might overlap with the diamonds label in gauntlets and weeklies)

**Comment by altalk23** [comment]
!accept
