### ISSUE TITLE
Geometry Dash

### ISSUE THREAD

**Issue by sofabeddd** [geode-sdk/indexer#1009]
### Your mod link

https://cdn.discordapp.com/attachments/1004832153076518932/1207938826958274651/sofabeddd.geometry_dash.geode

### Your mod source code

https://github.com/sofabeddd/Geometry-Dash

### Your mod description

[self explanatory video](https://cdn.discordapp.com/attachments/1087069528581755004/1207937236541251604/2024-02-15_21-40-06.mov)

**Comment by TheSillyDoggo** [comment]
add it to the releases section of the repo also setup github actions so it supports android and (maybe) mac
