### ISSUE TITLE
Update Hide Profile Button

### ISSUE THREAD

**Issue by Bigmancozmo** [geode-sdk/indexer#1014]
### Your mod link

https://github.com/Bigmancozmo/Hide-Profile-Button/releases/download/v1.2.0/bigmancozmo.hide_profile_button.geode

### Your mod source code

https://github.com/Bigmancozmo/Hide-Profile-Button/

### Your mod description

Hides the profile button from the main menu.
Can be toggled on/off and set to hide name only.

**Comment by altalk23** [comment]
!accept
