### ISSUE TITLE
Add Compact-Endscreen

### ISSUE THREAD

**Issue by MuhXd** [geode-sdk/indexer#1017]
### Your mod link

https://github.com/Suntle/Compact-Endscreen

### Your mod source code

https://github.com/Suntle/Compact-Endscreen/releases/download/v0.1.0/suntle.compactendscreen.geode

### Your mod description

# makes the endscreen compact
## my friend was offline so i'm publishing the first version 
![image](https://github.com/geode-sdk/indexer/assets/100521306/8b2141ad-1996-4df5-b2ca-a323da96350f)

**Comment by MuhXd** [comment]
???

**Comment by Bigmancozmo** [comment]
you swapped mod source code and mod link
