### ISSUE TITLE
Update Hide Profile Button to v1.3.2

### ISSUE THREAD

**Issue by Bigmancozmo** [geode-sdk/indexer#1020]
### Your mod link

https://github.com/Bigmancozmo/Hide-Profile-Button/releases/download/v1.3.2/bigmancozmo.hide_profile_button.geode

### Your mod source code

https://github.com/Bigmancozmo/Hide-Profile-Button/

### Your mod description

- allows you to hide your profile button
- can be enabled/disabled
- can be set to hide name only
- android support!!

**Comment by Bigmancozmo** [comment]
forgot to increase version my bad

**Comment by Cvolton** [comment]
!accept
