### ISSUE TITLE
Add UnixSync

### ISSUE THREAD

**Issue by Watkin81** [geode-sdk/indexer#1027]
### Your mod link

https://github.com/Watkin81/UnixSync/releases/download/v1.2.0/creatorcreepy.unixsync.geode

### Your mod source code

https://github.com/Watkin81/UnixSync

### Your mod description

A tiny mod that updates ItemIDs 7501-7513 to be set to current unix, date, and time values.
This allows for levels to sync between players with the globed mod.
The functionality of this mod can be enabled via level options.
The unix timestamp in the corner of the screen can be removed via mod options.

**Comment by matcool** [comment]
!accept
