### ISSUE TITLE
Add compact Menu

### ISSUE THREAD

**Issue by MuhXd** [geode-sdk/indexer#1044]
### Your mod link

https://github.com/Suntle/Compact-Endscreen/releases/download/v0.1.0/suntle.compactendscreen.geode

### Your mod source code

https://github.com/Suntle/Compact-Endscreen

### Your mod description

# Make the End Menu Compact

**Comment by Fleeym** [comment]
this has very questionable code that will 100% break on different aspect ratios, but what the hell

**Comment by Fleeym** [comment]
!accept
