### ISSUE TITLE
Add Colored Icon Kit v1.0.0

### ISSUE THREAD

**Issue by sofabeddd** [geode-sdk/indexer#1056]
### Your mod link

https://github.com/sofabeddd/Colored-Icon-Kit/releases/download/v1.0.0/sofabeddd.colored_icon_kit.geode

### Your mod source code

https://github.com/sofabeddd/Colored-Icon-Kit

### Your mod description

Colors all the icons in the garage, shops, achievements, etc. with your player colors.

**Comment by Cvolton** [comment]
newer version added
