### ISSUE TITLE
Add Quotes (v1.0.0)

### ISSUE THREAD

**Issue by Uproxide** [geode-sdk/indexer#1060]
### Your mod link

https://github.com/Uproxide/quotes-geode/releases/download/1.0.0/uproxide.quotes.geode

### Your mod source code

https://github.com/Uproxide/quotes-geode/

### Your mod description

# Quotes

Adds a "Quote Button" to the Main Menu and will get a random quote on click!
This can be funny, odd, or down right terrible. But its funny at times! 

## Want your own Quote in the mod?

[Join the Discord and Request One!](https://discord.gg/gy4BrxmWrF)

## Credits

Uproxide
Luna
You, The User

**Comment by Cvolton** [comment]
!accept
