### ISSUE TITLE
Add "Gamemode Changer"

### ISSUE THREAD

**Issue by BULL3TB0T** [geode-sdk/indexer#1061]
### Your mod link

https://github.com/BULL3TB0T/gamemode-changer-geode/releases/download/1.0.3/bulletbot.gamemode_changer.geode

### Your mod source code

https://github.com/BULL3TB0T/gamemode-changer-geode

### Your mod description

It lets you change to platformer mode or normal mode in-game.

**Comment by RayDeeUx** [comment]
please add @geode-sdk's Node IDs mod as a dependency: https://docs.geode-sdk.org/mods/dependencies

**Comment by Cvolton** [comment]
!accept
