### ISSUE TITLE
Add an entry

### ISSUE THREAD

**Issue by StatusZer0** [geode-sdk/indexer#1067]
### Your mod link

https://github.com/StatusZer0/Splash-Text/releases/download/Release/statuszer0.splashtext.geode

### Your mod source code

https://github.com/StatusZer0/Splash-Text

### Your mod description

Adds randomized splash text to the title screen.

**Comment by matcool** [comment]
nice link

**Comment by tulpenkiste** [comment]
truly the private repository ever
