### ISSUE TITLE
Add ZCB Live 1.0.1-beta.1

### ISSUE THREAD

**Issue by zeozeozeo** [geode-sdk/indexer#1071]
### Your mod link

https://github.com/zeozeozeo/zcblive-geode/releases/download/1.0.1-beta.1/zeozeozeo.zcblive.geode

### Your mod source code

https://github.com/zeozeozeo/zcblive-geode

### Your mod description

A pretty cool Geometry Dash clickbot

**NOTE:** [please read this](https://github.com/zeozeozeo/zcblive-geode/blob/main/README.md)

**Comment by matcool** [comment]
wow thats some nasty code, wheres the source code for the rust dll 😭

**Comment by zeozeozeo** [comment]
> wow thats some nasty code, wheres the source code for the rust dll 😭

gimme a min :pray:

**Comment by zeozeozeo** [comment]
@matcool here :3  https://github.com/zeozeozeo/zcblive-geode/tree/main/live

**Comment by matcool** [comment]
!accept
