### ISSUE TITLE
Add CameraShaderToggles

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1078]
### Your mod link

https://github.com/RayDeeUx/CameraShaderToggles/releases/download/v1.0.0/raydeeux.camerashadertoggles.geode

### Your mod source code

https://github.com/RayDeeUx/CameraShaderToggles

### Your mod description

# CameraShaderToggles

Allows individual toggles for each type of camera/shader trigger during gameplay, as opposed to the "No Shaders", "No Camera Move", and "No Camera Zoom" blanket treatment options provided with [Mega Hack](https://absolllute.com) or [OpenHack](https://geode-sdk.org/mods/prevter.openhack/).

Simple demo, with all shader triggers disabled and all camera triggers (except zoom, static, mode, and guide) disabled:

https://github.com/RayDeeUx/CameraShaderToggles/assets/51521765/549a3131-7b70-455f-9e96-af5bba0ba558

(Disclaimer: other Geode mods were active during this recording.)

This mod will not work on macOS.

**Comment by TheSillyDoggo** [comment]
bro wrote a whole essay

**Comment by Cvolton** [comment]
!accept
