### ISSUE TITLE
Add AutoDeafen+ v1.1.1

### ISSUE THREAD

**Issue by NucDevStuff** [geode-sdk/indexer#1083]
### Your mod link

https://github.com/NucDevStuff/AutoDeafen-Plus/releases/download/v1.1.1/nucdev.autodeafenplus.geode

### Your mod source code

https://github.com/NucDevStuff/AutoDeafen-Plus

### Your mod description

An extension to auto deafen, where you can make presets for auto deafen in each level that automatically load upon entering that level, including in different start positions. Note: Only uses legacy (2.1) percentages for now.

**Comment by Cvolton** [comment]
appears to crash while pausing the game for me? not sure if this is a mod conflict or some bigger issue though

[2024-02-27_03-48-39.log](https://github.com/geode-sdk/indexer/files/14424698/2024-02-27_03-48-39.log)
