### ISSUE TITLE
Update FuckGlow

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1095]
### Your mod link

https://github.com/RayDeeUx/FuckGlow/releases/download/v1.1.0/raydeeux.fuckglow.geode

### Your mod source code

https://github.com/RayDeeUx/FuckGlow/

### Your mod description

Remove conflict with [Capeling/gamemode-picker](https://github.com/Capeling/gamemode-picker). As a consequence, macOS support removed.

**Comment by Cvolton** [comment]
sad day for the one person playing on mac

**Comment by Cvolton** [comment]
!accept
