### ISSUE TITLE
Add Shortcuts Menu

### ISSUE THREAD

**Issue by Khronophobia** [geode-sdk/indexer#1103]
### Your mod link

https://github.com/Khronophobia/Shortcuts-Menu/releases/download/v1.0.0/khronophobia.shortcuts_menu.geode

### Your mod source code

https://github.com/Khronophobia/Shortcuts-Menu

### Your mod description

Adds a menu that takes you to various parts of the game accessible through a button.

**Comment by Fleeym** [comment]
!accept
