### ISSUE TITLE
Add ControlVanillaSFX

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1110]
### Your mod link

https://github.com/RayDeeUx/ControlVanillaSFX/releases/download/v1.0.0/raydeeux.controlvanillasfx.geode

### Your mod source code

https://github.com/RayDeeUx/ControlVanillaSFX

### Your mod description

# ControlVanillaSFX

Control the volume of SFX from vanilla GD separately from the volume of SFX from a level's SFX triggers.

To change the volume of vanilla SFX, use this mod's custom settings (see video demo below).

Video demo:

https://github.com/RayDeeUx/ControlVanillaSFX/assets/51521765/62e4522e-1add-40d5-887f-35f2b7aa51be

(Disclaimer: Other Geode mods were active while demonstrating this mod.)

This mod is exclusive to Windows.

**Comment by Cvolton** [comment]
!accept
