### ISSUE TITLE
Add NoOnlineLevelDelete

### ISSUE THREAD

**Issue by DoublefallingS** [geode-sdk/indexer#1111]
### Your mod link
https://github.com/DoublefallingS/NoOnlineLevelDelete/releases/download/v1.0.2/doublefallings.noonlineleveldelete.geode

### Your mod source code

https://github.com/DoublefallingS/NoOnlineLevelDelete

### Your mod description

Hides the button to delete your online levels to prevent accidents.

**Comment by Thegoldgames** [comment]
Version changed to v1.0.1. Mod link: https://github.com/Thegoldgames/NoOnlineLevelDelete/releases/download/v1.0.1/thegoldgames.noonlineleveldelete.geode

**Comment by coopeeo** [comment]
@Thegoldgames edit your original message and replace the line below `Your mod link` with your new download link.

**Comment by Cvolton** [comment]
!accept
