### ISSUE TITLE
Add Ambient Icons

### ISSUE THREAD

**Issue by Termantita** [geode-sdk/indexer#1112]
### Your mod link

https://github.com/Termantita/AmbientIcons/releases/download/v1.3.0/terma.ambienticons.geode

### Your mod source code

https://github.com/Termantita/AmbientIcons

### Your mod description

Changes the color of the icons based on the current color of the level (like YouTube Ambient Mode). In last version (1.3.0) added support to LevelEditorLayer too (this mod works on PlayLayer and LevelEditorLayer)!

**Comment by Cvolton** [comment]
!accept
