### ISSUE TITLE
ProfileImage v2

### ISSUE THREAD

**Issue by user95401** [geode-sdk/indexer#1117]
### Your mod link

https://github.com/user95401/ProfileImage/releases/download/v2/user95401.profile_image.geode

### Your mod source code

https://github.com/user95401/ProfileImage/tree/v2

### Your mod description

# Profile Image

u can set ur image on

- profile btn
- profile page 

### and
- others who installed that will see ur profile and stuff yea
- may support gdps unno

![image](https://github.com/geode-sdk/indexer/assets/90561697/3be433ab-a42e-41da-8910-0f50bbf5aa1c)
![image](https://github.com/geode-sdk/indexer/assets/90561697/2276f9f7-69b2-46b0-858f-675119b6ee06)

**Comment by Cvolton** [comment]
the mod uses node ids provided by the node ids mod, can you add it as a dependency into mod.json?

**Comment by user95401** [comment]
if I add this, the mod will not build... ok i can

**Comment by user95401** [comment]
![image](https://github.com/geode-sdk/indexer/assets/90561697/f9a5c59d-aee9-47da-89fb-e1b5d33f4a8f)
updated

**Comment by Cvolton** [comment]
!accept
