### ISSUE TITLE
Custom Name v1.3.1 (FIXES CRASHING ISSUES)

### ISSUE THREAD

**Issue by coopeeo** [geode-sdk/indexer#1126]
### Your mod link

https://github.com/coopeeo/customname-geodemod/releases/download/1.3.1/coopeeo.customname.geode

### Your mod source code

https://github.com/coopeeo/customname-geodemod/

### Your mod description

Make yourself have your own name. (Only appears for yourself)

## New This Update
* Fixed Crashing
### Also from 1.3.0
* Added Support For Level Info Pages
* Added Support For Level Search/Browser Pages

**Comment by Cvolton** [comment]
!accept
