### ISSUE TITLE
Add ChangeFont19

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1127]
### Your mod link

https://github.com/RayDeeUx/ChangeFont19/releases/download/v1.0.0/alphalaneous_raydeeux.changefont19.geode

### Your mod source code

https://github.com/RayDeeUx/ChangeFont19

### Your mod description

# ChangeFont19

Changes Font 19 in Geometry Dash to the official Minecraft font.
Applies across all graphics settings; use the highest quality settings for best results.

Based on [this wonderful tweet](https://twitter.com/bitzelyt/status/1351621941443125255) by @[BitzelYT](https://twitter.com/BitzelYT/).

Credits:
- [Alphalaneous](https://github.com/Alphalaneous) for the base code from [Happy Textures](https://github.com/Alphalaneous/HappyTextures/), reused with permission.
- [RayDeeUx](https://github.com/RayDeeUx) for the idea, font resources, and mod logo.

Special thanks to [YellowCat98](https://github.com/YellowCat98) for suggesting Sprite Font Builder to generate the resources.
Additional thanks to [Magpipe](https://www.youtube.com/channel/UC4NJ3nwh1oG9IeS64vyoPwQ) for publishing Subwoofer Lullaby (the level) and making it easier to test font sizes.
Thanks to [Mojang](https://mojang.com) for releasing Minecraft and for making such an iconic font.

Before ChangeFont19:
![antiDemoOne](https://github.com/geode-sdk/indexer/assets/51521765/8b3fda1a-5171-4d75-b062-2c6efdeb6491)

After ChangeFont19:
![demoOne](https://github.com/geode-sdk/indexer/assets/51521765/e0b8ba99-23b1-468d-83aa-c30989a4b1ca)

**Comment by Fleeym** [comment]
!accept
