### ISSUE TITLE
Add FuckPlayButton

### ISSUE THREAD

**Issue by GlebCraft** [geode-sdk/indexer#1141]
### Your mod link

https://github.com/GlebCraft/FuckPlayButton/releases/download/Release/glebcraft.fuckplaybutton.geode

### Your mod source code

https://github.com/GlebCraft/FuckPlayButton

### Your mod description

Removes play button from MenuLayer (no longer play official levels).

**Comment by Weebifying** [comment]
looks like someone is not a big fan of hexagon force

**Comment by GlebCraft** [comment]
> looks like someone is not a big fan of hexagon force

actuallyyyyyy🤓🤓

**Comment by altalk23** [comment]
please rename the mod to something more appropriate
fod ~~daddy~~ mommy does not like it

**Comment by RayDeeUx** [comment]
ok pardon me for a sec but why is this a mod

no seriously, the official levels are there for easily beta-testing playlayer-related mods
