### ISSUE TITLE
Add Garage In Editor

### ISSUE THREAD

**Issue by Naxrin** [geode-sdk/indexer#1142]
### Your mod link

https://github.com/Naxrin/Garage-in-Editor/releases/download/Initial/naxrin.garage_in_editor.geode

### Your mod source code

https://github.com/Naxrin/Garage-in-Editor

### Your mod description

This mod does nothing but adding an extra icon garage entry at the Editor level entrance. Why not?

**Comment by Naxrin** [comment]
New Version Fix
Mod Link:
https://github.com/Naxrin/Garage-in-Editor/releases/download/v1.1.0/naxrin.garage_in_editor.geode
Source Code:
https://github.com/Naxrin/Garage-in-Editor
Changelog:
1. Fix position bug in Non-16/9 ratio display
2. float slider to freely customize the offset yourself

**Comment by Fleeym** [comment]
you should create a separate entry for 1.1.0

**Comment by Naxrin** [comment]
> you should create a separate entry for 1.1.0

ok done

**Comment by Cvolton** [comment]
superseded by #1225
