### ISSUE TITLE
Add "Geometrize2GD" (v1.1.0)

### ISSUE THREAD

**Issue by ShineUA** [geode-sdk/indexer#1144]
### Your mod link

https://github.com/ShineUA/geometrize2gd-mod-geode/releases/download/v1.1.0/shineua.geometrize2gd.geode

### Your mod source code

https://github.com/ShineUA/geometrize2gd-mod-geode/tree/v1.1.0

### Your mod description

Same as before, but I added Android support and clarified tutorial.

**Comment by Cvolton** [comment]
!accept
