### ISSUE TITLE
Add HidePlayButton

### ISSUE THREAD

**Issue by GlebCraft** [geode-sdk/indexer#1145]
### Your mod link

https://github.com/GlebCraft/HidePlayButton/releases/download/Release/glebcraft.HidePlayButton.geode

### Your mod source code

https://github.com/GlebCraft/HidePlayButton

### Your mod description

Removes play button from MenuLayer (no longer play official levels).  
(this was named F#ckPlayButton before i knew new guidelines)

**Comment by GlebCraft** [comment]
don't ask please why did i make this (funi)

**Comment by Cvolton** [comment]
the capital letters in the mod id are gonna cause issues once we move over to the new index, would recommend changing these to lower case

**Comment by Cvolton** [comment]
currently rejecting for the aforementioned reason, though with the influx of "hide x" mods and menulayer mods in general i'm not sure whether this could pass even while meeting that requirement
