### ISSUE TITLE
Geooqd quotrs

### ISSUE THREAD

**Issue by Uproxide** [geode-sdk/indexer#1150]
### Your mod link

https://github.com/Uproxide/quotes-geode/releases/download/1.1.0/uproxide.quotes.geode

### Your mod source code

https://github.com/Uproxide/quotes-geode/

### Your mod description

![canvas](https://github.com/geode-sdk/indexer/assets/153382689/bd096d4e-a24e-4434-9dea-f29766100908)

**Comment by Cvolton** [comment]
idk tier imo
