### ISSUE TITLE
Update editor save button v1.0.2

### ISSUE THREAD

**Issue by slammy333** [geode-sdk/indexer#1153]
### Your mod link

https://github.com/slammy333/gd-editor-save-button/releases/download/v1.0.2/slammy333.save_button.geode

### Your mod source code

https://github.com/slammy333/gd-editor-save-button

### Your mod description

A simple Geometry Dash mod that adds a save level button to the editor UI.

v1.0.2 changelog:
* Added github link to mod.json
* Fixed UI conflict with BetterEdit
* Fixed bug where save button doesn't hide during playtesting

**Comment by Cvolton** [comment]
!accept
