### ISSUE TITLE
Add Percentage Suicide

### ISSUE THREAD

**Issue by MarioMastr** [geode-sdk/indexer#1161]
### Your mod link

https://github.com/MarioMastr/Percentage-Suicide/releases/download/v1.0.0/mariomastr.percentage_suicide.geode

### Your mod source code

https://github.com/MarioMastr/Percentage-Suicide

### Your mod description

kills player when they hit a percentage value

**Comment by Cvolton** [comment]
Missing/unchanged about.md. Please consider writing one to let the user know what they are downloading.
