### ISSUE TITLE
Add Player Sizer

### ISSUE THREAD

**Issue by MadMincraftr** [geode-sdk/indexer#1163]
### Your mod link

https://github.com/MadMincraftr/GDPlayerSizer/releases/download/1.0.0/pinktarr.player_sizer.geode

### Your mod source code

https://github.com/MadMincraftr/GDPlayerSizer/

### Your mod description

Resizes the player!

**Comment by MadMincraftr** [comment]
Heres were i realized... i forgot to make the mod icon 💀💀💀

**Comment by MadMincraftr** [comment]
i might fix it if this gets approved

**Comment by Cvolton** [comment]
can you add node ids mod as a dependency in mod.json? since you use the menu in pauselayer it provides
