### ISSUE TITLE
Update OpenHack to 2.0.1

### ISSUE THREAD

**Issue by Prevter** [geode-sdk/indexer#1217]
### Your mod link

https://github.com/Prevter/GDOpenHack/releases/download/2.0.1/prevter.openhack.geode

### Your mod source code

https://github.com/Prevter/GDOpenHack

### Your mod description

- Fixed a crash during the game launch if you've unfocused the game window
- Fixed a crash for GDPS users, if executable name is not "GeometryDash.exe"

**Comment by matcool** [comment]
!accept
