### ISSUE TITLE
Update Garage in Editor

### ISSUE THREAD

**Issue by Naxrin** [geode-sdk/indexer#1225]
### Your mod link

https://github.com/Naxrin/Garage-in-Editor/releases/download/v1.1.0/naxrin.garage_in_editor.geode

### Your mod source code

https://github.com/Naxrin/Garage-in-Editor

### Your mod description

Changelog:

Fix position bug in Non-16/9 ratio display
Float slider to freely customize the offset yourself

**Comment by Cvolton** [comment]
!accept
