### ISSUE TITLE
Update WSLiveEditor (1.0.2)

### ISSUE THREAD

**Issue by iAndyHD3** [geode-sdk/indexer#1238]
### Your mod link

https://github.com/iAndyHD3/WSLiveEditor/releases/download/v1.0.2/iandyhd3.wsliveeditor.geode

### Your mod source code

https://github.com/iAndyHD3/WSLiveEditor

### Your mod description

WSLiveEditor is a helpful tool for quick testing levels that are generated programmatically by a tool, by opening a Websocket Server it allows to remove old objects and add new ones without needing to re-open the editor or restart the game.

1.0.2 changelog:
- add `COLOR_ACTION`
- update logo

**Comment by Cvolton** [comment]
!accept
