### ISSUE TITLE
Robloxify

### ISSUE THREAD

**Issue by Bingy3** [geode-sdk/indexer#1239]
### Your mod link

https://github.com/Bingy3/gd-robloxify/releases/download/Robloxify/bingy3.robloxify.geode

### Your mod source code

https://github.com/Bingy3/gd-robloxify

### Your mod description

This mod changes the menu layer.

**Comment by RayDeeUx** [comment]
direct conflict with yellowcat's gdlite mod (crash)

**Comment by Cvolton** [comment]
superseded by #1255

**Comment by Bingy3** [comment]
I fixed it I think
