### ISSUE TITLE
Lower Add Comment

### ISSUE THREAD

**Issue by AlvyDaGreat** [geode-sdk/indexer#1242]
### Your mod link

https://github.com/AlvyDaGreat/gd-movecommentdown/releases/download/Release/alvy.movecommentdown.geode

### Your mod source code

https://github.com/AlvyDaGreat/gd-movecommentdown

### Your mod description

it lowers the comment menu
like it just moves it down
like it just does that
i know
insane

**Comment by BeatACVR** [comment]
lower add comment?

**Comment by Cvolton** [comment]
!accept
