### ISSUE TITLE
Update Ambient Icons (v1.3.0 -> v1.3.1)

### ISSUE THREAD

**Issue by Termantita** [geode-sdk/indexer#1243]
### Your mod link

https://github.com/Termantita/AmbientIcons/releases/download/v1.3.1/terma.ambienticons.geode

### Your mod source code

https://github.com/Termantita/AmbientIcons/tree/v1.3.1

## v1.3.1 Changes
* **Updated** for Geode Beta 21
* **Added** changelog.md
* **Fixed** performance issues (0ms update time now can be used)
* **Added** ambient glow support and its mod option
* **Added** ambient wave trail support and its mod option
* **Reduced** *update time* limit to 1000ms
* **Added** *Set X* and *Set Y* options for adjusting where to get the colors
* **Reduced** mod tags to one

**Comment by Cvolton** [comment]
!accept
