### ISSUE TITLE
Update Rainbow Icon Mod to 1.0.2

### ISSUE THREAD

**Issue by shadowforce78** [geode-sdk/indexer#1249]
### Your mod link

https://github.com/shadowforce78/Rainbow-Icon/releases/download/1.0.2/saumondeluxe.rainbow_icon.geode

### Your mod source code

https://github.com/shadowforce78/Rainbow-Icon

### Your mod description

- Added Saturation settings
- Remade the mod icon for a better looks in geode loader
- Thx beat for this update

**Comment by Cvolton** [comment]
!accept
