### ISSUE TITLE
Update "Auto priority to high" (v1.0.1)

### ISSUE THREAD

**Issue by elnexreal** [geode-sdk/indexer#1262]
### Your mod link

https://github.com/elnexreal/autoSetPriority/releases/download/1.0.1/elnexreal.auto_priority.geode

### Your mod source code

https://github.com/elnexreal/autoSetPriority

**Comment by elnexreal** [comment]
for some reason i forgot to bump the version lmao

**Comment by Cvolton** [comment]
!accept
