### ISSUE TITLE
Update Ambient Icons (v1.3.1 -> v1.3.2)

### ISSUE THREAD

**Issue by Termantita** [geode-sdk/indexer#1264]
### Your mod link

https://github.com/Termantita/AmbientIcons/releases/download/v1.3.2/terma.ambienticons.geode

### Your mod source code

https://github.com/Termantita/AmbientIcons/tree/v1.3.2

### Your mod description

- **Added** link to *GitHub* Repo
- **Added** performance warning with Globed in mod's info
- **Added** incompatibility warning with Rainbow Icon in mod's info
- **Added** incompatibility warning with Blending Glow in ambient glow's info (both items thanks to Erymanthus)
- **Added** - Now the mod doesn't pick colors if all changing options are disabled (except Player Flash)

**Comment by Cvolton** [comment]
!accept
