### ISSUE TITLE
Azure Utils

### ISSUE THREAD

**Issue by zkayns** [geode-sdk/indexer#1266]
### Your mod link

https://github.com/zkayns/Azure-Utils/releases/download/v1.0.1/azurebluet.azure_utils.geode

### Your mod source code

https://github.com/zkayns/Azure-Utils

### Your mod description

Adds some neato keybinds that do neato thingies

**Comment by RayDeeUx** [comment]
> ```
> "dependencies": [
>   {
>     "id": "geode.custom-keybinds",
>     "version": "v1.1.0",
>     "required": true
>   }
> ],
> ```
to bring your geode mod up to current expectations, please replace `"required": true` with `"importance": "required"`

**Comment by zkayns** [comment]
done

**Comment by RayDeeUx** [comment]
currently crashes with `zalphalaneous.minecraft`

**Comment by RayDeeUx** [comment]
[2024-02-29_22-47-20.log](https://github.com/geode-sdk/indexer/files/14456176/2024-02-29_22-47-20.log)
