### ISSUE TITLE
Update GD in 2019 to 2.0.3 (last one i swear)

### ISSUE THREAD

**Issue by GDColon** [geode-sdk/indexer#1270]
### Your mod link

https://github.com/GDColon/gd-in-2019/releases/download/v2.0.3/colon.gd_in_2019.geode

### Your mod source code

https://github.com/GDColon/gd-in-2019

**Comment by camila314** [comment]
!approve

**Comment by camila314** [comment]
im stupid

**Comment by camila314** [comment]
!accept
