### ISSUE TITLE
Add Confirm Practice/Restart v1.0.0

### ISSUE THREAD

**Issue by xiyxs** [geode-sdk/indexer#1278]
### Your mod link

https://github.com/xiyxs/Confirm-Practice-Restart/releases/download/v1.0.0/xiyxs.confirmpracticerestart.geode

### Your mod source code

https://github.com/xiyxs/Confirm-Practice-Restart

### Your mod description

Shows a confirmation menu when you try to practice/restart/full restart.

**Comment by Cvolton** [comment]
!accept
