### ISSUE TITLE
Add "Auto Deafen" (v1.0.2)

### ISSUE THREAD

**Issue by elnexreal** [geode-sdk/indexer#1288]
### Your mod link

https://github.com/elnexreal/AutoDeafen_geode/releases/download/1.0.2/elnexreal.auto_deafen.geode

### Your mod source code

https://github.com/elnexreal/AutoDeafen_geode

### Your mod description

My mod allows you to auto deafen on a certain percentage when playing a level.

**Comment by Cvolton** [comment]
!accept
