### ISSUE TITLE
Update Rainbow Icon to V1.0.3

### ISSUE THREAD

**Issue by shadowforce78** [geode-sdk/indexer#1290]
### Your mod link

https://github.com/shadowforce78/Rainbow-Icon/releases/download/1.0.3/saumondeluxe.rainbow_icon.geode

### Your mod source code

https://github.com/shadowforce78/Rainbow-Icon

### Your mod description

- Added tags to mod.json
- Added Shortcut btn to open settings
- Added preset settings for easier use
- Added Incompatibility issues

**Comment by Cvolton** [comment]
!accept
