### ISSUE TITLE
Add Skip Editor Save Confirm

### ISSUE THREAD

**Issue by Bigmancozmo** [geode-sdk/indexer#1313]
### Your mod link

https://github.com/Bigmancozmo/Skip-Editor-Save-Confirm/releases/download/v1.0.0/bigmancozmo.skip_editor_save_confirm.geode

### Your mod source code

https://github.com/Bigmancozmo/Skip-Editor-Save-Confirm

### Your mod description

Skips the save confirmation in the editor, with some additional configuration.

**Comment by Cvolton** [comment]
!accept
