### ISSUE TITLE
Update ScrollAnyInput 1.0.0 -> 1.1.0

### ISSUE THREAD

**Issue by TpdeaX** [geode-sdk/indexer#1329]
### Your mod link

https://github.com/TpdeaX/ScrollAnyInput-Geode/releases/download/Release_1/tpdea.scroll_any_input.geode

### Your mod source code

https://github.com/TpdeaX/ScrollAnyInput-Geode

### Your mod description

epic

**Comment by Cvolton** [comment]
!accept
