### ISSUE TITLE
Update SceneSwitcher 1.0.0 -> 1.1.0

### ISSUE THREAD

**Issue by TpdeaX** [geode-sdk/indexer#1333]
### Your mod link

https://github.com/TpdeaX/SceneSwitcher-Geode/releases/download/Release_1/tpdea.sceneswitcher.geode

### Your mod source code

https://github.com/TpdeaX/SceneSwitcher-Geode

### Your mod description

epic

**Comment by RayDeeUx** [comment]
ok something is terribly wrong here

**Comment by RayDeeUx** [comment]
the download link is going to be terribly wrong for folks with both mods installed

**Comment by TpdeaX** [comment]
I guess it should be ready :n

**Comment by Cvolton** [comment]
!accept
