### ISSUE TITLE
Add Rating Info

### ISSUE THREAD

**Issue by polskidevv** [geode-sdk/indexer#1334]
### Your mod link

https://github.com/polskidevv/RatingInfo/releases/download/1.0.0/polsk.ratinginfo.geode

### Your mod source code

https://github.com/polskidevv/RatingInfo

### Your mod description

shows info when clicking the difficulty faces in levelinfolayer

**Comment by Cvolton** [comment]
the mod is 120 lines of code the least u could do is write positioning properly......

**Comment by Cvolton** [comment]
superseded by #1624
