### ISSUE TITLE
Add Geometwy dash

### ISSUE THREAD

**Issue by jojo989** [geode-sdk/indexer#1349]
### Your mod link

https://github.com/jojo989/geometwy-dash/releases/download/v1/jojo989.geometwy_dash.geode

### Your mod source code

https://github.com/jojo989/geometwy-dash

### Your mod description

my mod replaces almost every r + l with w's

the code is pretty shit tho

**Comment by RayDeeUx** [comment]
mf ported https://github.com/kerbybit/MinecwaftOwO to geometry dash wtf

**Comment by Cvolton** [comment]
> Missing/unchanged about.md. Please consider writing one to let the user know what they are downloading.

**Comment by jojo989** [comment]
ok, i changed about.md now! :D

**Comment by Cvolton** [comment]
!accept
