### ISSUE TITLE
Add DisturbingNewBests

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1366]
### Your mod link

https://github.com/RayDeeUx/DisturbingNewBests/releases/download/v1.1.0/raydeeux.disturbingnewbests.geode

### Your mod source code

https://github.com/RayDeeUx/DisturbingNewBests

### Your mod description

# DisturbingNewBests

Replaces "New Best" messages with slightly "better" ones, including those of your own choice.

Allows three sets of messages: a default set, custom text from the config folder, and (ad-friendly) Brandon Rogers quotes.

Custom messages defined from the `custom.txt` file within the mod's config directory will be formatted as follows: `- lorem ipsum -` in order to distinguish them from the default set of messages.

As tempting as it would be to have a regex filter to moderate messages found in `custom.txt`, this mod will not be pulling double duty by attempting to solve the Scunthorpe problem.

Quotes originated from a variety of sources, including various members of the Geode SDK Discord server, Brandon Rogers, and Adam Neylan.

Logo contributions by sofabeddd.

Level featured in `logo.png` and `demoOne.png`: Unnamed 84 by 4y4.

Built-in quotes moderated by CatXus and alk.

Original mod idea by [actualkanyewest](https://gdbrowser.com/u/28091796).

This [Geode mod](https://geode-sdk.org) is licensed under LGPLv2, and may be prone to bugs on macOS as the mod index on macOS grows...

![demoOne](https://github.com/geode-sdk/indexer/assets/51521765/02080d87-9264-4953-9983-31c6dcdb5b06)

**Comment by Cvolton** [comment]
!accept
