### ISSUE TITLE
Add NoMoreGrayFilter

### ISSUE THREAD

**Issue by PetitFrapo** [geode-sdk/indexer#1374]
### Your mod link

https://github.com/PetitFrapo/NoMoreGrayFilter/releases/download/v1.0.2/petitfrapo.nomoregrayfilter.geode

### Your mod source code

https://github.com/PetitFrapo/NoMoreGrayFilter

### Your mod description

This mod removes the gray filter on the Event, Map and Versus buttons in CreatorLayer. This is a cosmetic change that pleases the eye as it makes it feel like 2.2 is fully finished, plus seeing these textures in their full coloured glory is a perfect small change to the game.

**Comment by Cvolton** [comment]
can you add node ids mod as a dependency since you use creatorlayer node ids

**Comment by PetitFrapo** [comment]
Done, sorry I didn't know it was from a mod, I thought it was vanilla Geode. I updated the link on my original comment with the new release.

**Comment by PetitFrapo** [comment]
uh i changed it again, i put v1.7.0 of node ids instead of 1.8.1, fixed.

**Comment by Cvolton** [comment]
1.7.0 would've still been fine, since the required ids are already available there, no harm in being safe by requiring the latest version though

**Comment by Cvolton** [comment]
!accept
