### ISSUE TITLE
Update custom gamemode icons

### ISSUE THREAD

**Issue by RoootTheFox** [geode-sdk/indexer#1386]
### Your mod link

https://github.com/RoootTheFox/custom-gamemode-colors/releases/download/v0.1.2/rooot.custom-gamemode-colors.geode

### Your mod source code

https://github.com/RoootTheFox/custom-gamemode-colors

### Your mod description

updat
globe support
some bug fixes
yes

update: make dank meme happy

**Comment by RoootTheFox** [comment]
h

**Comment by dankmeme01** [comment]
!accept

**Comment by dankmeme01** [comment]
hiiii

**Comment by RoootTheFox** [comment]
haii!!

**Comment by dankmeme01** [comment]
!accept
