### ISSUE TITLE
Add AutoDeafen

### ISSUE THREAD

**Issue by Lynxdeer** [geode-sdk/indexer#1410]
### Your mod link

https://github.com/Lynxdeer/AutoDeafen/releases/download/release/lynxdeer.autodeafen.geode

### Your mod source code

https://github.com/Lynxdeer/AutoDeafen

### Your mod description

# AutoDeafen
### Includes:
* A neat config menu in the pause menu (Compatible with BetterPause)
* Configurable Percentage per-level
* Configurable Keybind
* Undeafening on win/death
### Screenshots
![image](https://github.com/geode-sdk/indexer/assets/79340005/baa76039-4229-40dc-bb8b-88b07981a579)
![image](https://github.com/geode-sdk/indexer/assets/79340005/f53fdf36-839d-4802-a4f3-9eef9e9bf979)

**Comment by Cvolton** [comment]
!accept
