### ISSUE TITLE
Update Ambient Icons (v1.3.2 > v1.4.2)

### ISSUE THREAD

**Issue by Termantita** [geode-sdk/indexer#1411]
### Your mod link

https://github.com/Termantita/AmbientIcons/releases/download/v1.4.2/terma.ambienticons.geode

### Your mod source code

https://github.com/Termantita/AmbientIcons/tree/v1.4.2

### Your mod description

- **Added** `Node IDs` as a dependency
- **Added** conflicting mod incompatibilities in mod.json

Now on Windows and Android :3

**Comment by Cvolton** [comment]
!accept
