### ISSUE TITLE
Add Comment in Pause menu

### ISSUE THREAD

**Issue by mishpro-programm** [geode-sdk/indexer#1418]
### Your mod link

https://github.com/mishpro-programm/infoinpause/releases/download/v1.0.0/mishpro.comments_in_pause_menu.geode

### Your mod source code

https://github.com/mishpro-programm/infoinpause

### Your mod description

This mod adds a button in pause menu that allows to view level comments. Can be used as text chat for globed

**Comment by RayDeeUx** [comment]
slight issue with the `mod.json`: it's `"win": "2.204"`, not `"windows": "2.204"`

**Comment by mishpro-programm** [comment]
> slight issue with the `mod.json`: it's `"win": "2.204"`, not `"windows": "2.204"`

Ok, will open new issue
