### ISSUE TITLE
Add Comments in Pause menu

### ISSUE THREAD

**Issue by mishpro-programm** [geode-sdk/indexer#1419]
### Your mod link

https://github.com/mishpro-programm/infoinpause/releases/download/v1.0.0-1/mishpro.comments_in_pause_menu.geode

### Your mod source code

https://github.com/mishpro-programm/infoinpause

### Your mod description

This mod adds a button that allows to view level comments in pause menu, not exiting level

**Comment by Cvolton** [comment]
!accept
