### ISSUE TITLE
Add ModifyLoadingLayer

### ISSUE THREAD

**Issue by YellowCat98** [geode-sdk/indexer#1430]
### Your mod link

https://github.com/YellowCat98/ModifyLoadingLayer/releases/download/1.0.0/yellowcat98.modifyloadinglayer.geode

### Your mod source code

https://github.com/YellowCat98/ModifyLoadingLayer

### Your mod description

This mod lets you change the sprite of any sprite in LoadingLayer.

**Comment by Cvolton** [comment]
!accept
