### ISSUE TITLE
Update LikeBaitExterminator to v1.1.0

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1436]
### Your mod link

https://github.com/RayDeeUx/LikeBaitExterminator/releases/download/v1.1.0/raydeeux.likebaitexterminator.geode

### Your mod source code

https://github.com/RayDeeUx/LikeBaitExterminator

### Your mod description

Adds a toggle to only apply the likebait filter on daily/weekly levels.

Supports Windows (tested), Android (untested), and macOS (untested).

**Comment by Cvolton** [comment]
!accept
