### ISSUE TITLE
Add BreakingPlatforming

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1437]
### Your mod link

https://github.com/RayDeeUx/BreakingPlatforming/releases/download/v1.1.0/raydeeux.breakingplatforming.geode

### Your mod source code

https://github.com/RayDeeUx/BreakingPlatforming

### Your mod description

# BreakingPlatforming

"Platformer level creators hate this one simple trick!"

Ever wondered if a platformer level has checkpoints? Want to tailor every platformer level to your preferences without constantly opening/reopening the level editor? Have at it with BreakingPlatforming.

Checkpoint-related notifications keep you informed on a platformer level's checkpoint count.

Adjust every setting related to solid blocks (and gameplay elements) to your heart's content. (Well, *almost* every setting. "NoTouch" is still quite difficult to deal with and has been supplemented with a toggleable Noclip-esque option for hazards only.)

This Geode mod is licensed under LGPLv2, and is unavailable for macOS.

**Comment by Cvolton** [comment]
!accept
