### ISSUE TITLE
my mincraftify! is not minecraftifying...

### ISSUE THREAD

**Issue by GD-phkxv** [geode-sdk/indexer#1439]
[2024-03-09_08-19-02.log](https://github.com/geode-sdk/indexer/files/14545117/2024-03-09_08-19-02.log)
help?
pls?

**Comment by coopeeo** [comment]
@GD-phkxv make an [issue](https://github.com/Alphalaneous/Minecraft-UI-in-GD/issues) on their [GitHub repository](https://github.com/Alphalaneous/Minecraft-UI-in-GD)
