### ISSUE TITLE
Add Separate Dual Icons

### ISSUE THREAD

**Issue by Weebifying** [geode-sdk/indexer#1476]
### Your mod link

https://github.com/Weebifying/separate-dual-icons-geode/releases/download/v1.0.1/weebify.separate_dual_icons.geode

### Your mod source code

https://github.com/Weebifying/separate-dual-icons-geode

### Your mod description

thank you cvolton very cool

**Comment by Weebifying** [comment]
dont accept yet!!

**Comment by Cvolton** [comment]
!accept
