### ISSUE TITLE
Add InDeCreaseIcons 0.0.3

### ISSUE THREAD

**Issue by user95401** [geode-sdk/indexer#1485]
### Your mod link

https://github.com/user95401/InDeCreaseIcons/releases/download/beta3/ruhax.indecreaseicons.geode

### Your mod source code

https://github.com/user95401/InDeCreaseIcons

### Your mod description

# patch values of maximum icons count
![image](https://github.com/user95401/InDeCreaseIcons/assets/90561697/20b80fff-84d1-49d9-ab85-2f5bb5629ada)

**Comment by user95401** [comment]
hereisno android btw

**Comment by user95401** [comment]
a

**Comment by SpaghettDev** [comment]
Your mod crashes when changing pages in the Garage after increasing the robot or spider icon count. Works fine with the other icons.

**Comment by user95401** [comment]
oh yeaa forgot that

**Comment by user95401** [comment]
needs fix of config copy stuff

**Comment by user95401** [comment]
settings copy fixed now
