### ISSUE TITLE
Update user95401.mainlevelseditor v4 => v5

### ISSUE THREAD

**Issue by user95401** [geode-sdk/indexer#1496]
### Your mod link

https://github.com/user95401/MainLevelsEditor/releases/download/v5-release/user95401.mainlevelseditor.geode

### Your mod source code

https://github.com/user95401/MainLevelsEditor

### Your mod description

edit main levels and other leveltools stuff

v5:

- stat gain guard
- online levels setup ability (experimental and unfinished)
- buttons for helpers
- some settings

**Comment by Cvolton** [comment]
!accept
