### ISSUE TITLE
ABot

### ISSUE THREAD

**Issue by asc11ts** [geode-sdk/indexer#1498]
### Your mod link

https://github.com/asc11ts/ABot-GDBot/releases/download/mod/qwqascii.abot.geode

### Your mod source code

https://github.com/asc11ts/ABot-GDBot

### Your mod description

Mod for showcases. Free and easy to use. :3

**Comment by RayDeeUx** [comment]
code theft: https://www.diffchecker.com/rEJ9lg95/

**Comment by RayDeeUx** [comment]
code theft part two: https://www.diffchecker.com/ynfVhXQd/

**Comment by Prevter** [comment]
lmao

**Comment by Bean0of** [comment]
insane

**Comment by matcool** [comment]
hey if youre going to outright copy a whole project at least put some credit and ask the original creator

**Comment by asc11ts** [comment]
> hey if youre going to outright copy a whole project at least put some credit and ask the original creator

👌
