### ISSUE TITLE
Add WholesomeEndTexts

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1500]
### Your mod link

https://github.com/RayDeeUx/WholesomeEndTexts/releases/download/v1.1.1/raydeeux.wholesomeendtexts.geode

### Your mod source code

https://github.com/RayDeeUx/WholesomeEndTexts/

### Your mod description

# WholesomeEndTexts

Replaces "Level Complete" texts with wholesome ones, including those of your own choice. The antithesis of DisturbingNewBests.

Allows three sets of messages: a default set, custom text from the config folder, and Technoblade quotes.

Also comes with other customization options for the "Level Complete" screen, including an option to show attempts and jumps on platformer levels.

Custom messages defined from the `custom.txt` file within the mod's config directory will be formatted as follows: `- lorem ipsum -` in order to distinguish them from the default set of messages. As tempting as it would be to have a regex filter to moderate messages found in `custom.txt`, this mod will not be pulling double duty by attempting to solve the Scunthorpe problem.

Quotes originated from a variety of sources, including various members of the Geode SDK Discord server, variations of comments from level ID 64760396 that didn't make it to update 2.2, Ted Lasso on Apple TV+, and Technoblade.

End text positioning, sizing, and wrapping by [sofabeddd](https://gdbrowser.com/u/7976112).

This [Geode mod](https://geode-sdk.org) is licensed under LGPLv2.

![demoOne](https://github.com/geode-sdk/indexer/assets/51521765/34676d32-715f-4d7c-9322-d3fb24449c9c)

**Comment by Cvolton** [comment]
!accept
