### ISSUE TITLE
Add entry for "gay wave trail"

### ISSUE THREAD

**Issue by TheBearodactyl** [geode-sdk/indexer#1511]
### Your mod link

https://github.com/TheBearodactyl/gay-wave-trail/releases/download/1.0.7/the_bearodactyl.gay-wave-trail.geode

### Your mod source code

https://github.com/TheBearodactyl/gay-wave-trail

### Your mod description

uhhhhh, gay wave trail go brrr i guess

makes the wave trail a R A I N B O W when enabled. 

<details>
<summary>update so that the github bot works</summary>

One, two, three, uh
My baby don't mess around
Because she loves me so
And this I know fo sho (uh)
But does she really wanna
But can't stand to see me walk out the door? (Ah)
Don't try to fight the feeling
Because the thought alone is killin' me right now (uh)
Thank God for Mom and Dad
For sticking two together
'Cause we don't know how (c'mon)
Hey ya! Hey ya!
Hey ya! Hey ya!
Hey ya! Hey ya!
Hey ya! Hey ya!
You think you've got it
Oh, you think you've got it
But got it just don't get it 'til there's nothin' at all
We get together
Oh, we get together
But separate's always better when there's feelings involved
If what they say is
"Nothing is forever"
Then what makes, then what makes
Then what makes, then what makes (what makes, what makes)
Love the exception?
So why, oh, why, oh
Why, oh, why, oh, why, oh
Are we so in denial when we know we're not happy here?
(Y'all don't want to hear me, you just want to dance)
Hey ya! (Uh oh) Hey ya! (Uh oh)
Don't want to meet your daddy
Hey ya! (Uh oh)
Just want you in my Caddy (Uh oh)
Hey ya! (Uh oh)
Don't want to meet your mama
Hey ya! (Uh oh)
Just want to make you cum-a (Uh oh)
Hey ya! (Uh oh)
I'm, I'm, I'm just being honest (Uh oh)
I'm just being honest
Hey! Alright now
Alright now, fellas (Yeah?)
Now, what cooler than being cool? (Ice cold!)
I can't hear you
I say what's, what's cooler than being cool? (Ice cold!)
Alright, alright, alright, alright, alright
Alright, alright, alright, alright, alright
Alright, alright, alright, alright
Okay, now ladies (Yeah?)
Now, we gon' break this thang down in just a few seconds
Now, don't have me break this thang down for nothin'
Now, I want to see y'all on y'all baddest behavior
Lend me some sugar, I am your neighbor
Ah! Here we go
Shake it, shake, shake it, shake it, shake, shake it (Uh oh)
Shake it, shake, shake it, shake it, shake it (Uh oh)
Shake it like a Polaroid picture, hey ya!
Shake it, shake, shake it, shake it, shake, shake it
Shake it, shake it, shake it, sugar
Shake it like a Polaroid picture
Now, all Beyonce's, and Lucy Liu's
And baby dolls
Get on the floor
Get on the floor, you know what to do
You know what to do
You know what to do
Hey ya! (Uh oh) Hey ya! (Uh oh)
Hey ya! (Uh oh) Hey ya! (Uh oh)
Hey ya! (Uh oh) Hey ya! (Uh oh)
Hey ya! (Uh oh) Hey ya! (Uh oh)
</details>

**Comment by RayDeeUx** [comment]
ok so testing this on dash shows me that the shader triggers broke and none of the animated sprites animate

**Comment by RayDeeUx** [comment]
hold on i was recording in v1.0.1

**Comment by TheBearodactyl** [comment]
> hold on i wasn't recording in v1.0.1
> 
> edit for past tense. v1.0.1 works fine

just pushed a new update for cross platform btw

**Comment by RayDeeUx** [comment]
ok now for the more pressing issue: you need to specify the version of geometry dash it will work on

yes i know you want to be crossplatform but with how much more often robtop updates the game it's currently the best practice to specify the exact version for now

mac 2.200
android 2.205
windows 2.204

**Comment by TheBearodactyl** [comment]
> ok now for the more pressing issue: you need to specify the version of geometry dash it will work on
> 
> yes i know you want to be crossplatform but with how much more often robtop updates the game it's currently the best practice to specify the exact version for now
> 
> mac 2.200 android 2.205 windows 2.204

but it works on any version

**Comment by RoootTheFox** [comment]
No it won't, the mod will only run on 2.204 for windows for example. Android might work, but I wouldn't bet on that

**Comment by TheBearodactyl** [comment]
> No it won't, the mod will only run on 2.204 for windows for example. Android might work, but I wouldn't bet on that

it works on Android

**Comment by RoootTheFox** [comment]
but not windows, specifying gd * will break

**Comment by TheBearodactyl** [comment]
> but not windows, specifying gd * will break

lemme fix that then

**Comment by SpaghettDev** [comment]
specifying { "gd": "*" } is only really used with mods that *only* touch cocos and not the game's classes because the game engine rarely changes between updates, while the game's classes have to be found and added to the bidings repo.

**Comment by matcool** [comment]
at most you should only target `*` on android, but even thats flaky. only do windows if youre really sure

**Comment by RayDeeUx** [comment]
also the softtoggle still breaks everything like i said in my very first comment

https://github.com/geode-sdk/indexer/assets/51521765/1efb784d-1161-4f07-826d-70c817b7f87c

**Comment by TheBearodactyl** [comment]
@RayDeeUx it's fixed

**Comment by RoootTheFox** [comment]
@TheBearodactyl mac suffers from the same issue as windows, where it is not compatible with every version due to missing symbols - in fact its even worse than windows, because not even cocos has symbols on mac.

**Comment by TheBearodactyl** [comment]
> @TheBearodactyl mac suffers from the same issue as windows, where it is not compatible with every version due to missing symbols - in fact its even worse than windows, because not even cocos has symbols on mac.

@RoootTheFox I fixed the versions as well

**Comment by dankmeme01** [comment]
Why is this mod written in an inferior programming language?

**Comment by TheBearodactyl** [comment]
> Why is this mod written in an inferior programming language?

oh, i've already written a second version in rust, so once I've ported the basic stuff, it'll be miles better >:3

**Comment by TheBearodactyl** [comment]
> @TheBearodactyl update your original comment so the github action notices

@RoootTheFox it's fixed now

**Comment by TheBearodactyl** [comment]
so can it be added now?

**Comment by TheBearodactyl** [comment]
@RoootTheFox can it be added now?

**Comment by RoootTheFox** [comment]
i'm not one to decided that, i'm not a lead dev

**Comment by ItsJaid** [comment]
qolmod breaks this mod

**Comment by TheBearodactyl** [comment]
> qolmod breaks this mod

fixed

**Comment by ItsJaid** [comment]
> > qolmod breaks this mod
> 
> fixed

still broken

**Comment by TheBearodactyl** [comment]
> > > qolmod breaks this mod
> > 
> > 
> > fixed
> 
> still broken

it should be so that neither one is able to be loaded at once now, that's weird

**Comment by TheBearodactyl** [comment]
> > > qolmod breaks this mod
> > 
> > 
> > fixed
> 
> still broken

@ItsJaid fixed it, there was a typo lol

**Comment by ItsJaid** [comment]
> > > > qolmod breaks this mod
> > > 
> > > 
> > > fixed
> > 
> > 
> > still broken
> 
> it should be so that neither one is able to be loaded at once now, that's weird

oh, that's not what i expected 3:
i suppose that means there's nothing you can do to fix the incompat

**Comment by TheBearodactyl** [comment]
> > > > > qolmod breaks this mod
> > > > 
> > > > 
> > > > fixed
> > > 
> > > 
> > > still broken
> > 
> > it should be so that neither one is able to be loaded at once now, that's weird
> 
> oh, that's not what i expected 3:
> i suppose that means there's nothing you can do to fix the incompat

nah, this is just for until I've got enough time to figure out why qolmod breaks it

**Comment by ItsJaid** [comment]
> > > > > > qolmod breaks this mod
> > > > > 
> > > > > 
> > > > > fixed
> > > > 
> > > > 
> > > > still broken
> > > 
> > > 
> > > it should be so that neither one is able to be loaded at once now, that's weird
> > 
> > 
> > oh, that's not what i expected 3:
> > i suppose that means there's nothing you can do to fix the incompat
> 
> nah, this is just for until I've got enough time to figure out why qolmod breaks it

oh, alright

**Comment by Cvolton** [comment]
dont rly trust android * when playlayer member offsets are one of the few things that has been documented to change between minor 2.20x updates

**Comment by TheBearodactyl** [comment]
> dont rly trust android * when playlayer member offsets are one of the few things that has been documented to change between minor 2.20x updates but anyone else can chime in with a counterpoint if u have one

fixed

**Comment by LauchitaGD** [comment]
!accept

**Comment by TheBearodactyl** [comment]
LET'S GO
