### ISSUE TITLE
Add Better Unlock Info (v1.0.0)

### ISSUE THREAD

**Issue by Rynat86** [geode-sdk/indexer#1521]
### Your mod link

https://github.com/Rynat86/Better-Unlock-Info/releases/download/v1.0.0/rynat.better_unlock_info.geode

### Your mod source code

https://github.com/Rynat86/Better-Unlock-Info

### Your mod description

Changes icon unlock popup to include colors and more detailed information about unlocking the icon. Makes icons on profile page clickable to display the popup.

**Comment by Cvolton** [comment]
!accept
