### ISSUE TITLE
Update Confirm Practice/Restart to v1.0.1

### ISSUE THREAD

**Issue by xiyxs** [geode-sdk/indexer#1525]
### Your mod link

https://github.com/xiyxs/Confirm-Practice-Restart/releases/download/v1.0.1/xiyxs.confirmpracticerestart.geode

### Your mod source code

https://github.com/xiyxs/Confirm-Practice-Restart

### Your mod description

Fixed an issue caused by the "Custom Keybinds" mod where menus could be opened multiple times through a bind

**Comment by Cvolton** [comment]
!accept
