### ISSUE TITLE
Add user95401.window-name

### ISSUE THREAD

**Issue by user95401** [geode-sdk/indexer#1528]
### Your mod link

https://github.com/user95401/window-name/releases/download/v1/user95401.window-name.geode

### Your mod source code

https://github.com/user95401/window-name/

### Your mod description

![image](https://github.com/geode-sdk/indexer/assets/90561697/d57af635-26e8-4145-a6a7-68132d8c9a5d)
helluva cool mod

**Comment by Cvolton** [comment]
!accept
