### ISSUE TITLE
Featured List (attempt 2)

### ISSUE THREAD

**Issue by SkeletalVirus** [geode-sdk/indexer#1558]
### Your mod link

https://github.com/SkeletalVirus/featuredlists/blob/main/skeletalvirus.featuredlists.zip

### Your mod source code

https://github.com/SkeletalVirus/featuredlists

**Comment by SkeletalVirus** [comment]
mf the fuck you mean its not a zip file

**Comment by RoootTheFox** [comment]
- it is not the direct download link to the zip file: 
![image](https://github.com/geode-sdk/indexer/assets/78933889/58da8982-3515-4558-8a0e-84f7e4f2eb36)
- your geode file is INSIDE the zip file, which won't work: 
![image](https://github.com/geode-sdk/indexer/assets/78933889/c290550c-9061-4d85-a6c4-0e0744d58835)

tldr; extract the .geode file and put it in a GitHub release, and copy the link from that.
