### ISSUE TITLE
Add NoMoreSocials (1.0.0)

### ISSUE THREAD

**Issue by Cubentum** [geode-sdk/indexer#1570]
### Your mod link

https://github.com/Cubentum/NoMoreSocials/releases/download/v1.0.0/cubentum.nomoresocials.geode

### Your mod source code

https://github.com/Cubentum/NoMoreSocials

### Your mod description

Removes ALL of RobTop's socials from the main menu screen, because he's been getting too much fame lately.

**Comment by Cvolton** [comment]
what benefit does this provide over cleaner menu DevCmb's mod, Gdtweaks, viper's and I lost track and all the other mods that provide this functionality

**Comment by Cvolton** [comment]
stale issue
