### ISSUE TITLE
Update GDDP Integration (beta.10 -> beta.13) (please it's been like 3 days)

### ISSUE THREAD

**Issue by Minemaker0430** [geode-sdk/indexer#1572]
### Your mod link

https://github.com/Minemaker0430/GDDPIntegration/releases/download/v1-beta.13/minemaker0430.gddp_integration.geode

### Your mod source code

https://github.com/Minemaker0430/GDDPIntegration

### Your mod description

* Prevented Crashes related to fetching pack data
* Added Pack Descriptions
* Difficulty Faces are now collected individually instead of being based on the current pack
	* Fixes incorrect difficulties
	* Fixes difficulties showing on Non-GDDP levels
	* Allows for Bonus Packs and Monthly Packs to show difficulties
	* Not all levels will have the individual difficulties at the start, please be patient with me
* Mod no longer accesses depreciated database values
* Progress evaluation should be significantly better
* Fixed a minor bug where the mod wouldn't detect you as outside of the GDDP menus

Edit:
* Fixed Visual Bug involving Levels in Bonus and Monthly Packs
* Non-GDDP Lists don't get visuals applied to them anymore

Edit 2:
* Fixed crash related to level lists
* New config option to replace Map Packs
	* Prioritizes Compact Menu Button over this option

Known Issues:
* Due to the way the Grandpa Demon compatibility works currently, when using Disable Effects...
	* Projected Stars particles may be hidden
	* Some effects may not be hidden on some levels

**Comment by dankmeme01** [comment]
!accept
