### ISSUE TITLE
Update Custom Gamemode Colors to v0.1.4

### ISSUE THREAD

**Issue by RoootTheFox** [geode-sdk/indexer#1573]
### Your mod link

https://github.com/RoootTheFox/custom-gamemode-colors/releases/download/v0.1.4/rooot.custom-gamemode-colors.geode

### Your mod source code

https://github.com/RoootTheFox/custom-gamemode-colors

### Your mod description

this update adds some info notification popups to avoid confusion with the ui and changes the internal format of color overrides
also removes some hooks that weren't necessary

[diff](https://github.com/RoootTheFox/custom-gamemode-colors/compare/v0.1.3...v0.1.4)

**Comment by RoootTheFox** [comment]
pls its been 2 days :>

**Comment by Weebifying** [comment]
i thought dank meme was gonna fix that pensive

**Comment by dankmeme01** [comment]
i'm a liar sorry

**Comment by dankmeme01** [comment]
!accept
