### ISSUE TITLE
Add user95401.extended-mod-info-popup v1.0.0

### ISSUE THREAD

**Issue by user95401** [geode-sdk/indexer#1580]
### Your mod link

https://github.com/user95401/extended-mod-info-popup/releases/download/v1.0.0/user95401.extended-mod-info-popup.geode

### Your mod source code

https://github.com/user95401/extended-mod-info-popup

### Your mod description

- downloads count label of last release
- button to open website page of mod
- last release size label
- last release update time label

![repoimg](https://repository-images.githubusercontent.com/774037359/dfb99c42-5fdb-458d-9b68-1bb87f6cc26b)

**Comment by OM3GA6400** [comment]
@user95401 shouldn't you close this one because you already published a new one?

**Comment by user95401** [comment]
no

**Comment by user95401** [comment]
oh wait

**Comment by user95401** [comment]
why its still here\

**Comment by OM3GA6400** [comment]
> why its still here\
> 

told u

**Comment by user95401** [comment]
i was sure i didnt create new one
