### ISSUE TITLE
Update MainMenuWallpaper (v1.0.3 -> v1.1.0)

### ISSUE THREAD

**Issue by iristraa** [geode-sdk/indexer#1588]
### Your mod link

https://github.com/iristraa/MainMenuWallpaper/releases/download/v1.1.0/iristraa.mainmenuwallpaper.geode

### Your mod source code

https://github.com/iristraa/MainMenuWallpaper

### Your mod description

adds wallpaper to menulayer

**Comment by Cvolton** [comment]
!accept
