### ISSUE TITLE
NoShake

### ISSUE THREAD

**Issue by MetaGG2** [geode-sdk/indexer#1591]
### Your mod link

https://github.com/MetaGG2/NoShake/releases/download/v1.0.0/avscs.noshake.geode

### Your mod source code

https://github.com/MetaGG2/NoShake

### Your mod description

Disables shake automatically for all levels similar to in-game "Enable LDM" setting

**Comment by Cvolton** [comment]
can you update the release to include a version with the proper about.md

**Comment by Cvolton** [comment]
!accept
