### ISSUE TITLE
Update NoMoreGrayFilter to v1.0.3

### ISSUE THREAD

**Issue by PetitFrapo** [geode-sdk/indexer#1604]
### Your mod link

https://github.com/PetitFrapo/NoMoreGrayFilter/releases/download/v1.0.3/petitfrapo.nomoregrayfilter.geode

### Your mod source code

https://github.com/PetitFrapo/NoMoreGrayFilter

### Your mod description

This update fixes compatibility issues and adds a couple of things.
* Added incompatibility with Goodbye Unnecessary Buttons in mod.json (why did i not think about this before).
* Fixed overlapping textures with the Super Expert mod.
* Added repository to the mod info.
* Added a changelog.

**Comment by Cvolton** [comment]
!accept
