### ISSUE TITLE
replace mod link just in case

### ISSUE THREAD

**Issue by coopeeo** [geode-sdk/indexer#1605]
### Your mod link

https://github.com/clicksounds/geode-clicksound/releases/download/Release-v1.8.0/beat.click-sound.geode

### Your mod source code

https://github.com/clicksounds/geode-clicksound/

### Your mod description

no new update :(

**Comment by coopeeo** [comment]
!accept

**Comment by RayDeeUx** [comment]
?

**Comment by coopeeo** [comment]
what?

**Comment by Cvolton** [comment]
!accept
