### ISSUE TITLE
Update NoMoreGrayFilter (1.0.3 -> 1.1.0) (1.0.3 doesn't work properly)

### ISSUE THREAD

**Issue by PetitFrapo** [geode-sdk/indexer#1609]
### Your mod link

https://github.com/PetitFrapo/NoMoreGrayFilter/releases/download/v1.1.0/petitfrapo.nomoregrayfilter.geode

### Your mod source code

https://github.com/PetitFrapo/NoMoreGrayFilter/

### Your mod description

Merged RayDeeUx's pull request which conveniently fixed my mod not even working.
I feel so bad for pushing it to the indexer...
anyways thank you very much RayDeeUx!!

**Comment by Cvolton** [comment]
!accept
