### ISSUE TITLE
Update Art importer (v1.0.0 -> v1.1.0)

### ISSUE THREAD

**Issue by CelestialGecko** [geode-sdk/indexer#1614]
### Your mod link

https://github.com/CelestialGecko/Art-importer/releases/download/v1.1.0/grian.art_importer.geode

### Your mod source code

https://github.com/CelestialGecko/Art-importer/tree/Android-port

### Your mod description

Just a update that makes the art importer compatible with android. I have also re written a bit of the code that should make it more efficient. I have also changed the logo to look a bit better.

**Comment by Cvolton** [comment]
art imposter

**Comment by Cvolton** [comment]
!accept
