### ISSUE TITLE
Add Underrated Non-Demons

### ISSUE THREAD

**Issue by acaruso-xx** [geode-sdk/indexer#1615]
### Your mod link

https://github.com/acaruso-xx/horn-geode/releases/download/v1.0.0/acaruso.horn.geode

### Your mod source code

https://github.com/acaruso-xx/horn-geode

### Your mod description

Underrated non-demons list integration.

## Features

- Levels with inconsistent difficulties now have demonic horns!
- Click on a level to learn more.

**Comment by dankmeme01** [comment]
!accept
