### ISSUE TITLE
Update AutoDeafen (1.0.0 -> 1.0.1)

### ISSUE THREAD

**Issue by Lynxdeer** [geode-sdk/indexer#1618]
### Your mod link

https://github.com/Lynxdeer/AutoDeafen/releases/download/1.0.1/lynxdeer.autodeafen.geode

### Your mod source code

https://github.com/Lynxdeer/AutoDeafen

### Your mod description

# v1.0.1

- Fixed autodeafen not working if you didn't have percentage turned on
- Added some color to about.md
- Improved the logo to look better :D

Old logo (made in paint 3d):
![logov1](https://github.com/Lynxdeer/AutoDeafen/assets/79340005/7af5a73e-2375-4621-894d-e4d44ffb5776)

New logo (made in google slides):
![logo](https://github.com/Lynxdeer/AutoDeafen/assets/79340005/7b586676-570a-408c-a592-37e4c08858d4)

**Comment by Cvolton** [comment]
!accept
