### ISSUE TITLE
update art importer v1.1.1

### ISSUE THREAD

**Issue by CelestialGecko** [geode-sdk/indexer#1623]
### Your mod link

https://github.com/CelestialGecko/Art-importer/releases/download/v1.1.1/grian.art_importer.geode

### Your mod source code

https://github.com/CelestialGecko/Art-importer/tree/v1.1.1

### Your mod description

now works on android and windows at the same time.
ples don't look at my previous issue :sk

**Comment by Cvolton** [comment]
scary repo organization

**Comment by Cvolton** [comment]
!accept
