### ISSUE TITLE
Update NoMoreGrayFilter (1.1.0 -> 1.1.1)

### ISSUE THREAD

**Issue by PetitFrapo** [geode-sdk/indexer#1630]
### Your mod link

https://github.com/PetitFrapo/NoMoreGrayFilter/releases/download/v1.1.1/petitfrapo.nomoregrayfilter.geode

### Your mod source code

https://github.com/PetitFrapo/NoMoreGrayFilter

### Your mod description

* Adjusted the scale of the buttons to work with any resolution.

Warning though, a crash will occur if the user happens to have no buttons in CreatorLayer, but if so why use the mod anyway?
If needed though I can implement a check for it, just let me know.

**Comment by Cvolton** [comment]
!accept
