### ISSUE TITLE
ruhax.indecreaseicons.geode 0.0.0-beta.5 

### ISSUE THREAD

**Issue by user95401** [geode-sdk/indexer#1641]
### Your mod link

https://github.com/user95401/InDeCreaseIcons/releases/download/v0.0.0-beta.5/ruhax.indecreaseicons.geode

### Your mod source code

https://github.com/user95401/InDeCreaseIcons

### Your mod description

fix the settings saving...

**Comment by user95401** [comment]
asd

**Comment by Cvolton** [comment]
!accept
