### ISSUE TITLE
Update Geometrize2GD

### ISSUE THREAD

**Issue by ShineUA** [geode-sdk/indexer#1644]
### Your mod link

https://github.com/ShineUA/geometrize2gd-mod-geode/releases/download/v1.2.0/shineua.geometrize2gd.geode

### Your mod source code

https://github.com/ShineUA/geometrize2gd-mod-geode/tree/v1.2.0/

**Comment by relativemodder** [comment]
!accept

**Comment by Cvolton** [comment]
thank you relative for your input

**Comment by Cvolton** [comment]
!accept
