### ISSUE TITLE
Update Dark Mode

### ISSUE THREAD

**Issue by zohnannor** [geode-sdk/indexer#1670]
### Your mod link

https://github.com/zohnannor/dark-mode-gd/releases/download/v0.1.2/zohnannor.dark_mode.geode

### Your mod source code

https://github.com/zohnannor/dark-mode-gd

### Your mod description

Changes hard-coded colors to a dark-mode-style theme with an option of customization. Inspired by Absolute's DarkMode Patcher for 2.1.

**Comment by zohnannor** [comment]
> Replacing an existing version `0.1.2`

It was totally intended!!...

**Comment by Cvolton** [comment]
!accept
