### ISSUE TITLE
Update NoOnlineLevelDelete

### ISSUE THREAD

**Issue by DoublefallingS** [geode-sdk/indexer#1675]
### Your mod link

https://github.com/DoublefallingS/NoOnlineLevelDelete/releases/download/v1.0.3/doublefallings.noonlineleveldelete.geode

### Your mod source code

https://github.com/DoublefallingS/NoOnlineLevelDelete

### Your mod description

Hides the button to delete your online levels to prevent accidents.

**Comment by Cvolton** [comment]
!accept
