### ISSUE TITLE
Add NinKaz's Editor Utils (v1.0.0)

### ISSUE THREAD

**Issue by flurrybun** [geode-sdk/indexer#1676]
### Your mod link

https://github.com/flurrybun/ninkaz-editor-utils/releases/download/v1.0.0/ninkaz.editor_utils.geode

### Your mod source code

https://github.com/flurrybun/ninkaz-editor-utils

### Your mod description

extra editor utilities to help make my life a little easier when creating. currently only has one but will be adding more! :]

**Comment by Cvolton** [comment]
the repository link in mod.json is invalid (goes to a 404 page), im assuming this isnt intended, otherwise looks good to me

**Comment by flurrybun** [comment]
fixed the broken link. thanks :)

**Comment by Cvolton** [comment]
!accept
