### ISSUE TITLE
Add PauseMenuLoop

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1678]
### Your mod link

https://github.com/RayDeeUx/PauseMenuLoop/releases/download/v1.0.0/raydeeux.pausemenuloop.geode

### Your mod source code

https://github.com/RayDeeUx/PauseMenuLoop

### Your mod description

# PauseMenuLoop

Allows you to choose a song to loop while the pause layer is active.

Select a menu loop of your choice from any supported audio file (`.mp3`, `.ogg`, `.wav`) on your device, or let the mod choose a random file from its config directory.

Special thanks to [Weebify](https://github.com/Weebifying) for lending his FMOD audio engine expertise again in getting audio to loop properly.

Note that if you have xiyxs's "Confirm Practice/Restart" mod loaded (or similar options enabled in your friendly neighborhood mod menu), your pause menu loop can end earlier than expected (when the confirmation menu shows up).

This issue comes from the lack of confirmation menus in vanilla Geometry Dash (forcing mod developers to write duct-taped solutions).

Marking an incompatibility from either mod solely because of this issue would accomplish nothing.

Original mod idea by [coakmuffer](https://youtube.com/channel/UCUDS3SX8eiO1CX4Cy_oe60Q).

This [Geode mod](https://geode-sdk.org) is licensed under LGPLv2.

Demo:

https://github.com/RayDeeUx/PauseMenuLoop/assets/51521765/3370434a-c3ab-445a-997a-740d7bec278b

**Comment by camila314** [comment]
this is cool and i like it but i also could not get it to work on mac, the menu works and everything but pausing just doesn't play the song. i tried both a wav and an ogg with no results.

**Comment by RayDeeUx** [comment]
> this is cool and i like it but i also could not get it to work on mac, the menu works and everything but pausing just doesn't play the song. i tried both a wav and an ogg with no results.

mp3?

**Comment by camila314** [comment]
!accept
