### ISSUE TITLE
1.1.0

### ISSUE THREAD

**Issue by Uproxide** [geode-sdk/indexer#1682]
### Your mod link

https://github.com/Uproxide/user-reviews/releases/download/1.1.0/uproxide.user_reviews.geode

### Your mod description

my mod does a thing, in a place, dont like it? try another place, at a different **T I M E**

**Comment by skyer1a** [comment]
when opening user profiles, the review button isnt padding correctly with other buttons that are there 
version: 1.1.0

**Comment by TheSillyDoggo** [comment]
I blame node ids

**Comment by skyer1a** [comment]
It seems like an easy fix
