### ISSUE TITLE
Add ErysEdits

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1687]
### Your mod link

https://github.com/RayDeeUx/ErysEdits/releases/download/v1.0.0/raydeeux.erysedits.geode

### Your mod source code

https://github.com/RayDeeUx/ErysEdits

### Your mod description

# ErysEdits
Several mods I would've made into smaller standalone mods when I was an ignorant Geode developer. (And I still probably am by several accounts, but who's keeping track? `/j`)

Not all features of ErysEdits are available across all platforms; check your settings for this mod after installing to verify.

## Features
- Various Info Label tweaks, including improved readibility, conditional displays, and debug text logging

![demoOne](https://github.com/geode-sdk/indexer/assets/51521765/4833977f-cfbd-4fa5-ba63-2d0cddc97cf9) ![demoOnePointFive](https://github.com/geode-sdk/indexer/assets/51521765/349f6a0f-88df-4607-8dfb-a17be33f2519)
![demoOnePointSeventyFive](https://github.com/geode-sdk/indexer/assets/51521765/df72137c-fc65-4b0a-b75d-b2e43de08b8f)
![demoOnePointEightHundredSeventyFive](https://github.com/geode-sdk/indexer/assets/51521765/703299b4-4d9e-49e4-9644-a2755066e194)

- Viewing level descriptions from level lists and daily/weekly levels (compatible with nearly every possible mod that edits the LevelCell, including Cvolton's BetterInfo + Compact Level Lists, cdc's Level Thumbnails, n's Level Pronouns, and dankmeme's Globed)

![demoTwo](https://github.com/geode-sdk/indexer/assets/51521765/d4053571-832f-422e-ad54-6b0bc4ff61e5)
![demoTwoPointFive](https://github.com/geode-sdk/indexer/assets/51521765/c00508d6-1c21-4883-8091-80c505a1d039)
![demoTwoPointSeventyFive](https://github.com/geode-sdk/indexer/assets/51521765/3ce6c297-68df-4a3d-b4bd-32566fce9cd4)

- Compact local levels list (with some code borrowed from Cvolton, compatible with LevelSize by hiimjustin000)

![demoThree](https://github.com/geode-sdk/indexer/assets/51521765/cac71b8b-b029-4dac-b930-832225526df4)

- Hide "Level Complete" visuals (except particles, use your local mod menu to hide those)

![demoFour](https://github.com/geode-sdk/indexer/assets/51521765/03c5c1ca-4f07-4a0e-8910-42468d59585a)

- Disabling the cube jump animation in platformer levels (hitbox trail for reference)

![demoFive](https://github.com/geode-sdk/indexer/assets/51521765/32b24f49-f50e-4091-9692-9111eb9c95c3)

- Compact view of user profile comments/posts

![demoSix](https://github.com/geode-sdk/indexer/assets/51521765/f5fa72b0-c9ab-47e9-b0e9-218885396a48)

- Various FLAlertLayers tweaks (including wider alerts, smaller, text, and scrollable text)

![demoSeven](https://github.com/geode-sdk/indexer/assets/51521765/7732a8b9-3c6c-4b04-ba84-cb1d07f3def4)

- Hidden progress bar and percentage on unverified local levels
- Force levels to stop music on death
- Force levels to play your death SFX on death (compatible with Adam_729's Random Death Sounds and ControlVanillaSFX, see mod settings for more details)
- Various keybinds to make navigating Geometry Dash feel a lot less repetive (Ctrl + S to save, Ctrl + R to refresh, Alt + Left/Right to navigate between layers with pages, Shift + Left/Right to go to the first or last page, etc)
- Requiring Shift key to enter shops and vaults (to avoid changing menu loop music)
- Disable Shake, Pulse, Area Tint, SFX, and Edit SFX triggers

## Special Thanks
- [acaruso](https://gdbrowser.com/u/25012294), for moral support + massive optimizations in codebase during development
- [Cvolton](https://gdbrowser.com/u/761691), for lending their C++ knowledge and allowing me to reuse/adapt some of their code from BetterEdit, Misc Bugfixes, and Compact Lists
- [Alphalaneous](https://gdbrowser.com/u/1139015) and [dankmeme](https://gdbrowser.com/u/9735891), for supplemental CMake/C++ expertise
- [SpaghettDev](https://gdbrowser.com/u/7670168) and [Prevter](https://gdbrowser.com/u/7696536), for finding memory address bindings that fully fleshed out some features (`0x305630` for `SecretLayer2::create()`;  `0x276180` and `0x276170`, for `LikeItemLayer::onDislike()` and `LikeItemLayer::onLike()` respectively)
- [Cooper](https://gdbrowser.com/u/21207551), for allowing me to reuse code for custom setting headers
- [CatXus](https://gdbrowser.com/u/14467409), for extensively testing this mod on Android, and for helping me sing "You Are a Pirate" from LazyTown ;)
- [sofabeddd](https://gdbrowser.com/u/7976112), for the occasional reality check

This [Geode mod](https://geode-sdk.org) is licensed under LGPLv2.

**Comment by Cvolton** [comment]
!accept
