### ISSUE TITLE
Auto delete

### ISSUE THREAD

**Issue by Bingy3** [geode-sdk/indexer#1691]
### Your mod link

https://github.com/Bingy3/gd-auto-delete/releases/download/v1.0.2/bingy3.auto_delete.geode

### Your mod source code

https://github.com/Bingy3/gd-auto-delete

### Your mod description

Auto deletes the level when exiting the level layer.

**Comment by RayDeeUx** [comment]
![image](https://github.com/geode-sdk/indexer/assets/51521765/feec429b-451d-4e84-80c1-8a4ffb595343)
would be nice if the button was a bit less intrusive (maybe smaller? or circular? your call)

**Comment by Bingy3** [comment]
I made it a bit smaller in the newer geode file, thanks.

**Comment by Cvolton** [comment]
!accept
