### ISSUE TITLE
update ingamelistmod

### ISSUE THREAD

**Issue by AdyaGMD** [geode-sdk/indexer#1699]
### Your mod link

https://github.com/AdyaGMD/IngameListMod/releases/download/release-v1.1.5/adyagd.ingamelistmod.geode

### Your mod source code

https://github.com/AdyaGMD/IngameListMod/

**Comment by Cvolton** [comment]
why is the repo a month behind

**Comment by AdyaGMD** [comment]
because recompiling it differently is what fixed it

**Comment by AdyaGMD** [comment]
u right, I forgot to push, its just a link change cuz aredl changed endpoints

**Comment by AdyaGMD** [comment]
fixed

**Comment by Cvolton** [comment]
!accept
