### ISSUE TITLE
Add ReplayLastCheckpoint

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1705]
### Your mod link

https://github.com/RayDeeUx/ReplayLastCheckpoint/releases/download/v1.0.0/raydeeux.replaylastcheckpoint.geode

### Your mod source code

https://github.com/RayDeeUx/ReplayLastCheckpoint/

### Your mod description

# ReplayLastCheckpoint

Recreation of the "Replay Last Checkpoint" module from MegaHack and GDMO, primarily intended for non-Windows platforms.

Also adds a spacebar keybind to restart from the last checkpoint (Windows and macOS only, will not work without MegaHack!).

Demos:

![demoOne](https://github.com/geode-sdk/indexer/assets/51521765/e7a1ba6c-bf80-4f64-bd44-14b93e116ab4)

![demoTwo](https://github.com/geode-sdk/indexer/assets/51521765/320fabbb-dbbe-4cdf-aee1-a5b8d70d6986)

![demoThree](https://github.com/geode-sdk/indexer/assets/51521765/901414ba-bc1d-42b7-b853-5e50a47f0fb6)

Mod idea suggested by [u/Aarxy](https://reddit.com/u/Aarxy/).

This [Geode mod](https://geode-sdk.org) is licensed under GPLv3, and is based off of GPLv3-licensed code by [SpaghettDev](https://github.com/SpaghettDev) and [maxnu](https://github.com/maxnut).

**Comment by camila314** [comment]
yay! hooray!

**Comment by camila314** [comment]
!accept
