### ISSUE TITLE
Add Progress Bar Color

### ISSUE THREAD

**Issue by Naxrin** [geode-sdk/indexer#1707]
### Your mod link

https://github.com/Naxrin/Progress-Bar-Color-Geode/releases/download/v1.0.0/naxrin.progress_bar_color.geode

### Your mod source code

https://github.com/Naxrin/Progress-Bar-Color-Geode

### Your mod description

Allows players to customize progress bar color
Apply to PauseLayer, LevelInfoLayer and LevelSelectLayer
Works for BetterPause

**Comment by camila314** [comment]
!accept
