### ISSUE TITLE
Add Transparent BG (more than qol)

### ISSUE THREAD

**Issue by Naxrin** [geode-sdk/indexer#1711]
### Your mod link

https://github.com/Naxrin/Transparent-Background/releases/download/v1.2.0/naxrin.transparent.geode

### Your mod source code

https://github.com/Naxrin/Transparent-Background

**Comment by camila314** [comment]
the description is gonna need to be toned down a few notches

**Comment by Naxrin** [comment]
ok will submit another one right now
