### ISSUE TITLE
Add Menu Shaders (?

### ISSUE THREAD

**Issue by Naxrin** [geode-sdk/indexer#1712]
### Your mod link

https://github.com/Naxrin/MenuShaders/releases/download/v1.2.0/cgytrus.menu-shaders.geode

### Your mod source code

https://github.com/Naxrin/MenuShaders

### This repo is forked from cgytrus'  version for GD2.11
I don't know why this mod isn't included in the mod index up to now, if forking is not allowed or something else, I'm not on purpose.

Replace the GD background with a shader,
now supports almost EVERY menu page in the Robtop's raw game program.

**Comment by Cvolton** [comment]
paging @cgytrus and @matcool for this one

**Comment by cgytrus** [comment]
rooot is *actually* working on porting the mod to 2.2. if you want to add additional features, properly pr them to upstream, preferably after it updates to 2.2.
