### ISSUE TITLE
Add Auto Nong v0.0.2

### ISSUE THREAD

**Issue by FlafyDev** [geode-sdk/indexer#1733]
### Your mod link

https://github.com/FlafyDev/auto-nong/releases/download/v0.0.2/flafy.autonong.geode

### Your mod source code

https://github.com/FlafyDev/auto-nong

### Your mod description

My mod automatically finds and downloads NONG songs when entering a level. You can learn more about it and check how it works in the `README.md`/`about.md` files.

v0.0.1 didn't have the correct gd version so i closed #1732

**Comment by FlafyDev** [comment]
demo:

https://github.com/geode-sdk/indexer/assets/44374434/95a3c3a7-7669-450b-9e85-09aaece975fc

**Comment by Fleeym** [comment]
!accept
