### ISSUE TITLE
Update entry for "Gay Wave Trail" to 1.0.9

### ISSUE THREAD

**Issue by TheBearodactyl** [geode-sdk/indexer#1738]
### Your mod link

https://github.com/TheBearodactyl/gay-wave-trail/releases/download/1.0.9/the_bearodactyl.gay-wave-trail.geode

### Your mod source code

https://github.com/TheBearodactyl/gay-wave-trail/

### Your mod description

pretty much just removed the incompatibility with qolmod since all that happens is that this mod just doesn't do anything when qolmod is enabled

**Comment by Cvolton** [comment]
!accept
