### ISSUE TITLE
Update ZCB Live

### ISSUE THREAD

**Issue by zeozeozeo** [geode-sdk/indexer#1743]
### Your mod link

https://github.com/zeozeozeo/zcblive-geode/releases/download/1.0.1/zeozeozeo.zcblive.geode

### Your mod source code

https://github.com/zeozeozeo/zcblive-geode

### Your mod description

Statically links with the Rust DLL now and contains lots of bugfixes

Note: this also has ClickpackDB, which makes connections to `raw.githubusercontent.com` and `github.com` to fetch the database with [ureq](https://github.com/algesten/ureq): https://github.com/zeozeozeo/clickpack-db/
![image](https://github.com/geode-sdk/indexer/assets/108888572/fa43aad3-36c0-480a-92c9-28dee7509603)

**Comment by Cvolton** [comment]
!accept
