### ISSUE TITLE
Update LoadingScreenTweaks

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1744]
### Your mod link

https://github.com/RayDeeUx/LoadingScreenTweaks/releases/download/v1.2.0/raydeeux.loadingscreentweaks.geode

### Your mod source code

https://github.com/RayDeeUx/LoadingScreenTweaks/

### Your mod description

- Allow users to customize the text area on the loading screen, much like DisturbingNewBests and WholesomeEndTexts.

Supports Windows, macOS, and Android.

**Comment by Cvolton** [comment]
!accept
