### ISSUE TITLE
true blue friend :)

### ISSUE THREAD

**Issue by Uproxide** [geode-sdk/indexer#1747]
### Your mod link

https://github.com/Uproxide/user-reviews/releases/download/1.3.0/uproxide.user_reviews.geode

### Your mod description

my mod makes it where chorus
It's okay
It's okay
It's okay
You're okay
You lived a million years
You'll make it through the day
Through the sun
And the rain
And the mud
And the clay
You lived a million years
Now look ahead to better days
verse
You're my rock
(Hello)
You're my everything
My pet rock
I'd do anything
To see you smile again
And i don't know when
It went wrong
(Woo)
I'm just glad we're still friends
chorus
It's okay
It's okay
It's okay
You're okay
You lived a million years
You'll make it through the day
Through the sun
And the rain
And the mud
And the clay
You lived a million years
Now look ahead to better days
verse
I feel lost (I feel lost)
Don't know what to do
Is it my fault
That you feel it too?
I'd end it all
If it wasn't true
You needed me
Like i need you
outro
(You rock)
(You rock)
(You rock)
(You rock)
(Let me show you something else, I love you)

**Comment by coopeeo** [comment]
wtf @Uproxide
