### ISSUE TITLE
Add Click Between Frames v1.0.0

### ISSUE THREAD

**Issue by theyareonit** [geode-sdk/indexer#1752]
### Your mod link

https://github.com/theyareonit/Click-Between-Frames/releases/download/v1.0.0/syzzi.click_between_frames.geode

### Your mod source code

https://github.com/theyareonit/Click-Between-Frames

### Your mod description

Allows the player to click in between visual frames, to greatly increase input precision.

**Comment by camila314** [comment]
!accept
