### ISSUE TITLE
No details / ULDM

### ISSUE THREAD

**Issue by hydragaryu** [geode-sdk/indexer#1756]
### Your mod link

https://github.com/hydragaryu/No-detail.git

### Your mod source code

https://github.com/hydragaryu/No-detail

### Your mod description

My mod removes **SOME** details of the game. Meant to go with Robtop's ULDM that he scrapped.
This will definitely have more updates for removing details.
     (The ULDM removes the game's texture file so it wont be there)

**Comment by RayDeeUx** [comment]
Greetings! Please refer to [this manual](https://docs.geode-sdk.org/getting-started/cpp-stuff) to begin making a Geode mod.

**Comment by TechStudent10** [comment]
my guy... that's not how modding works unfortunately
