### ISSUE TITLE
Add Transparent BG (more than QoL)

### ISSUE THREAD

**Issue by Naxrin** [geode-sdk/indexer#1773]
### Your mod link

https://github.com/Naxrin/Transparent-Background/releases/download/v1.3.0/naxrin.transparent.geode

### Your mod source code

https://github.com/Naxrin/Transparent-Background

### Your mod description

Commonly used transparent background mod
In addition, you can customize loading circle colors to fix your background theme.
Also you can switch to dark theme for gauntlet/daily/weekly levels.

**Comment by Naxrin** [comment]
made a tiny fix,
now adding a level to a list will not crash the game.

**Comment by Alphalaneous** [comment]
The code is a little weird, though it works, (also I see that sneaky code yoinked from my transparent lists mod commented out haha), but overall a worthwhile quality of life mod

**Comment by Alphalaneous** [comment]
!accept

**Comment by Naxrin** [comment]
> The code is a little weird, though it works, (also I see that sneaky code yoinked from my transparent lists mod commented out haha), but overall a worthwhile quality of life mod

Well the transparent list thing was planned firstly but I found those code failed to compile so I give in.
