### ISSUE TITLE
Update ErysEdits to v1.0.2

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1788]
### Your mod link

https://github.com/RayDeeUx/ErysEdits/releases/download/v1.0.2/raydeeux.erysedits.geode

### Your mod source code

https://github.com/RayDeeUx/ErysEdits

### Your mod description

- Rebuild the mod due to *someone* mangling up `FLAlertLayer` codegen
- Fix funky text scaling behavior in `FLAlertLayer`s with scrolling enabled by default

**Comment by Cvolton** [comment]
!accept
