### ISSUE TITLE
Update BreakingPlatforming

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1793]
### Your mod link

https://github.com/RayDeeUx/BreakingPlatforming/releases/download/v1.1.1/raydeeux.breakingplatforming.geode

### Your mod source code

https://github.com/RayDeeUx/BreakingPlatforming/

### Your mod description

- Apply a temporary (and toggleable) fix caused by accessing the garage before playing a level from the EditLevelLayer. ***This setting is off by default (so the crash will still happen) as toggling it on prevents you from entering the garage at all.***

Supports Windows and Android.

**Comment by Cvolton** [comment]
> Any crash reports caused by leaving this setting disabled after v1.1.1 of this mod was released will be ignored.

> "default": false

whatever i dont care since its at least a minor improvement from the current state but its comical that the mod crashes by default

**Comment by Cvolton** [comment]
!accept
