### ISSUE TITLE
Update FrickGlow

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1794]
### Your mod link

https://github.com/RayDeeUx/FrickGlow/releases/download/v1.3.3/raydeeux.fuckglow.geode

### Your mod source code

https://github.com/RayDeeUx/FrickGlow/

### Your mod description

- macOS support! Yay!
- Option 1 of "Hide Glow Deco" is no longer exclusive to Windows.

Supports Windows, macOS, and Android.

**Comment by RayDeeUx** [comment]
something went wrong oops

**Comment by Cvolton** [comment]
!accept
