### ISSUE TITLE
Update WholesomeEndTexts

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1796]
### Your mod link

https://github.com/RayDeeUx/WholesomeEndTexts/releases/download/v1.1.2/raydeeux.wholesomeendtexts.geode

### Your mod source code

https://github.com/RayDeeUx/WholesomeEndTexts/releases/download/v1.1.2/raydeeux.wholesomeendtexts.geode

### Your mod description

- Futureproofing the mod against unexpected `m_fields` behavior between Geode versions. Also raised the minimum Geode version requirement.

Supports Windows, macOS, and Android.

**Comment by Cvolton** [comment]
i think youre overthinking the m_fields changes, if anything, they behave more like expected in beta 24 and if you dont recompile, it just uses old behavior anyway

**Comment by Cvolton** [comment]
!accept
