### ISSUE TITLE
Add EvenMoreLevelTags (indirectly update MoreLevelTags)

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1798]
### Your mod link

https://github.com/RayDeeUx/More-Level-Tags/releases/download/v1.3.0/raydeeux_thesillydoggo.evenmoreleveltags.geode

### Your mod source code

https://github.com/RayDeeUx/more-level-tags

### Your mod description

- Bring back Android support.
- Refactor everything to avoid spawning phantom PlayLayers, and instead reading the level's decompressed string.
- Rebrand mod display name.
- Change mod ID, so that Globed's incompatibility list stays the same.
- Bump minimum Geode version and Geode Node ID requirements.
- Added more level tags (check the `about.md` for more info).
- License everything under the LGPLv2 license.

Supports Windows (tested), macOS (untested), and Android (tested).

**Comment by RayDeeUx** [comment]
per [this message](https://discord.com/channels/911701438269386882/911702535373475870/1228543422344855573), @TheSillyDoggo would like the original More Level Tags mod de-listed from the index before this gets accepted.

**Comment by OM3GA6400** [comment]
@RayDeeUx with the mod installed, i cant find a single level that receives an extra tag

**Comment by RayDeeUx** [comment]
@OM3GA6400 opinion rejected; make sure the mod is enabled and try again on ancient levels like windy landscape

**Comment by OM3GA6400** [comment]
@RayDeeUx i tried with blood bath and only had node ids and EveMoreLevelTags on

**Comment by OM3GA6400** [comment]
btw, that was on mobile, ill try again on pc rn

**Comment by OM3GA6400** [comment]
worked on pc but not on mobile

**Comment by RayDeeUx** [comment]
@OM3GA6400 skill differential detected
![Screenshot_2024-04-21-14-50-09-81_73932565f5d18c5d7f2b58eb6d5de17f](https://github.com/geode-sdk/indexer/assets/51521765/1f72d036-4875-4607-a414-f07fe398ea34)
![Screenshot_2024-04-21-14-49-56-46_73932565f5d18c5d7f2b58eb6d5de17f](https://github.com/geode-sdk/indexer/assets/51521765/d7e12789-b2ea-4bf4-91af-8d991b69813b)

**Comment by OM3GA6400** [comment]
odd

**Comment by RayDeeUx** [comment]
@OM3GA6400 please respond to my pings on discord

**Comment by OM3GA6400** [comment]
> @OM3GA6400 please respond to my pings on discord

you haven't sent me anything on discord wdym

**Comment by OM3GA6400** [comment]
also why did you block me

**Comment by RayDeeUx** [comment]
misclick

**Comment by OM3GA6400** [comment]
> misclick

i haven't been pinged at all, wdym

**Comment by OM3GA6400** [comment]
> misclick

are you trying to ping me or smt?

**Comment by RayDeeUx** [comment]
what is the `@OM3GA6400` in geode sdk discord then

**Comment by RayDeeUx** [comment]
is 1095091588813836289 not your discord user ID?

**Comment by OM3GA6400** [comment]
thats me, but i dont have any pings

**Comment by OM3GA6400** [comment]
what channel?

**Comment by Alphalaneous** [comment]
Positioning is a bit buggy, I hope you can resolve that, other than that, haven't had any issues

**Comment by Alphalaneous** [comment]
!accept
