### ISSUE TITLE
Update AutoDeafen (v1.0.1 -> v1.0.2)

### ISSUE THREAD

**Issue by Lynxdeer** [geode-sdk/indexer#1799]
### Your mod link

https://github.com/Lynxdeer/AutoDeafen/releases/download/v1.0.2/lynxdeer.autodeafen.geode

### Your mod source code

https://github.com/Lynxdeer/AutoDeafen

### Your mod description

# v1.0.2
- Added text telling you about changing the keybind first, because I have had six different people DM me and ask why the mod wasn't working because they didn't know that they had to have a discord "Toggle Deafen" keybind set to use the mod
- Made the default keybind empty rather than being a set keybind (nobody used that feature anyway)
- Fixed an issue where levels saving to the list on level exit sometimes wouldn't work
- Added a config option for enabling by default (which enables it globally)
- Added a config option for changing the default percentage in a new level
- Added Node IDs as a dependency (Should have been like this from the start)
- Made the .autodeafen file save on game exit rather than on level exit
- Removed the accidental controller support (it might confuse some users, since you can't set your discord toggle deafen keybind to it anyway)

**Comment by Cvolton** [comment]
!accept
