### ISSUE TITLE
Add Randomize Icon on Death

### ISSUE THREAD

**Issue by kittenchilly** [geode-sdk/indexer#1800]
### Your mod link

https://github.com/kittenchilly/Randomize-Icon-on-Death/releases/download/v1.0.2/kittenchilly.randomize_icon_on_death.geode

### Your mod source code

https://github.com/kittenchilly/Randomize-Icon-on-Death

### Your mod description

Simply makes it so your icon gets randomized everytime you die or restart a level.

**Comment by Cvolton** [comment]
as expected, most of the resulting icon combinations are absolutely ugly lol

**Comment by Cvolton** [comment]
!accept
