### ISSUE TITLE
Add Recolored-Music-Library-Songs

### ISSUE THREAD

**Issue by xiyxs** [geode-sdk/indexer#1807]
### Your mod link

https://github.com/xiyxs/Recolored-Music-Library-Songs/releases/download/v1.0.1/xiyxs.recolored_music_library_songs.geode

### Your mod source code

https://github.com/xiyxs/Recolored-Music-Library-Songs/

### Your mod description

Changes the color of songs from the Music Library in level search so they're different from songs that are on Newgrounds

**Comment by Cvolton** [comment]
!accept
