### ISSUE TITLE
Update WholesomeEndTexts

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1810]
### Your mod link

https://github.com/RayDeeUx/WholesomeEndTexts/releases/download/v1.1.3/raydeeux.wholesomeendtexts.geode

### Your mod source code

https://github.com/RayDeeUx/WholesomeEndTexts

### Your mod description

- Finally found a workaround past Cocos2D's tendency to ignore text alignment with multi-line quotes on Android. As such, quotes are no longer forcibly downscaled on Android. If your `bigFont.fnt` is somehow monospaced, that's on you.

Supports Windows, macOS, and Android.

**Comment by Cvolton** [comment]
!accept
