### ISSUE TITLE
Update AutoDeafen (v1.0.2 -> v1.0.3)

### ISSUE THREAD

**Issue by Lynxdeer** [geode-sdk/indexer#1819]
### Your mod link

https://github.com/Lynxdeer/AutoDeafen/releases/download/v1.0.3/lynxdeer.autodeafen.geode

### Your mod source code

https://github.com/Lynxdeer/AutoDeafen

### Your mod description

# v1.0.3
### This update was brought to you by RayDeeUx. Very cool!

**List of things he did:**

- Re-formatted the code to not be terrible and be more readable (sorry, I will do better at writing code when I make it open source)
- Changed the mod to use 2.0.0-beta23 (this will affect, as alk said, the 6 people that still use 2.0.0)
- Made level exiting much faster by making a setting to remove the massive foreach loop logging tool that I accidentally left in when debugging 1.0.2... Whoops!
- Changed the file saving event trigger to be GameManager instead of GManager (functionally equivalent) to remove TodoReturn usage
- Increased the minimum Node IDs version (didn't really need to since Node IDs is only used once and uses something that has existed since I think Node IDs 1.5.2, but doesn't matter `¯\_(ツ)_/¯`)
- Changed indents in `mod.json` to use tabs (Some places still have spaces though, I originally used spaces because I was used to yaml for editing plugin.yml. Whoops!) 
- Fixed the github actions workflow (thank you!!!)

**Comment by Cvolton** [comment]
!accept
