### ISSUE TITLE
Add Every Level is Mythic

### ISSUE THREAD

**Issue by GDColon** [geode-sdk/indexer#1836]
### Your mod link

https://github.com/GDColon/every-level-mythic/releases/download/v1.0.0/colon.allmythic.geode

### Your mod source code

https://github.com/GDColon/every-level-mythic

**Comment by Alphalaneous** [comment]
Unfortunately, mods like this are not allowed on the index, if it leaned more into the joke in some way, it could be accepted, but it needs to be built upon

**Comment by Alphalaneous** [comment]
!reject

**Comment by Alphalaneous** [comment]
I can see where you are coming from, it's definitely a grey area though, I am personally for mods like this, but also understand why they aren't allowed. I personally believe that multiple indexes should exist one day, and if that does happen, hopefully it could be added there
