### ISSUE TITLE
Add LevelEditorHack

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1837]
### Your mod link

https://github.com/RayDeeUx/LevelEditorHack/releases/download/v1.0.0/raydeeux.leveleditorhack.geode

### Your mod source code

https://github.com/RayDeeUx/LevelEditorHack

### Your mod description

# LevelEditorHack

Level Editor hack for macOS specifically, because Firee hasn't added one to Prism Menu yet and TheSillyDoggo's QOLMod crashes me on absolutely every button press.

Intended for personal use; feel free to install anyways.

This mod is licensed under LGPLv2 and is intentionally exclusive to macOS.

**Comment by kynex7510** [comment]
!accept
