### ISSUE TITLE
Add Statuses v1.0.0

### ISSUE THREAD

**Issue by cdc-sys** [geode-sdk/indexer#1845]
### Your mod link

https://github.com/cdc-sys/statuses-mod/releases/download/v1.0.0/cdc.statuses.geode

### Your mod source code

https://github.com/cdc-sys/statuses-mod/

### Your mod description

my mod adds live updating status icons to gd profiles

**Comment by cdc-sys** [comment]
tpecca!

**Comment by Uproxide** [comment]
tidel

**Comment by dankmeme01** [comment]
!accept
