### ISSUE TITLE
Doki Theme v1.0.0

### ISSUE THREAD

**Issue by LimeGradient** [geode-sdk/indexer#1846]
### Your mod link

https://github.com/LimeGradient/doki-theme-gd/releases/download/v1.0.0/limegradient.doki-theme-gd.geode

### Your mod source code

https://github.com/LimeGradient/doki-theme-gd

### Your mod description

My mod adds anime characters to the bottom right of your screen as a sticker. It also adds a faint one to the Editor UI in the background.

**Comment by LimeGradient** [comment]
I have just replaced the spicy images with normal images

**Comment by dankmeme01** [comment]
why does this target android 2.204. that does not exist

**Comment by RayDeeUx** [comment]
> why does this target android 2.204. that does not exist

@dankmeme01 working on a PR to fix that along with 38 other things, lemme cook

**Comment by LimeGradient** [comment]
> > why does this target android 2.204. that does not exist
> 
> @dankmeme01 working on a PR to fix that along with 38 other things, lemme cook

Im also fixing a bunch of stuff, and adding features requested by a playtester
