### ISSUE TITLE
Add Doki Theme 1.1.0

### ISSUE THREAD

**Issue by LimeGradient** [geode-sdk/indexer#1853]
### Your mod link

https://github.com/LimeGradient/doki-theme-gd/releases/download/v1.1.0/limegradient.doki-theme-gd.geode

### Your mod source code

https://github.com/LimeGradient/doki-theme-gd

### Your mod description

My mod adds anime characters to the bottom right of your screen. It also adds them in the background of the editor.

**Comment by TheBearodactyl** [comment]
LOL I USE THIS ADD-ON IN INTELLIJ

**Comment by LimeGradient** [comment]
> LOL I USE THIS ADD-ON IN INTELLIJ

I USE IT IN VSCODE LMFAO

**Comment by RayDeeUx** [comment]
*now* the mod's purpose makes a lot more sense

**Comment by TheBearodactyl** [comment]
> > LOL I USE THIS ADD-ON IN INTELLIJ
> 
> I USE IT IN VSCODE LMFAO

AWESOME

**Comment by LimeGradient** [comment]
> _now_ the mod's purpose makes a lot more sense

:)

**Comment by Alphalaneous** [comment]
!accept

**Comment by TheBearodactyl** [comment]
PEAK HAS BEEN ACCEPTED, LET'S GO

**Comment by LimeGradient** [comment]
LETS GOOOO
