### ISSUE TITLE
Update entry for "Gay Wave Trail"

### ISSUE THREAD

**Issue by TheBearodactyl** [geode-sdk/indexer#1871]
### Your mod link

https://github.com/TheBearodactyl/gay-wave-trail/releases/download/1.0.15/the_bearodactyl.gay-wave-trail.geode

### Your mod source code

https://gitlab.com/thebearodactyl/gay-wave-trail.git

### Your mod description

Updates geode version to latest version, and changes the repo link to the new location over on GitLab

**Comment by RayDeeUx** [comment]
config settings need a *massive* revamp

**Comment by TheBearodactyl** [comment]
> ![image](https://private-user-images.githubusercontent.com/51521765/326071301-745a6333-42b4-4db6-9035-dd5146fdc8c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNTYwMTgsIm5iZiI6MTcxNDE1NTcxOCwicGF0aCI6Ii81MTUyMTc2NS8zMjYwNzEzMDEtNzQ1YTYzMzMtNDJiNC00ZGI2LTkwMzUtZGQ1MTQ2ZmRjOGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDE4MjE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5OTM2MTNkZTUzMWZlMDk0NzFlNmY4OTBmNGZiODlmYjk0ZjI0NGY5ZjQxNjgxYzkxYmEwYmM4NzMzZTc5NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RVdgqDrh726SeQ4_4nzlwbc-MZjp_CxhGqoKNXXfOZ4) what in christ almighty is this

HOLY SHIT IT LOOKS DIFFERENT ON MINE

imma fix that now.

**Comment by RayDeeUx** [comment]
please also check your discord pings while you're at it; there's a few issues with your pauselayer button

**Comment by Cvolton** [comment]
why is the release and the associated tag with it assigned to a different repo...

**Comment by Cvolton** [comment]
!accept
