### ISSUE TITLE
Add FLIKK2GD

### ISSUE THREAD

**Issue by undefined06855** [geode-sdk/indexer#1873]
### Your mod link

https://github.com/undefined06855/FLIKK2GD/releases/download/v1.0.4/undefined0.flikk2gd.geode

### Your mod description

i think about 2 people will download this

**Comment by undefined06855** [comment]
yes it's starting on v1.0.4 just ignore it

**Comment by UniqueName12345** [comment]
Real quick - could you give a link to this "FLIKK" game?
