### ISSUE TITLE
Add Custom Icon Colors v1.1.1

### ISSUE THREAD

**Issue by emerald73** [geode-sdk/indexer#1898]
### Your mod link

https://github.com/emerald73/custom-icon-colors/releases/download/v1.1.1/gdemerald.custom_icon_colors.geode

### Your mod source code

https://github.com/emerald73/custom-icon-colors

### Your mod description

Allows you to set your P1 color, P2 color, and glow color to any color you want, including ones not possible in the base game.

**Comment by Alphalaneous** [comment]
!accept
