### ISSUE TITLE
update level thumbnails to v1.0.4

### ISSUE THREAD

**Issue by cdc-sys** [geode-sdk/indexer#1901]
### Your mod link

https://github.com/cdc-sys/level-thumbs-mod/releases/download/v1.0.4/cdc.level_thumbnails.geode

### Your mod source code

https://github.com/cdc-sys/level-thumbs-mod/

**Comment by cdc-sys** [comment]
ok

**Comment by cdc-sys** [comment]
fuck accident 💀

**Comment by Cvolton** [comment]
bro rejected his own mod...

**Comment by Cvolton** [comment]
!accept
