### ISSUE TITLE
user95401.mainlevelseditor v6.0.0-beta.7

### ISSUE THREAD

**Issue by user95401** [geode-sdk/indexer#1911]
### Your mod link

https://github.com/user95401/MainLevelsEditor/releases/download/v6.0.0-beta.7/user95401.mainlevelseditor.geode

### Your mod source code

https://github.com/user95401/MainLevelsEditor/tree/v6.0.0-beta.7

### Your mod description

pathetic android support and a bunch of other shit goes in this beta of v6

**Comment by kynex7510** [comment]
!accept
