### ISSUE TITLE
Update Level History -> v1.0.2

### ISSUE THREAD

**Issue by SergeyMC9730** [geode-sdk/indexer#1912]
### Your mod link

https://github.com/SergeyMC9730/levelhistory/releases/download/v1.0.2/dogotrigger.level_history.geode

### Your mod source code

https://github.com/SergeyMC9730/levelhistory

### Your mod description

Look through **deleted and outdated levels** using **GDHistory** or other sources!

**Comment by Cvolton** [comment]
!accept
