### ISSUE TITLE
Update entry for "Gay Wave Trail"

### ISSUE THREAD

**Issue by TheBearodactyl** [geode-sdk/indexer#1915]
### Your mod link

https://github.com/TheBearodactyl/gay-wave-trail/releases/download/1.0.16/the_bearodactyl.gay-wave-trail.geode

### Your mod source code

https://gitlab.com/TheBearodactyl/gay-wave-trail.git

### Your mod description

just some small optimizations and new `hsv_to_rgb` logic using ternaries instead of a switch statement (for reduced code density)

**Comment by Alphalaneous** [comment]
!accept
