### ISSUE TITLE
Add Pickups Across Sessions

### ISSUE THREAD

**Issue by iAndyHD3** [geode-sdk/indexer#1916]
### Your mod link

https://github.com/iAndyHD3/pickups-across-sessions/releases/download/v1.0.0/iandyhd3.persistent_pickup_ids.geode

### Your mod source code

https://github.com/iAndyHD3/pickups-across-sessions

### Your mod description

This mod allows you to save item ids across sessions, you can save your pickups ids and use them in any levels you publish from your account. More details in the repo README

**Comment by Alphalaneous** [comment]
!accept
