### ISSUE TITLE
QuickAccess

### ISSUE THREAD

**Issue by KorshunDev** [geode-sdk/indexer#1920]
### Your mod link

https://github.com/KorshunDev/QuickAccess/releases/download/1.0.1/korshun.quickaccess.geode

**Comment by TheSillyDoggo** [comment]
Why beta 16?

**Comment by KorshunDev** [comment]
I tried making mods when the latest version was beta-16

**Comment by Alphalaneous** [comment]
In the future I suggest targeting the latest version of Geode

**Comment by Alphalaneous** [comment]
!accept
