### ISSUE TITLE
Add UltraHack

### ISSUE THREAD

**Issue by W20MC** [geode-sdk/indexer#1922]
### Your mod link

https://github.com/W20MC/UltraHack/releases/download/1.0/windows_20.ultrahack.geode

### Your mod source code

https://github.com/W20MC/UltraHack/

### Your mod description

My mod adds a menu with noclip, practice music sync and noclip. You invoke it with L

**Comment by Alphalaneous** [comment]
Currently, we are going to have to deny adding this mod. It does not have enough content, and what it does have is provided by multiple other mods as well. In the future, this can be reconsidered when there is more added onto it.

**Comment by W20MC** [comment]
> Currently, we are going to have to deny adding this mod. It does not have enough content, and what it does have is provided by multiple other mods as well. In the future, this can be reconsidered when there is more added onto it.

Thanks for the feedback.
