### ISSUE TITLE
Update LikeBaitExterminator

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1923]
### Your mod link

https://github.com/RayDeeUx/LikeBaitExterminator/releases/download/v1.2.0/raydeeux.likebaitexterminator.geode

### Your mod source code

https://github.com/RayDeeUx/LikeBaitExterminator

### Your mod description

- Fix a rare crash when combined with Emojis in Comments (with help from Alphalaneous and Prevter).
- Updated the regex a smidge.

Supports Windows, macOS, and Android.

**Comment by Alphalaneous** [comment]
!accept
