### ISSUE TITLE
Update BreakingPlatforming

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#1924]
### Your mod link

https://github.com/RayDeeUx/BreakingPlatforming/releases/download/v1.2.0/raydeeux.breakingplatforming.geode

### Your mod source code

https://github.com/RayDeeUx/BreakingPlatforming

### Your mod description

- Add macOS support.
- Added a new toggle to disable the platformer squish jumping animation.
- Fix a bug where speed portals could not be marked as multiactivated.

Supports Windows, macOS, and Android.

**Comment by Alphalaneous** [comment]
!accept
