### ISSUE TITLE
Update Level History v1.0.3

### ISSUE THREAD

**Issue by SergeyMC9730** [geode-sdk/indexer#1929]
### Your mod link

https://github.com/SergeyMC9730/levelhistory/releases/download/v1.0.3/dogotrigger.level_history.geode

### Your mod source code

https://github.com/SergeyMC9730/levelhistory

### Your mod description

# Level History

Look through **deleted and outdated levels** using **GDHistory** or other sources!

## As of `v1.0.3` GDHistory is supported only.

# How To Use

- Go to the Online menu
- Find **folder icon** in the up right corner
- Select **level provider** you want to use for this session
- **GG**

**Comment by Alphalaneous** [comment]
!accept
