### ISSUE TITLE
Update Random Death Sounds v1.0.0 -> v1.1.0

### ISSUE THREAD

**Issue by Adam7290** [geode-sdk/indexer#1946]
### Your mod link

https://github.com/Adam7290/randdeathsounds/releases/download/v1.1.0/adam_729.randdeathsounds.geode

### Your mod source code

https://github.com/Adam7290/randdeathsounds/tree/v1.1.0

### Your mod description

- Android support!
- Moved sounds folder to config dir
- Death sounds are cached and preloaded when loading a level
- Now using std::mt19937 rng instead of rand()
- Killing icons in the menu now plays random death sounds!
- Added "Force Death SFX" option
- Added "Stop Death SFX on Respawn" option (enabled = default gd behaviour)

**Comment by RayDeeUx** [comment]
LET'S GOOOOOOOOOOOOO

**Comment by Cvolton** [comment]
!accept
