### ISSUE TITLE
Add Spinny-Menu

### ISSUE THREAD

**Issue by SupKittyMeow** [geode-sdk/indexer#1948]
### Your mod link

https://github.com/SupKittyMeow/Spinny-Menu/blob/main/build/supkittymeow.spinnyMenu.geode

### Your mod source code

https://github.com/SupKittyMeow/Spinny-Menu

### Your mod description

Adds a button that makes it so when you click it, the entire screen rotates by 10 degrees.

It's really dumb, but it was my first project in c++.

**Comment by YellowCat98** [comment]
invalid geode file?

**Comment by SupKittyMeow** [comment]
Yeah, I accidentally entered the wrong link. I created a new issue that is open.
