### ISSUE TITLE
Add SpaceUK Mode

### ISSUE THREAD

**Issue by Tiago1257** [geode-sdk/indexer#1964]
### Your mod link

https://github.com/Tiago1257/spaceukmode/releases/download/v1.0.1/1257plays.spaceuk_mode.geode

### Your mod source code

https://github.com/Tiago1257/spaceukmode/

### Your mod description

my mod adds funny spaceuk watermark but this time it works on other platforms

**Comment by RayDeeUx** [comment]
got a crashlog on windows of all places oof: https://discord.com/channels/911701438269386882/911702535373475870/1236385725205708940

**Comment by RayDeeUx** [comment]
nvm, manually resolved

**Comment by Tiago1257** [comment]
### Your mod link

https://github.com/Tiago1257/spaceukmode/releases/download/v1.0.1/1257plays.spaceuk_mode.geode
### Your mod source code

https://github.com/Tiago1257/spaceukmode/
### Your mod description

my mod adds funny spaceuk watermark but this time it works on other platforms - also fixed practice mode crashes
(does the action catch this)
