### ISSUE TITLE
Update Garage Utilities to v1.0.4

### ISSUE THREAD

**Issue by nytelytee** [geode-sdk/indexer#1984]
### Your mod link

https://github.com/nytelytee/geode-garage-utilities/releases/download/v1.0.4/nytelyte.garage_utilities.geode

### Your mod source code

https://github.com/nytelytee/geode-garage-utilities

#### v1.0.4
- added support for colors in the item info popup on profile pages
- reordered gauntlets for strict category to match newly added ones

#### v1.0.3

- added support for item info popup arrows on profile pages, for people with Better Unlock Info
- changed names of elements from 'Unlock Popup' to 'Item Info Popup' in settings and about pages
- move arrows in item info popups slightly up, to make them centered on the popup

**Comment by Cvolton** [comment]
!accept
