### ISSUE TITLE
Update Ultra LDM to 1.0.1

### ISSUE THREAD

**Issue by StatusZer0** [geode-sdk/indexer#1988]
### Your mod link

https://github.com/StatusZer0/UltraLDM/releases/download/ReleasePatch/statuszer0.ultra_ldm.geode

### Your mod source code

https://github.com/StatusZer0/UltraLDM

### Your mod description

Added something to set all object opacity to maximum, disregarding alpha triggers (I think)

**Comment by Cvolton** [comment]
!accept
