### ISSUE TITLE
Add Nuzlocke v1.0.3

### ISSUE THREAD

**Issue by SergeyMC9730** [geode-sdk/indexer#1991]
### Your mod link

https://github.com/SergeyMC9730/nuzlocke/releases/download/v1.0.3/dogotrigger.nuzlocke.geode

### Your mod source code

https://github.com/SergeyMC9730/nuzlocke

### Your mod description

<cp>**Nuzlocke Challenge in Geometry Dash.**</c>

There's two simple rules:
- If you <cr>die</c>, your currently selected cube icon <cy>becomes unusable.</c>
- If no icons remaining <cr>you lose</c>.

**Comment by kynex7510** [comment]
!accept
