### ISSUE TITLE
Update DisturbingNewBests

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#2000]
### Your mod link

https://github.com/RayDeeUx/DisturbingNewBests/releases/download/v1.1.2/raydeeux.disturbingnewbests.geode

### Your mod source code

https://github.com/RayDeeUx/DisturbingNewBests/

## v1.1.2
- Replaced a few quotes in the default set in light of recent events.
- Replaced a few quotes in the Brandon Rogers set, because some of them were incredibly unfunny.
- A small optimization.
- Increase minimum Geode version requirement to 2.0.0-beta26.
## v1.1.1
- A single line swap to properly enforce text alignment.

Supports Windows, macOS, and Android.

**Comment by kynex7510** [comment]
!accept
