### ISSUE TITLE
death tracker 2.0.0-beta 4

### ISSUE THREAD

**Issue by abb2k** [geode-sdk/indexer#2010]
### Your mod link

https://github.com/eloh-mrow/death-tracker/releases/download/v2.0.0-beta.4/elohmrow.death_tracker.geode

### Your mod source code

https://github.com/eloh-mrow/death-tracker

### Your mod description

- added the new UI and removed the old one
- added linking levels
- added graphs
- added multi session tracking
- added run tracking
- added manual run management
- added layout customization
- a lot of fixes
- completions are now tracked as 100% instead of 0-100 runs

**Comment by abb2k** [comment]
:)

**Comment by abb2k** [comment]
2 days ago :(

**Comment by Alphalaneous** [comment]
!accept
