### ISSUE TITLE
Add Click on Steps

### ISSUE THREAD

**Issue by qimiko** [geode-sdk/indexer#2011]
### Your mod link

https://github.com/qimiko/click-on-steps/releases/download/v1.0.0/zmx.cbf-lite.geode

### Your mod source code

https://github.com/qimiko/click-on-steps

### Your mod description

mod that increases input precision to 240tps on non 240fps gameplay. like cbf, but it stops just before the whole modifying physics part

**Comment by matcool** [comment]
!accept
