### ISSUE TITLE
update entry for "gay wave trail"

### ISSUE THREAD

**Issue by TheBearodactyl** [geode-sdk/indexer#2017]
### Your mod link

https://github.com/TheBearodactyl/gay-wave-trail/releases/download/1.0.17/the_bearodactyl.gay-wave-trail.geode

### Your mod source code

https://gitlab.com/thebearodactyl/gay-wave-trail.git

### Your mod description

new version introduces customizable wave trail colors using gradients :D
it currently only supports 4 colors

**Comment by TheBearodactyl** [comment]
showcase: 
https://youtu.be/uW0T6lOwMK0?si=J4DVzvRfRAb2p9nf

**Comment by Alphalaneous** [comment]
!accept
