### ISSUE TITLE
Update GDDP Integration to v1.0.0-beta.20

### ISSUE THREAD

**Issue by Minemaker0430** [geode-sdk/indexer#2025]
### Your mod link

https://github.com/Minemaker0430/GDDPIntegration/releases/download/v1-beta.20/minemaker0430.gddp_integration.geode

### Your mod source code

https://github.com/Minemaker0430/GDDPIntegration/

### Your mod description

* Added skillset badges
* Added failsafes for missing textures
* Fixed coin icons in LevelBrowserLayer causing visual bugs
	* This also sets an ID for the Grandpa Demon face, let me know if this conflicts with another mod
* Added an option to enable GDDP Ratings for all difficulties **\([Made by wint0r](https://github.com/wint0r), tweaked by Me\)**
	* Uses IDS, NLW, and Pointercrate API
* Added some more options
* Fixed Disable Grandpa Demon Effects (I think)

**Comment by Alphalaneous** [comment]
!accept
