### ISSUE TITLE
add ocd icons

### ISSUE THREAD

**Issue by TheBearodactyl** [geode-sdk/indexer#2037]
### Your mod link

https://github.com/TheBearodactyl/ocd-icons/releases/download/1.0.0/the_bearodactyl.ocd-icons.geode

### Your mod source code

https://github.com/TheBearodactyl/ocd-icons.git

### Your mod description

it keeps the icons upside-up

**Comment by Alphalaneous** [comment]
Please update your about.md

**Comment by kynex7510** [comment]
!accept
