### ISSUE TITLE
Add Daily & Weekly Indicators (v1.0.0)

### ISSUE THREAD

**Issue by xiyxs** [geode-sdk/indexer#2044]
### Your mod link

https://github.com/xiyxs/Daily-and-Weekly-Levels/releases/download/v1.0.0/xiyxs.daily_and_weekly_levels.geode

### Your mod source code

https://github.com/xiyxs/Daily-and-Weekly-Levels

### Your mod description

Adds an indicator next to levels that have been daily or weekly.

**Comment by Alphalaneous** [comment]
!accept
