### ISSUE TITLE
Update NoGrounds (v1.0 -> v1.1)

### ISSUE THREAD

**Issue by rileythesillyone** [geode-sdk/indexer#2050]
### Your mod link

https://github.com/rileythesillyone/nogrounds/releases/download/update/riley.nogrounds.geode

### Your mod source code

https://github.com/rileythesillyone/nogrounds

### Your mod description

it removes the newgrounds button from the bottom menu, this update optimizes it and ported it to android and mac

**Comment by Alphalaneous** [comment]
!accept
