### ISSUE TITLE
Add "XXLify"

### ISSUE THREAD

**Issue by Ziegenhainy** [geode-sdk/indexer#2060]
### Your mod link

https://github.com/Ziegenhainy/XXLify/releases/download/v1.0.1/ziegenhainy.xxlify.geode

### Your mod source code

https://github.com/Ziegenhainy/XXLify

### Your mod description

Levels longer than 4 minutes get appropriate XXL tags, or above 8 minutes XXXL tags and so on. :)
Here is an example with Eon:
![image](https://github.com/geode-sdk/indexer/assets/49167717/c9d46d0c-a669-4e3c-bce1-631e4f6e2b66)

**Comment by Ziegenhainy** [comment]
>     * Actual platforms: `['windows']`

**Comment by Alphalaneous** [comment]
The reason it says "Actual platforms: `['windows']`" is due to the fact that it was never built for other platforms, looking at the .geode file, there is only a dll in there.

**Comment by Ziegenhainy** [comment]
> To add, looking at your actions, the latest builds are fine, so I suggest updating the release with one of those.

hmm. I used Cmake in VScode to make the builds, but that apparently didnt add the crossplat. Still new to all this stuff. Thanks for clarification!

**Comment by Alphalaneous** [comment]
> > To add, looking at your actions, the latest builds are fine, so I suggest updating the release with one of those.
> 
> hmm. I used Cmake in VScode to make the builds, but that apparently didnt add the crossplat. Still new to all this stuff. Thanks for clarification!

Yeah the action is what builds cross platform, it doesn't automatically build for all platforms

**Comment by Alphalaneous** [comment]
!accept
