### ISSUE TITLE
Update Chroma Icons

### ISSUE THREAD

**Issue by Naxrin** [geode-sdk/indexer#2070]
### Your mod link

https://github.com/Naxrin/Chroma-Icons/releases/download/v1.1.1/naxrin.rgb_icons.geode

### Your mod source code

https://github.com/Naxrin/Chroma-Icons

### Your mod description

Nothing different but added a title image to about.md

**Comment by Alphalaneous** [comment]
Btw, you don't need to use CCARRAY_FOREACH, there is a utility that turns a CCArray into an iterator, `CCArrayExt<CCSprite*>(glow_sprites->getChildren())` for example

I would also recommend some way to soft toggle in the UI so you can enable/disable all effects without reverting all the settings

**Comment by Alphalaneous** [comment]
!accept

**Comment by Naxrin** [comment]
> Btw, you don't need to use CCARRAY_FOREACH, there is a utility that turns a CCArray into an iterator, `CCArrayExt<CCSprite*>(glow_sprites->getChildren())` for example
> 
> I would also recommend some way to soft toggle in the UI so you can enable/disable all effects without reverting all the settings

OK will prettify the iterator thing later
I set the ultimate switch in options menu
