### ISSUE TITLE
Update XXLify to 1.1.2

### ISSUE THREAD

**Issue by Ziegenhainy** [geode-sdk/indexer#2079]
### Your mod link

https://github.com/Ziegenhainy/XXLify/releases/download/v1.1.2/ziegenhainy.xxlify.geode

### Your mod source code

https://github.com/Ziegenhainy/XXLify

### Your mod description

XXLify makes levels longer than 4 minutes show XXL tags or longer, this update makes the mod work on levels released before 2.2.

**Comment by Cvolton** [comment]
this retain call https://github.com/Ziegenhainy/XXLify/blob/main/src/main.cpp#L21 should be above the std::thread, retaining/releasing in any other thread than main has the potential for crashing if you dont know what youre doing

**Comment by Ziegenhainy** [comment]
> this retain call https://github.com/Ziegenhainy/XXLify/blob/main/src/main.cpp#L21 should be above the std::thread, retaining/releasing in any other thread than main has the potential for crashing if you dont know what youre doing

I hate microsoft specifically and I am definitely not in the wrong. Fixed in 1.1.2, link updated

**Comment by Cvolton** [comment]
thats a cocos issue, not a microsoft issue

**Comment by Cvolton** [comment]
!accept
