### ISSUE TITLE
add "next free editor layer"

### ISSUE THREAD

**Issue by TheBearodactyl** [geode-sdk/indexer#2085]
### Your mod link

https://github.com/TheBearodactyl/next-free-layer-button/releases/download/1.0.2/the_bearodactyl.next-free-layer.geode

### Your mod source code

https://github.com/TheBearodactyl/next-free-layer-button.git

### Your mod description

my mod adds a button to `EditorUI` that, when pressed, sets the current editor layer to the next one without objects

edit for version bump

**Comment by Prevter** [comment]
!accept
