### ISSUE TITLE
Add Demons In Between (1.0.1)

### ISSUE THREAD

**Issue by hiimjustin000** [geode-sdk/indexer#2101]
### Your mod link

https://github.com/hiimjustin000/DemonsInBetween/releases/download/v1.0.1/hiimjustin000.demons_in_between.geode

### Your mod source code

https://github.com/hiimjustin000/DemonsInBetween

### Your mod description

A mod that adds additional demon difficulties in between existing ones.

**Comment by Prevter** [comment]
!accept
