### ISSUE TITLE
Add Keystrokes

### ISSUE THREAD

**Issue by blueblock6** [geode-sdk/indexer#2109]
### Your mod link

https://github.com/blueblock6/Keystrokes/releases/download/1.0.2/blueblock6.keystrokes.geode

### Your mod source code

https://github.com/blueblock6/Keystrokes

### Your mod description

Adds a keystrokes overlay in the corner of the screen while playing

**Comment by Prevter** [comment]
I'm getting crashes when entering 2-player mode platformer levels with dual mode enabled.
It only seems to trigger the crash when entering it from EditLevelLayer, but works for online levels.
Try copying this level and testing for yourself: 105742045

**Comment by Prevter** [comment]
!accept
