### ISSUE TITLE
Update Garage Utilities to v1.0.5

### ISSUE THREAD

**Issue by nytelytee** [geode-sdk/indexer#2111]
### Your mod link

https://github.com/nytelytee/geode-garage-utilities/releases/download/v1.0.5/nytelyte.garage_utilities.geode

### Your mod source code

https://github.com/nytelytee/geode-garage-utilities

### Your mod description

- fix crashes on Android
- better compatibility with Better Unlock Info
  - don't remove diamond shards, hide them instead, BUI tries to modify the label, causing a crash
  - refresh the filters if something is purchased inside the garage using BUI's purchase popups

Crashes on Android apparently happened due to activeIconForType hooking being broken on Android, which I used to make the game place the selected icon cursor in the correct position. I have removed the hook and now place the cursor in the correct position manually.

**Comment by Prevter** [comment]
!accept
