### ISSUE TITLE
Menu Modifier

### ISSUE THREAD

**Issue by Xytriza** [geode-sdk/indexer#2113]
### Your mod link

https://github.com/Xytriza/menu-modifier/releases/download/v1.0.0/xytriza.menu_modifier.geode

### Your mod source code

https://github.com/Xytriza/menu-modifier

### Your mod description

- Remove the RobTop Logo (setting)
- Remove the RobTop Socials (setting)
- Remove the More Games Button (setting)
- Remove useless buttons from the Creator Layer (setting)
- Move the Profile Button or Daily Chest button (setting)

**Comment by HJfod** [comment]
!accept
