### ISSUE TITLE
Update Demons In Between (1.0.1 -> 1.0.2)

### ISSUE THREAD

**Issue by hiimjustin000** [geode-sdk/indexer#2119]
### Your mod link

https://github.com/hiimjustin000/DemonsInBetween/releases/download/v1.0.2/hiimjustin000.demons_in_between.geode

### Your mod source code

https://github.com/hiimjustin000/DemonsInBetween

### Your mod description

- Fixed incompatibility with the mod "GDDP Integration" by Minemaker0430

**Comment by Prevter** [comment]
!accept
