### ISSUE TITLE
Update XXLify to 1.2.0

### ISSUE THREAD

**Issue by Ziegenhainy** [geode-sdk/indexer#2121]
### Your mod link

https://github.com/Ziegenhainy/XXLify/releases/download/v1.2.0/ziegenhainy.xxlify.geode

### Your mod source code

https://github.com/Ziegenhainy/XXLify/

### Your mod description

I added a variety of features to this mod, and all of them can be expressed in this one image.
![image](https://github.com/geode-sdk/indexer/assets/49167717/1cf7bc6f-1207-45fe-a791-1ceaee18b4d0)

**Comment by ninXout** [comment]
!accept
