### ISSUE TITLE
Update GDDP Integration to beta.21

### ISSUE THREAD

**Issue by Minemaker0430** [geode-sdk/indexer#2134]
### Your mod link

https://github.com/Minemaker0430/GDDPIntegration/releases/download/v1-beta.21/minemaker0430.gddp_integration.geode

### Your mod source code

https://github.com/Minemaker0430/GDDPIntegration/

### Your mod description

* Added Progress Bars
	* Progress Bar colors in the Lists now match the ones in the menus
* Added as many Node IDs to the GDDP Stuff as I could
* Patched up Beta 20 stuff
	* Insane/Extreme Demon ratings now rely on GDDL Tiers as opposed to 3 seperate APIs
* Fixed Main Menu related issues (I think)

**Comment by Prevter** [comment]
!accept
