### ISSUE TITLE
Update Drunk Mode

### ISSUE THREAD

**Issue by StatusZer0** [geode-sdk/indexer#2164]
### Your mod link

https://github.com/StatusZer0/DrunkMode/releases/download/1.1.0/statuszer0.drunk_mode.geode

### Your mod source code

https://github.com/StatusZer0/DrunkMode

### Your mod description

Changes game speed between 0.85 and 1.15 rapidly

**Comment by YellowCat98** [comment]
do we tell them

**Comment by SpaghettDev** [comment]
you dont submit mods here anymore, use the cli

**Comment by StatusZer0** [comment]
I haven't caught up yet lol

**Comment by StatusZer0** [comment]
sorry
