### ISSUE TITLE
Update XXLify to 1.2.1-beta.1

### ISSUE THREAD

**Issue by Ziegenhainy** [geode-sdk/indexer#2170]
### Your mod link

https://github.com/Ziegenhainy/XXLify/releases/download/v1.2.1-beta.1/ziegenhainy.xxlify.geode

### Your mod source code

https://github.com/Ziegenhainy/XXLify/tree/beta

### Your mod description

Support for the new versions, but not mac sorry

**Comment by hiimjustin000** [comment]
Who's gon tell them

**Comment by Ziegenhainy** [comment]
> Who's gon tell them

idk

**Comment by Ziegenhainy** [comment]
tf is it lol
