### ISSUE TITLE
Add an entry

### ISSUE THREAD

**Issue by Explodingbill** [geode-sdk/indexer#241]
### Your mod link

https://github.com/Explodingbill/Pause-Menu-Mods/releases/v1.0/explodingbill.pausemods.geode

**Comment by Explodingbill** [comment]
Source code in the releases source.zip

**Comment by cgytrus** [comment]
please use git properly.

**Comment by Fleeym** [comment]
me when sources.zip 309MB

**Comment by Explodingbill** [comment]
> please use git properly.

Too big to upload

**Comment by cgytrus** [comment]
its not when you use git properly. you uploaded the entire 1gb build folder bro wtf

**Comment by cgytrus** [comment]
also the release link isnt even correct

**Comment by cgytrus** [comment]
> its not when you use git properly. you uploaded the entire 1gb build folder bro wtf

its even in the gitignore all you have to do is initialize a git repo and push it to remote,
refer to these basic git tutorials for more information.

https://docs.github.com/en/get-started/quickstart/set-up-git
https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository

**Comment by Explodingbill** [comment]
I am not a good programmer, I make games and mods for fun when I have free time. I've never used got and was just doing what the readme said. Upload source and upload .geode
