### ISSUE TITLE
Add an entry

### ISSUE THREAD

**Issue by TheSillyDoggo** [geode-sdk/indexer#333]
### Your mod link

https://github.com/TheSillyDoggo/GD-Discord-Webhook-Integration/releases/download/v1.0.0/TheSillyDoggo.DiscordWebhook.geode

**Comment by TheSillyDoggo** [comment]
source code in the repo https://github.com/TheSillyDoggo/GD-Discord-Webhook-Integration/

**Comment by matcool** [comment]
!accept
