### ISSUE TITLE
Update BetterMenuMod

### ISSUE THREAD

**Issue by MuhXd** [geode-sdk/indexer#387]
### Your mod link

https://github.com/MuhXd/BetterMenuMod/releases/tag/BetterMenu-V1.04-beta.10

**Comment by MegaFaresX** [comment]
I think it needs a link like this https://github.com/MuhXd/BetterMenuMod/releases/download/BetterMenu-V1.04-beta.10/muhammadgames.bettermenu.geode

**Comment by MuhXd** [comment]
oh i'm dumb

**Comment by MuhXd** [comment]
thanks
