### ISSUE TITLE
Add Demons In Garage 2.2 (v1.1.0)

### ISSUE THREAD

**Issue by Capeling** [geode-sdk/indexer#425]
### Your mod link

https://github.com/Capeling/Demons-In-Garage-2.2/releases/download/v1.1.0/capeling.demons_in_garage_2.2.geode

**Comment by TheSillyDoggo** [comment]
He had 7 years how is this not in vanilla gd already

**Comment by MuhXd** [comment]
lol

**Comment by altalk23** [comment]
!accept
