### ISSUE TITLE
Scale lock not working. Its a bug, not an issue.

### ISSUE THREAD

**Issue by supergamer66000** [geode-sdk/indexer#449]
### Your mod link

C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash

**Comment by TheSillyDoggo** [comment]
there is so much wrong with this

**Comment by TheSillyDoggo** [comment]
this is a vanilla bug and indexer repo is for adding mods to the index

**Comment by supergamer66000** [comment]
ok, sorry. Im actually kinda new to using github and didn't start using it untill recently to post my projects, sorry if i didn't use it the intended way

**Comment by supergamer66000** [comment]
i just now realized were i put it. Ignore this
