### ISSUE TITLE
Add a Restart Game button in main menu

### ISSUE THREAD

**Issue by Weebifying** [geode-sdk/indexer#472]
### Your mod link

https://github.com/Weebifying/restartbutton-geode/releases/download/v1.0.0/weebify.restartbtn.geode

**Comment by Weebifying** [comment]
idk

**Comment by altalk23** [comment]
add node ids as a dependency

**Comment by Weebifying** [comment]
isnt menulayer in base geode already?

**Comment by Fleeym** [comment]
yeah, its fine

**Comment by Fleeym** [comment]
!accept

**Comment by Weebifying** [comment]
oh i closed just as u did that does it work

**Comment by Fleeym** [comment]
lmao

**Comment by Fleeym** [comment]
!accept

**Comment by Weebifying** [comment]
man i wanted to close this and make a new issue for v1.0.1 XD

**Comment by Fleeym** [comment]
seems to have been added, ill close this and you can make a new issue with the new ver
