### ISSUE TITLE
Add "Eminem gei test (1.0)"

### ISSUE THREAD

**Issue by elnexreal** [geode-sdk/indexer#489]
### Your mod link

https://github.com/elnexreal/indexer/releases/download/1.0/elnexreal.eminemgeitest.geode

**Comment by Weebifying** [comment]
the description of the mod translates to "Eminem wants to ask if you are gay, can you answer him?"

**Comment by elnexreal** [comment]
> the description of the mod translates to "Eminem wants to ask if you are gay, can you answer him?"

yea it is a mod that i made inspired in a .exe my friend made as a joke

**Comment by altalk23** [comment]
ok but where source

**Comment by elnexreal** [comment]
> ok but where source

lemme upload it

**Comment by Uproxide** [comment]
eminem
wassup guys its me m&m

**Comment by elnexreal** [comment]
# SOURCE CODE

https://github.com/elnexreal/EminemGeiTest/tree/main

**Comment by Uproxide** [comment]
can i make an english version or [perhaps make a setting that turns it english

**Comment by elnexreal** [comment]
> can i make an english version or [perhaps make a setting that turns it english

obviously you can :)

**Comment by Uproxide** [comment]
hoorah!

**Comment by Uproxide** [comment]
quick question, what does eri mean in english? im not fully sure since im english

**Comment by Uproxide** [comment]
ahh its are

**Comment by elnexreal** [comment]
> quick question, what does eri mean in english? im not fully sure since im english

the thing translates to "are u gay"

**Comment by elnexreal** [comment]
neu bersion releaced
