### ISSUE TITLE
Add xdBot v1.0.1

### ISSUE THREAD

**Issue by ZiLko** [geode-sdk/indexer#508]
### Your mod link

https://github.com/ZiLko/xdBot/releases/download/v1.0.1/xdbot.geode

**Comment by ZiLko** [comment]
Source: https://github.com/ZiLko/xdBot/archive/refs/tags/v1.0.1.zip

**Comment by altalk23** [comment]
someone didnt like geodes file utils looks like

**Comment by altalk23** [comment]
!accept
