### ISSUE TITLE
Add Stat Changes 1.0.0

### ISSUE THREAD

**Issue by RedLime** [geode-sdk/indexer#511]
### Your mod link

https://github.com/RedLime/Stat-Changes-Geode/releases/download/1.0.0/redlime.statchanges.geode

**Comment by RedLime** [comment]
source: https://github.com/RedLime/Stat-Changes-Geode/
download: https://github.com/RedLime/Stat-Changes-Geode/releases/download/1.0.0/redlime.statchanges.geode

## Additional Notes
I was published `KR Profile Leaderboard`, and it's technically same mod with this.
But this mod have configurables, new sprites for stats and apply for top 10k players.
 
So `KR Profile Leaderboard` need to be removed from indexer.

**Comment by altalk23** [comment]
!accept
