### ISSUE TITLE
Add No Robtop Logo

### ISSUE THREAD

**Issue by Deadcello** [geode-sdk/indexer#515]
### Your mod link

https://github.com/Deadcello/no-robtop-logo-geode/releases/download/release/skyward.no_robtop_logo.geode

**Comment by Deadcello** [comment]
source: [https://github.com/Deadcello/no-robtop-logo-geode](https://github.com/Deadcello/no-robtop-logo-geode)

**Comment by Weebifying** [comment]
robtop hater spotted

**Comment by Deadcello** [comment]
real?!?!?!?!?

**Comment by altalk23** [comment]
cursed code that even i dont know how it works or if it works

**Comment by altalk23** [comment]
!accept

**Comment by altalk23** [comment]
add node ids mod as a dependency

**Comment by Deadcello** [comment]
okay

**Comment by Deadcello** [comment]
I fixed it

**Comment by Deadcello** [comment]
https://github.com/Deadcello/no-robtop-logo-geode/releases/download/1.01/skyward.no_robtop_logo.geode
