### ISSUE TITLE
Add No Controller Glyphs

### ISSUE THREAD

**Issue by Kevadroz** [geode-sdk/indexer#516]
### Your mod link

https://github.com/Kevadroz/NoControllerGlyphs/releases/download/v0.1.0/kevadroz.nocontrollerglyphs.geode

**Comment by Kevadroz** [comment]
source: https://github.com/Kevadroz/NoControllerGlyphs

**Comment by altalk23** [comment]
very cursed code but eh

**Comment by altalk23** [comment]
!accept
