### ISSUE TITLE
Update No Robtop Logo

### ISSUE THREAD

**Issue by Deadcello** [geode-sdk/indexer#518]
### Your mod link

https://github.com/Deadcello/no-robtop-logo-geode/releases/download/1.01/skyward.no_robtop_logo.geode

**Comment by Deadcello** [comment]
Source: https://github.com/Deadcello/no-robtop-logo-geode

**Comment by Cvolton** [comment]
likely broken on beta.10, as it defines IDs for the twitch and discord buttons

**Comment by Deadcello** [comment]
oh

**Comment by Deadcello** [comment]
ill fix it now

**Comment by Fleeym** [comment]
you can reopen the issue when you fix it (cuz im guessing you're gonna make a new version)

**Comment by Deadcello** [comment]
yeah i am

**Comment by Fleeym** [comment]
I meant open a new one btw, my bad
