### ISSUE TITLE
Bye More Games v1.0

### ISSUE THREAD

**Issue by Uproxide** [geode-sdk/indexer#530]
### Your mod link

https://github.com/Uproxide/GeodeMods/releases/download/BMG1.0/uproxide.bye_more_games.geode

**Comment by Uproxide** [comment]
only update for it ever, all it does is kill the more games button cause screw that guy

**Comment by Weebifying** [comment]
isnt there another mod exactly like this waiting for approval

**Comment by Kingminer7** [comment]
> isnt there another mod exactly like this waiting for approval

yeah there is

**Comment by Uproxide** [comment]
yea there is (#acceptevilgeometrydash)
