### ISSUE TITLE
Add "Minecraft Splash" v1.0.0

### ISSUE THREAD

**Issue by ShineUA** [geode-sdk/indexer#535]
### Your mod link

https://github.com/ShineUA/minecraft-splash-mod-geode/releases/download/v1.0.0/shineua.minecraft_splash.geode

**Comment by ShineUA** [comment]
Source: https://github.com/ShineUA/minecraft-splash-mod-geode

**Comment by Weebifying** [comment]
you finally figured it out, good job

**Comment by ShineUA** [comment]
Finally!

**Comment by Fleeym** [comment]
Update it to use "geode": "2.0.0" on the mod.json, otherwise the mod will break on every geode update

**Comment by Cvolton** [comment]
also `"gd": "*"` is incorrect, since the windows version needs rebuilding for every gd update

**Comment by Fleeym** [comment]
i didnt check that thank you cvolton

**Comment by ShineUA** [comment]
ok I'll do that

**Comment by ShineUA** [comment]
> also `"gd": "*"` is incorrect, since the windows version needs rebuilding for every gd update

So, for other platforms I can set `*`?

**Comment by Fleeym** [comment]
no, you add the latest version available on each
android: 2.205
windows: 2.204
im guessing you didnt build mac but 2.200

**Comment by ShineUA** [comment]
> no, you add the latest version available on each android: 2.205 windows: 2.204 im guessing you didnt build mac but 2.200

Yeah, I didn't built mac because it fails

**Comment by ShineUA** [comment]
Do I need create a new issue?

**Comment by ShineUA** [comment]
Release v1.1.1: https://github.com/ShineUA/minecraft-splash-mod-geode/releases/download/v1.1.1/shineua.minecraft_splash.geode
Source: https://github.com/ShineUA/minecraft-splash-mod-geode

**Comment by Fleeym** [comment]
yeah, create a new issue

**Comment by ShineUA** [comment]
ok
