### ISSUE TITLE
Add "Eminem Gei Test" (v1.1.0)

### ISSUE THREAD

**Issue by elnexreal** [geode-sdk/indexer#538]
### Your mod link

https://github.com/elnexreal/EminemGeiTest/releases/download/1.1.0/elnexreal.eminemgeitest.geode

**Comment by elnexreal** [comment]
# Source code
https://github.com/elnexreal/EminemGeiTest

**Comment by Fleeym** [comment]
I don't think I need to explain why I'm denying this one
