### ISSUE TITLE
Add Daily Transfer

### ISSUE THREAD

**Issue by GDSaneS** [geode-sdk/indexer#539]
### Your mod link

https://github.com/GDSaneS/Daily-Transfer/releases/download/v1.0.0/sanes.daily-transfer.geode

**Comment by GDSaneS** [comment]
Source Code:

https://github.com/GDSaneS/Daily-Transfer

**Comment by Fleeym** [comment]
use "geode": "2.0.0" in mod.json, otherwise your mod will break with every beta release

**Comment by GDSaneS** [comment]
Thanks, I've now updated it.

**Comment by Fleeym** [comment]
looks good

**Comment by Fleeym** [comment]
!accept
