### ISSUE TITLE
Add Better Startpos UI

### ISSUE THREAD

**Issue by eitanmdk** [geode-sdk/indexer#540]
### Your mod link

https://github.com/eitanmdk/Better-2.2-UIS/releases/download/geode/eitan.betterUIS.geode

**Comment by Fleeym** [comment]
man thats not how you add your source to github

**Comment by eitanmdk** [comment]
do I need to add source?

**Comment by Fleeym** [comment]
yeah

**Comment by Fleeym** [comment]
just have it in your repo

**Comment by eitanmdk** [comment]
ah ok I will add it

**Comment by eitanmdk** [comment]
Already added it @Fleeym

**Comment by Fleeym** [comment]
Sorry but I can't accept this, it uses objectAtIndex way too much.
Please refer to this tutorial to learn about string IDs: https://docs.geode-sdk.org/tutorials/nodetree
There's a mod in GD that adds a lot of those ids to different layers, you can add it as a dependency to your mod and use them.
