### ISSUE TITLE
OpenHack v1.6.0

### ISSUE THREAD

**Issue by Prevter** [geode-sdk/indexer#553]
### Your mod link

https://github.com/Prevter/GDOpenHack/releases/download/1.6.0/prevter.openhack.geode

**Comment by Prevter** [comment]
Repository (geode branch): https://github.com/Prevter/GDOpenHack/tree/geode

**Comment by matcool** [comment]
https://github.com/Prevter/GDOpenHack/blob/geode/src/hook.cpp#L228
dont use minhook!

**Comment by matcool** [comment]
embedding minhook in your own mod is a bad idea, hook conflicts can cause crashes or hooks being called twice.
If you still want to do sigscanning, you can just do hooks manually:
https://docs.geode-sdk.org/tutorials/manualhooks

**Comment by Prevter** [comment]
i know, but some of them were just crashing the game unless done the old way

**Comment by Prevter** [comment]
will check if something can be done about it
