### ISSUE TITLE
Add GDDL Integration v1.0.0-beta.1

### ISSUE THREAD

**Issue by B1rtek** [geode-sdk/indexer#557]
### Your mod link

https://github.com/B1rtek/Geode-GDDLIntegration/releases/download/v1.0.0-beta.1/b1rtek.gddlintegration.geode

**Comment by B1rtek** [comment]
(copypasted from the [pull request](https://github.com/geode-sdk/indexer/pull/556) )

I'd like to publish my mod
https://github.com/B1rtek/Geode-GDDLIntegration

It simply adds information about the difficulty tier assigned to the level on the Geometry Dash Demon Ladder
(it has a small issue as stated in the README.md and about.md - usernames sometimes turn into - for some reason and I have no idea why that happens, it's slightly annoying and that's why I marked it as beta, I'd like some help with that)

**Comment by matcool** [comment]
the - username bug seems to be caused by rob, @Cvolton would know more

**Comment by matcool** [comment]
!accept

**Comment by B1rtek** [comment]
^^ Thank you

> the - username bug seems to be caused by rob, @Cvolton would know more

Maybe I never catched that, but it seemed like it emerged after I installed my mod...

**Comment by Cvolton** [comment]
usernames in about.md always turn into `-` if you don't have any level by that user in your saved levels - this is Geode not accounting for vanilla behavior (therefore I would consider this more of a Geode bug than a vanilla bug). If you use BetterInfo, it includes a workaround for the issue, so that might be why you wouldn't have previously caught it.

**Comment by B1rtek** [comment]
I use BetterInfo, it's extremely useful, thank you for making it ^^

**Comment by Fleeym** [comment]
hey there, I can't find a way to reach you anywhere else. It seems your mod calls retain() on LevelInfoLayer but never calls release(). This causes crashes (pretty bad ones). Please update your mod and fix it.
the retain call is here: https://github.com/B1rtek/Geode-GDDLIntegration/blob/13a6a86f22e22c505216be9a5f78c24def31320a/src/LevelInfoLayer.cpp#L53

**Comment by matcool** [comment]
its also missing m_fields here https://github.com/B1rtek/Geode-GDDLIntegration/blob/master/src/LevelInfoLayer.cpp#L19

**Comment by dankmeme01** [comment]
good job guys

**Comment by B1rtek** [comment]
> hey there, I can't find a way to reach you anywhere else. It seems your mod calls retain() on LevelInfoLayer but never calls release(). This causes crashes (pretty bad ones). Please update your mod and fix it. the retain call is here: https://github.com/B1rtek/Geode-GDDLIntegration/blob/13a6a86f22e22c505216be9a5f78c24def31320a/src/LevelInfoLayer.cpp#L53

I forgot to remove that after trying to make it not crash in the first place and then I missed it completely, thanks for pointing it out!

**Comment by Fleeym** [comment]
> > hey there, I can't find a way to reach you anywhere else. It seems your mod calls retain() on LevelInfoLayer but never calls release(). This causes crashes (pretty bad ones). Please update your mod and fix it. the retain call is here: https://github.com/B1rtek/Geode-GDDLIntegration/blob/13a6a86f22e22c505216be9a5f78c24def31320a/src/LevelInfoLayer.cpp#L53
> 
> I forgot to remove that after trying to make it not crash in the first place and then I missed it completely, thanks for pointing it out!

its still good to keep it, just call release after the request is over
