### ISSUE TITLE
GD Swear Filter

### ISSUE THREAD

**Issue by CoderQCFromScraatch** [geode-sdk/indexer#561]
### Your mod link

https://github.com/CoderQCFromScraatch/gd-swear-filter/releases/download/1.0.1/coderqc.gdswearfilter.geode

**Comment by CoderQCFromScraatch** [comment]
Source if needed (yes my code sucks):
https://github.com/CoderQCFromScraatch/gd-swear-filter/tree/main

**Comment by Fleeym** [comment]
!accept
