### ISSUE TITLE
Add Evil Geometry Dash v1.0

### ISSUE THREAD

**Issue by Uproxide** [geode-sdk/indexer#567]
### Your mod link

https://github.com/Uproxide/GeodeMods/releases/download/egd-v1.0.1/uproxide.evilgd.geode

**Comment by Uproxide** [comment]
# Source

https://github.com/Uproxide/GeodeMods/tree/main/Evil%20Geometry%20Dash

**Comment by Uproxide** [comment]
updated

**Comment by Fleeym** [comment]
what the hell, why not

**Comment by Fleeym** [comment]
!accept

**Comment by Uproxide** [comment]
we win.
