### ISSUE TITLE
Music Manager

### ISSUE THREAD

**Issue by sse2** [geode-sdk/indexer#573]
### Your mod link

https://github.com/sse2/gd-music-manager/releases/download/v0.0.1/sse2.gj-music-manager.geode

**Comment by sse2** [comment]
Also please update your official docs to point out this is how you're supposed to submit mods, since everything I read pointed to me making a PR on the mods repo

**Comment by Fleeym** [comment]
will change, sorry about that

**Comment by Fleeym** [comment]
!accept
