### ISSUE TITLE
Update sse2.gj-music-manager to 0.0.2

### ISSUE THREAD

**Issue by sse2** [geode-sdk/indexer#579]
### Your mod link

https://github.com/sse2/gd-music-manager/releases/download/v0.0.2/sse2.gj-music-manager.geode

**Comment by altalk23** [comment]
@sse2 id say dont rely on cwd and use Mod::get()->getSaveDir() instead

**Comment by matcool** [comment]
god this is an ugly mod id

**Comment by matcool** [comment]
!accept
