### ISSUE TITLE
Cleaner Menu

### ISSUE THREAD

**Issue by 29cmb** [geode-sdk/indexer#580]
### Your mod link

https://github.com/29cmb/CleanMenu/releases/download/2.204-3/devcmb.cleanermenu.geode

**Comment by altalk23** [comment]
id recommend not targeting a single beta and just 2.0.0 instead

**Comment by 29cmb** [comment]
2.0.0 was targetted instead, thanks for the insight

**Comment by matcool** [comment]
!accept
