### ISSUE TITLE
Update Custom Name (v1.1.3)

### ISSUE THREAD

**Issue by coopeeo** [geode-sdk/indexer#581]
### Your mod link

https://github.com/coopeeo/customname-geodemod/releases/download/1.1.3/coopeeo.customname.geode

**Comment by coopeeo** [comment]
### Source
https://github.com/coopeeo/customname-geodemod/

**Comment by coopeeo** [comment]
so um like can i get review pwease! tanks you!

**Comment by coopeeo** [comment]
!accept

**Comment by coopeeo** [comment]
im desprwite pwease i beg also #586 too

**Comment by matcool** [comment]
!accept
