### ISSUE TITLE
Update techstudent10.discord_rich_presence to v2.0.0 (2.204)

### ISSUE THREAD

**Issue by TechStudent10** [geode-sdk/indexer#584]
### Your mod link

https://github.com/TechStudent10/DiscordRPC/releases/download/v2.0.0/techstudent10.discord_rich_presence.geode

**Comment by TechStudent10** [comment]
i think ive submitted enough mods to be verified, tbh /j

**Comment by coopeeo** [comment]
lol

**Comment by Fleeym** [comment]
hi tech!

**Comment by Fleeym** [comment]
!accept

**Comment by TechStudent10** [comment]
> hi tech!

heya, thanks!
