### ISSUE TITLE
GDDL Integration v1.0.2

### ISSUE THREAD

**Issue by B1rtek** [geode-sdk/indexer#585]
### Your mod link

https://github.com/B1rtek/Geode-GDDLIntegration/releases/download/v1.0.2/b1rtek.gddlintegration.geode

**Comment by B1rtek** [comment]
Thanks to the contributions of many players we got from beta.1 all the way to v1.0.2 in a single update
All the issues with the code stated in the issue from version v1.0.0-beta.1 should be fixed in this version

**Comment by Fleeym** [comment]
uhh, you should call release in the request response function (.then). What you're doing is calling retain(), running the request (that didn't end yet), then calling release(). after some time the request actually finishes, and your layer isn't retained

**Comment by B1rtek** [comment]
My mind at 2 AM: 
Anyways, I moved it back where it should be and I replaced the file in the releases tab

**Comment by Fleeym** [comment]
!accept

**Comment by B1rtek** [comment]
^^ Thank you
