### ISSUE TITLE
Add GD Mega Overlay

### ISSUE THREAD

**Issue by maxnut** [geode-sdk/indexer#593]
### Your mod link

https://github.com/maxnut/GDMegaOverlay/releases/download/2.2/maxnu.gd_mega_overlay.geode

**Comment by maxnut** [comment]
Source code: https://github.com/maxnut/GDMegaOverlay

**Comment by matcool** [comment]
omg gd-imgui-cocos user.. no more cocosexplorer imgui-hook copy
