### ISSUE TITLE
Add mod: Unlisted Objects in Editor

### ISSUE THREAD

**Issue by legowiifun** [geode-sdk/indexer#621]
### Your mod link

https://github.com/legowiifun/Geometry-Dash-Unlisted-Objects-in-Editor/releases/download/v1.0.0/legowiifun.unlisted_objects_in_editor.geode
### Your mod source code

https://github.com/legowiifun/Geometry-Dash-Unlisted-Objects-in-Editor

### Your mod description

This mod adds several unlisted objects to the level editor, organizing them in the appropriate tabs.

**Comment by matcool** [comment]
invalid mod link. please make it a direct link to the .geode file

**Comment by legowiifun** [comment]
I changed the link. It should be a direct link to the .geode file now.

**Comment by altalk23** [comment]
!accept
