### ISSUE TITLE
Add Geode Contributors (v1.0.0)

### ISSUE THREAD

**Issue by Uproxide** [geode-sdk/indexer#625]
### Your mod link

https://github.com/Uproxide/GeodeMods/releases/download/gdc-v1.0/uproxide.geodedevelopers.geode

### Your mod source code

https://github.com/Uproxide/GeodeMods/tree/main/Geode%20Contributors

### Your mod description

Gives geode contributors (that are whitelisted in the code) a special badge near the youtube icon

**Comment by matcool** [comment]
!accept
