### ISSUE TITLE
Update techstudent10.discord_rich_presense to v2.2.0

### ISSUE THREAD

**Issue by TechStudent10** [geode-sdk/indexer#631]
### Your mod link

https://github.com/TechStudent10/DiscordRPC/releases/download/v2.2.0/techstudent10.discord_rich_presence.geode

### Your mod source code

https://github.com/TechStudent10/DiscordRPC

### Your mod description

I'm updating this mod for the billionth time I think you know what it does

**Comment by TechStudent10** [comment]
i'm probably being the annoying guy but

a. that should say "staff" and not "verified"
b. what are the requirements for being verified anyway

good night

**Comment by matcool** [comment]
!accept
