### ISSUE TITLE
Hide Pause Menu Hack

### ISSUE THREAD

**Issue by EKVgd** [geode-sdk/indexer#633]
### Your mod link

https://github.com/EKVgd/hidePauseMenuHack/releases/download/v1.0.1/ekv.hidePauseMenuHack.geode

### Your mod source code

https://github.com/EKVgd/hidePauseMenuHack

### Your mod description

This mod adds A button to the pause menu to hide it.

**Comment by altalk23** [comment]
invalid mod link, please put a direct link for the geode file

**Comment by cgytrus** [comment]
editing the issue wont work, you have to create a new one
