### ISSUE TITLE
Same Dual Color

### ISSUE THREAD

**Issue by asakizuki** [geode-sdk/indexer#638]
### Your mod link

https://github.com/asakizuki/Same-Dual-Color/releases/download/v1.0.0/asaki_zuki.same_dual_color.geode

### Your mod source code

https://github.com/asakizuki/Same-Dual-Color

### Your mod description

Make colors of two players the same in level and editor.

**Comment by matcool** [comment]
avoid specifying beta in mod.json

**Comment by matcool** [comment]
!accept
