### ISSUE TITLE
add mod: menu loop randomizer

### ISSUE THREAD

**Issue by jojo989** [geode-sdk/indexer#645]
actually nvm im embarassed of my shitty code

**Comment by altalk23** [comment]
please use `Mod::get()->getSaveDir()` or `Mod::get()->getConfigDir()` to put your `menuloopsong` folder instead of cluttering the root folder

**Comment by jojo989** [comment]
ok i updated the mod! :d

**Comment by jojo989** [comment]
wait it has a few bugs
