### ISSUE TITLE
Death Markers

### ISSUE THREAD

**Issue by Bean0of** [geode-sdk/indexer#652]
### Your mod link

https://github.com/Bean0of/deathmarkers/releases/download/v1.0.1-beta/adam_729.deathmarkers.geode

### Your mod source code

https://github.com/Bean0of/deathmarkers

### Your mod description

Adds super mario maker death markers to gd.
https://www.youtube.com/watch?v=b4qcOJB5CZM

**Comment by altalk23** [comment]
!accept
