### ISSUE TITLE
Add Coins in Pause Menu

### ISSUE THREAD

**Issue by Weebifying** [geode-sdk/indexer#653]
### Your mod link

https://github.com/Weebifying/coins-in-pause-menu-geode/releases/download/v1.0.0/weebify.coins_in_pause_menu.geode

### Your mod source code

https://github.com/Weebifying/coins-in-pause-menu-geode

### Your mod description

Shows the current level's coins in the pause menu

**Comment by Weebifying** [comment]
!accept

**Comment by Fleeym** [comment]
nice try lil guy

**Comment by Weebifying** [comment]
oh no i was set up

**Comment by matcool** [comment]
!accept
