### ISSUE TITLE
save from level page

### ISSUE THREAD

**Issue by EKVgd** [geode-sdk/indexer#654]
### Your mod link

https://github.com/EKVgd/saveFromLevelMenu/releases/download/v1.0.0/ekv.save_on_level_page.geode

### Your mod source code

https://github.com/EKVgd/saveFromLevelMenu/

### Your mod description

My mod allows you to save your game from the level page instead of having to go back to the main menu

**Comment by altalk23** [comment]
please add `geode.node-ids` mod as a dependency

**Comment by cgytrus** [comment]
release an update to the mod under a new version number and resubmit it, you cant modify an existing version.
