### ISSUE TITLE
ShadyPause

### ISSUE THREAD

**Issue by ShadyIsCool** [geode-sdk/indexer#657]
### Your mod link

https://github.com/ShadyIsCool/ShadyPause/releases/download/v1.0.2/shadyiscool.shadypause.geode

### Your mod source code

https://github.com/ShadyIsCool/ShadyPause

### Your mod description

Lets you toggle the pause menu with a keybind (just now realising theres another mod just like this but i _did_ technically finish it last week, i was just adding the icon and a readme today), will add more features in future thoug h

**Comment by Fleeym** [comment]
please don't use "gd": "*". that's for mods that don't need any updates (theoretically) when GD gets an update

**Comment by ShadyIsCool** [comment]
wow i just got into bed, will change in the morning

**Comment by ShadyIsCool** [comment]
okay @Fleeym it's all updated now

**Comment by matcool** [comment]
!accept
