### ISSUE TITLE
Update Geode Contributors (1.0.1)

### ISSUE THREAD

**Issue by Uproxide** [geode-sdk/indexer#664]
### Your mod link

https://github.com/Uproxide/GeodeMods/releases/download/gdc1.0.1/uproxide.geodedevelopers.geode

### Your mod source code

https://github.com/Uproxide/GeodeMods/tree/main/Geode%20Contributors

### Your mod description

my mod does NOT remove creator layer
(fixed crashing and finally added the damn dependency for node ids)

**Comment by Uproxide** [comment]
The

**Comment by Fleeym** [comment]
!accept
