### ISSUE TITLE
Update sse2.gj-music-manager to v0.1.0

### ISSUE THREAD

**Issue by sse2** [geode-sdk/indexer#675]
### Your mod link

https://github.com/sse2/gd-music-manager/releases/download/v0.1.0/sse2.gj-music-manager.geode

### Your mod source code

https://github.com/sse2/gd-music-manager

### Your mod description

No longer relying on cwd, also fixed mod.json version
Note: some path formatting uglyness is still required as fmod refuses to play tracks if the path it has been given isn't relative to the `Resources` folder. This doesn't cause any issues on Windows and that's the only platform I want to support for now

**Comment by sse2** [comment]
!accept

**Comment by Fleeym** [comment]
!accept
