### ISSUE TITLE
HidePauseButton

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#680]
### Your mod link

https://github.com/RayDeeUx/HidePauseButton/releases/download/v1.0.0/raydeeux.hidepausebutton.geode

### Your mod source code

https://github.com/RayDeeUx/HidePauseButton

### Your mod description

Hides the pause button in Geometry Dash, even when "Show Cursor In-Game" is enabled in the Geometry Dash settings.

![image](https://github.com/geode-sdk/indexer/assets/51521765/552d5838-4514-4e55-bbf8-1313d12e322e)

**Comment by cgytrus** [comment]
!accept
