### ISSUE TITLE
Add WSLiveEditor

### ISSUE THREAD

**Issue by iAndyHD3** [geode-sdk/indexer#682]
### Your mod link

https://github.com/iAndyHD3/WSLiveEditor/releases/download/v1.0.1/iandyhd3.wsliveeditor.geode

### Your mod source code

https://github.com/iAndyHD3/WSLiveEditor

### Your mod description

WSLiveEditor is a helpful tool for quick testing levels that are generated programmatically by a tool, by opening a Websocket Server it allows to remove old objects and add new ones without needing to re-open the editor or restart the game. It was originally made for spwn. Documentation and examples can be found in the readme of the repo

**Comment by Fleeym** [comment]
damn this looks really cool. it would be nice to make the ws port customizable with a setting or something

**Comment by Fleeym** [comment]
!accept
