### ISSUE TITLE
Add On Death

### ISSUE THREAD

**Issue by coopeeo** [geode-sdk/indexer#685]
### Your mod link

https://github.com/coopeeo/ondeath-geode/releases/download/1.0.0/coopeeo.ondeath.geode

### Your mod source code

https://github.com/coopeeo/ondeath-geode/

### Your mod description

Does an action of your choice (not yet) when you die. Currently there is only the restart action.

**Comment by matcool** [comment]
not a fan of this, not having the whole bsod on death fiasco again

**Comment by coopeeo** [comment]
awwww ok can i resubmit if i change it to a webhook and no restart option?
