### ISSUE TITLE
Update HidePauseButton

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#695]
### Your mod link

https://github.com/RayDeeUx/HidePauseButton/releases/download/v1.1.0/raydeeux.hidepausebutton.geode

### Your mod source code

https://github.com/RayDeeUx/HidePauseButton/

### Your mod description
Hides the pause button, even if "Show Cursor In-Game" is enabled in GD's settings.
Added support for macOS, Android, and (hypothetically) iOS..
For the Steam version, added additional option to make the hidden pause button unclickable as well.

**Comment by cgytrus** [comment]
yeah um that does not support anything *but* mac
![image](https://github.com/geode-sdk/indexer/assets/30120687/338579c7-0cd9-4630-852f-2b3bb8903cf8)
and geode doesnt even support ios....

**Comment by RayDeeUx** [comment]
uhoh! let me see what's wrong

**Comment by cgytrus** [comment]
just use actions, thats also a good way to prove that your releases actually match your source code

**Comment by RayDeeUx** [comment]
updated the `.geode` file

**Comment by kionyas** [comment]
"ios support" 🙏

**Comment by Weebifying** [comment]
it was revealed to me in a dream that ios geode will be released in 2026

**Comment by matcool** [comment]
impressive how you support nothing but mac, only crystal does that

**Comment by RayDeeUx** [comment]
direct link updated

**Comment by Cvolton** [comment]
!accept
