### ISSUE TITLE
Add Demon List Team Icons

### ISSUE THREAD

**Issue by ArkaneOnline** [geode-sdk/indexer#702]
### Your mod link

https://github.com/ArkaneOnline/dl-team-icons/releases/download/v1.0.0/arkane.dl-team-icons.geode

### Your mod source code

https://github.com/ArkaneOnline/dl-team-icons

### Your mod description

A simple mod based on the "Geode  Contributors" mod that adds an icon to Demon List team member profile pages

**Comment by matcool** [comment]
!accept
