### ISSUE TITLE
Update Death Markers v1.0.3

### ISSUE THREAD

**Issue by Bean0of** [geode-sdk/indexer#711]
### Your mod link

https://github.com/Bean0of/deathmarkers/releases/download/v1.0.3/adam_729.deathmarkers.geode

### Your mod source code

https://github.com/Bean0of/deathmarkers

### Your mod description

- New marker icon
- Fixed death markers displaying on both sides in dual/2 plr mode when only one icon crashes
- Fixed markers not displaying in zoomed out platformer levels

**Comment by matcool** [comment]
!accept
