### ISSUE TITLE
Update Flashlight Mod to v1.0.1

### ISSUE THREAD

**Issue by LXanii** [geode-sdk/indexer#713]
### Your mod link

https://github.com/LXanii/Flashlight-Mod/releases/download/v1.0.1/xanii.flashlight.geode

### Your mod source code

https://github.com/LXanii/Flashlight-Mod

### Your mod description

// 1.0.1 Change log
// Fixed bug when resetting level after completion
// Fixed bug when flashlight was enabled on platformer level
// Fixed several crashes
// Added saves to the flashlight toggle after exiting a level
// Added new settings to mod, "Always Dark" names self explanatory
// Added setting to change when the darkness gets to max on flashlight, "Max Percent"

**Comment by matcool** [comment]
!accept
