### ISSUE TITLE
Add Roulette v1.0.0

### ISSUE THREAD

**Issue by SergeyMC9730** [geode-sdk/indexer#714]
### Your mod link

https://github.com/SergeyMC9730/roulette/releases/download/v1.0.0/dogotrigger.roulette.geode

### Your mod source code

https://github.com/SergeyMC9730/roulette

### Your mod description

Adds random events on every attempt.

**Comment by SergeyMC9730** [comment]
!accept

**Comment by SergeyMC9730** [comment]
no accept? :pleading_face: 

ok.

**Comment by Fleeym** [comment]
:(

**Comment by CdcOnGitHub** [comment]
this is me when no accept: 😭😭😭😭😭😭😭💔💔💔💔😿😿😿😢😢

**Comment by SergeyMC9730** [comment]
can i know why mod is not getting accepted rn

**Comment by CdcOnGitHub** [comment]
CCSprite *_nadezhdin;

**Comment by Uproxide** [comment]
hi cdc

**Comment by Uproxide** [comment]
i no no wanna :(

**Comment by zGuschin** [comment]
!accept

**Comment by Uproxide** [comment]
!deny

**Comment by matcool** [comment]
ur about.md is unchanged....

**Comment by SergeyMC9730** [comment]
lol

**Comment by matcool** [comment]
!accept

**Comment by SergeyMC9730** [comment]
will fix in a  next update
