### ISSUE TITLE
Add Death Tracker

### ISSUE THREAD

**Issue by eloh-mrow** [geode-sdk/indexer#716]
### Your mod link

https://github.com/eloh-mrow/death-tracker/releases/download/v1.0.0/elohmrow.death_tracker.geode

EDIT: current version: https://github.com/eloh-mrow/death-tracker/releases/download/v1.0.2/elohmrow.death_tracker.geode

### Your mod source code

https://github.com/eloh-mrow/death-tracker

### Your mod description

My mod adds a new button on the attempts dialog that shows all your normal mode deaths at  each percentage.

**Comment by eloh-mrow** [comment]
i made a bugfix update to the mod, figured i would put the newer ver here since it hasn't been accepted yet:
https://github.com/eloh-mrow/death-tracker/releases/download/v1.0.1/elohmrow.death_tracker.geode

**Comment by matcool** [comment]
!accept
