### ISSUE TITLE
Add LoadingScreenTweaks

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#722]
### Your mod link

https://github.com/RayDeeUx/LoadingScreenTweaks/releases/download/v1.0.0/raydeeux.loadingscreentweaks.geode

### Your mod source code

https://github.com/RayDeeUx/LoadingScreenTweaks

### Your mod description

Hides various elements of your choice from Geometry Da   sh's loading screen.

![demo](https://github.com/RayDeeUx/LoadingScreenTweaks/raw/main/demonstration.png)

**Comment by matcool** [comment]
this mod will not work on any gd version because you rely on loadinglayer::init

**Comment by RayDeeUx** [comment]
updated binary, shouldn't have the potential issue mentioned above by @matcool anymore

**Comment by matcool** [comment]
is the release link the same

**Comment by matcool** [comment]
funny you added the ios but whatever

**Comment by matcool** [comment]
!accept

**Comment by altalk23** [comment]
btw either beta 14 or nightlt has node ids for loadinglayer
