### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by zohnannor** [geode-sdk/indexer#725]
### Your mod link

https://github.com/zohnannor/dark-mode-gd/releases/download/v0.1.0/zohnannor.dark_mode.geode

### Your mod source code

https://github.com/zohnannor/dark-mode-gd

### Your mod description

Changes hard-coded colors to a dark-mode-style theme with an option to set custom colors. Will be updated with new options.  
Inspired by Absolute's Dark Mode Texture Pack Patcher for 2.1

**Comment by matcool** [comment]
!accept
