### ISSUE TITLE
Add Carrot Button

### ISSUE THREAD

**Issue by Uproxide** [geode-sdk/indexer#727]
### Your mod link

https://github.com/carrotdevs/carrot-button-geode/releases/download/1.0.0/carrot_devs.carrot_button.geode

### Your mod source code

https://github.com/carrotdevs/carrot-button-geode

### Your mod description

Adds a carrot button to the LevelSearchBrowser and searches for levels with carrot in the name. kinda useless but funny! might inspire a seperate mod eventually :3

**Comment by coopeeo** [comment]
Most useful mod

**Comment by altalk23** [comment]
levelsearchlayer has node ids, please use them

**Comment by Uproxide** [comment]
s
