### ISSUE TITLE
Add "Copy Song ID" (v1.1.0)

### ISSUE THREAD

**Issue by elnexreal** [geode-sdk/indexer#738]
### Your mod link

https://github.com/elnexreal/copy_song_id/releases/download/1.1.0/elnexreal.copy_song_id.geode

### Your mod source code

https://github.com/elnexreal/copy_song_id

### Your mod description

Adds the function to click the song ID of a level and copy it (like mega hack v7 had)

**Comment by altalk23** [comment]
levelinfolayer has node ids, please use them

**Comment by elnexreal** [comment]
@altalk23 updated

**Comment by Fleeym** [comment]
add jukebox as an incompatibility. its the same as adding dependencies, just set importance to "breaking"

**Comment by elnexreal** [comment]
updated, i think its ready now

**Comment by Fleeym** [comment]
should be fine
btw if you setup some node ids i can make jukebox work with your mod

**Comment by elnexreal** [comment]
okay, prolly tomorrow i will try setting up id's (i was going to do it in the first place but forgor 💀 )

**Comment by Fleeym** [comment]
!accept
