### ISSUE TITLE
GDDP Integration

### ISSUE THREAD

**Issue by Minemaker0430** [geode-sdk/indexer#740]
### Your mod link

https://github.com/Minemaker0430/GDDPIntegration/releases/download/v1.0.0/minemaker0430.gddp_integration.geode

### Your mod source code

https://github.com/Minemaker0430/GDDPIntegration/

### Your mod description

My mod adds a new button to the Creator Layer that adds all Main GDDP Lists. 

The mod is currently unfinished as crucial functions haven't been implemented yet and are stopping me from realizing the full idea of it (GJLevelList::create(), GameLevelManager->responseToDict(), etc.). I will be updating it in the future once these functions get added. I've done the best with what I had available.

**Comment by altalk23** [comment]
please add geode.node-ids as dependency

**Comment by Minemaker0430** [comment]
Done! Repo link and mod download link remain the same but have been updated to include the dependency
