### ISSUE TITLE
Add Small Geometry Dash Mods (v1.0.0)

### ISSUE THREAD

**Issue by bwest1027** [geode-sdk/indexer#744]
### Your mod link

https://github.com/bwest1027/small-geometry-dash-mods/releases/download/v1.0.0/creo.small-gd-mods.geode

### Your mod source code

https://github.com/bwest1027/small-geometry-dash-mods

### Your mod description

- Just some basic things:
- Color Unlock Hack
- Practice Music Unlock
- Music Customizer Unlock
- No Transition
- Hide The Pause Menu

**Comment by altalk23** [comment]
i thoroughly enjoyed your documentation

**Comment by altalk23** [comment]
!accept
