### ISSUE TITLE
Add Minecraft Menu

### ISSUE THREAD

**Issue by undefined06855** [geode-sdk/indexer#750]
### Your mod link

https://github.com/undefined06855/MinecraftMenu/releases/download/v1.0.1/undefined0.minecraft_menu.geode

### Your mod source code

https://github.com/undefined06855/MinecraftMenu

### Your mod description

Makes the MenuLayer look like the minecraft forge title screen
don't worry about the amazing repeated code, i'll redo it eventually (never)

**Comment by altalk23** [comment]
!accept
