### ISSUE TITLE
Update Dark Mode

### ISSUE THREAD

**Issue by zohnannor** [geode-sdk/indexer#751]
### Your mod link

https://github.com/zohnannor/dark-mode-gd/releases/download/v0.1.2/zohnannor.dark_mode.geode

### Your mod source code

https://github.com/zohnannor/dark-mode-gd/

**Comment by zohnannor** [comment]
@TheSillyDoggo I should also add node ids to deps. should I close the issue & open new one or edit this one?

**Comment by matcool** [comment]
you can edit the issue 👍

**Comment by altalk23** [comment]
it was fixed in fact id recommend readding the -beta.12 lmao

**Comment by zohnannor** [comment]
lol ok I'll update this issue later with a newer version

**Comment by matcool** [comment]
!accept
