### ISSUE TITLE
Update Minecraft Menu to v1.1.0

### ISSUE THREAD

**Issue by undefined06855** [geode-sdk/indexer#756]
### Your mod link

https://github.com/undefined06855/MinecraftMenu/releases/download/v1.1.0/undefined0.minecraft_menu.geode

### Your mod source code

https://github.com/undefined06855/MinecraftMenu/

**Comment by undefined06855** [comment]
damn I think a staff need to commend !accept, idk though

**Comment by altalk23** [comment]
!accept
