### ISSUE TITLE
Level Quests

### ISSUE THREAD

**Issue by polskidevv** [geode-sdk/indexer#759]
### Your mod link

https://github.com/polskidevv/Level-Quests/releases/download/1.0.0/polsk.level_quests.geode

### Your mod source code

https://github.com/polskidevv/Level-Quests/

### Your mod description

This mod adds a Quests button to the online level page.

**Comment by altalk23** [comment]
id recommend using the layouts in geode node ids to add your button, otherwise itll be incompatible with stuff

**Comment by altalk23** [comment]
!accept
