### ISSUE TITLE
YouTubers Mod Add

### ISSUE THREAD

**Issue by LXanii** [geode-sdk/indexer#771]
### Your mod link

https://github.com/LXanii/GD-YouTubers/releases/download/1.0.0v/xanii.youtubers.geode

### Your mod source code

https://github.com/LXanii/GD-YouTubers

### Your mod description

Gives a badge to well known figures in the community to help better recognize them.

![Untitled](https://github.com/geode-sdk/indexer/assets/73562093/259556d3-65b8-40fe-b323-fff186b66b28)

**Comment by LXanii** [comment]
updated mod link and fixed the !res issue

**Comment by CdcOnGitHub** [comment]
why are u even targetting mac gd if u dont have a mac build

**Comment by matcool** [comment]
You can use build-geode-mod and let github actions build it all https://github.com/geode-sdk/build-geode-mod?tab=readme-ov-file#combine

**Comment by CdcOnGitHub** [comment]
u could've made it cross platform tho :c

**Comment by matcool** [comment]
!accept
