### ISSUE TITLE
Add JunkHider

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#774]
### Your mod link

https://github.com/RayDeeUx/JunkHider/releases/download/v1.0.0/raydeeux.junkhider.geode

### Your mod source code

https://github.com/RayDeeUx/JunkHider/

### Your mod description

# JunkHider

Hides various elements across several GD menus (depending on OS) that weren't worth releasing as standalone Geode mods.

Hide the "clear search" button. Useful for Android users whose muscle memories hasn't adjusted to 2.2 yet and don't want to clear their search bar.
![demoOne](https://github.com/geode-sdk/indexer/assets/51521765/58625707-50e9-4588-810d-ce86c34600f9)

Hide useless junk on the main level select menu that other mods haven't gotten to yet. [Does not work on macOS, and to hide remaining junk please use Undefined0's GDTweaks if you're on Windows.]
![demoTwo](https://github.com/geode-sdk/indexer/assets/51521765/db7a28f2-516a-4291-8417-f2a008f67e11)

Hide profile hints, including the ones for social media and levels vs lists. [Compatible with other mods!]
![demoThree](https://github.com/geode-sdk/indexer/assets/51521765/5432bb01-fc95-4fcc-a2d1-73893d8070bb)

Hide the Newgrounds, Achievements, and Stats buttons from the main menu (individually!).
![demoFour](https://github.com/geode-sdk/indexer/assets/51521765/effd45b7-2516-45a6-bcee-c9d26e836cbe)

Hide the redundant white countdown for the next daily/weekly level, as the golden one is persistent. [Relies on "Node IDs" by Geode Team, which is not supported on macOS.]
![demoFive](https://github.com/geode-sdk/indexer/assets/51521765/2579db2c-33af-4ead-94e9-f62caf7aaf3d)

**Comment by RayDeeUx** [comment]
updates:
\- already works with NoGrounds
\- slight revision in the binary to use syntactically correct `if defined()` per `@poweredbypie`'s comments in another indexer issue entry

**Comment by Fleeym** [comment]
what is your obsession with hooking ccsprite

**Comment by Fleeym** [comment]
also please call updateLayout in MenuLayer thank you very much

**Comment by RayDeeUx** [comment]
> what is your obsession with hooking ccsprite

crossplatform

**Comment by RayDeeUx** [comment]
> also please call updateLayout in MenuLayer thank you very much

done, updated binary

**Comment by undefined06855** [comment]
please can you update the bottom menu's layout when removing the buttons oh my god it looks so odd with massive spaces between them

**Comment by RayDeeUx** [comment]
binary updated once more

**Comment by altalk23** [comment]
youre supposed to update the layout of bottomMenu not this

**Comment by RayDeeUx** [comment]
binary updated

**Comment by Cvolton** [comment]
!accept
