### ISSUE TITLE
add NoGrounds (v1.0.0)

### ISSUE THREAD

**Issue by rileythesillyone** [geode-sdk/indexer#777]
### Your mod link

https://github.com/rileythesillyone/geodemods/releases/download/newgroundsbuttonbegone/riley.nogrounds.geode

### Your mod source code

https://github.com/rileythesillyone/geodemods/tree/main/nogrounds

### Your mod description

The mod removes the Newgroudns button from the menu

**Comment by Uproxide** [comment]
me when i help :3

**Comment by Uproxide** [comment]
**bolb**

**Comment by Uproxide** [comment]
# **worm**

**Comment by RayDeeUx** [comment]
well this is gonna be tricky to test for incompatibility with https://github.com/geode-sdk/indexer/issues/774; mine does the same thing and then some

**Comment by Fleeym** [comment]
!accept
