### ISSUE TITLE
Add IDS Integration (v1.2.0)

### ISSUE THREAD

**Issue by oatmealine** [geode-sdk/indexer#793]
### Your mod link

https://github.com/oatmealine/nlw-integration/releases/download/ids-integration-v1.2.0/oatmealine.ids_integration.geode

### Your mod source code

https://github.com/oatmealine/nlw-integration/tree/ids-integration

### Your mod description

Uses the [Insane Demon Spreadsheet](https://docs.google.com/spreadsheets/d/15ehtAIpCR8s04qIb8zij9sTpUdGJbmAE_LDcfVA3tcU/edit)
with [nlw-api](https://nlw.oat.zone/) to query tiers, skillsets and descriptions for all insane demons. Fork of [NLW Integration](https://github.com/oatmealine/nlw-integration).
figured this would be easier to both use and implement than merging the two, so

**Comment by matcool** [comment]
!accept
