### ISSUE TITLE
Gold User Coins v1.0.0

### ISSUE THREAD

**Issue by GDColon** [geode-sdk/indexer#799]
### Your mod link

https://github.com/GDColon/Gold-User-Coins/releases/download/v1.0.0/colon.gold_user_coins.geode

### Your mod source code

https://github.com/GDColon/Gold-User-Coins

### Your mod description

Renders all user coins as gold ones

**Comment by matcool** [comment]
https://github.com/GDColon/Gold-User-Coins/blob/main/src/main.cpp#L14-L15
this is pointless because init only runs once per menulayer instance anyways, i think you meant to make this a global variable :-)

**Comment by matcool** [comment]
!accept
