### ISSUE TITLE
Add FuckGlow

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#805]
### Your mod link

https://github.com/RayDeeUx/FuckGlow/releases/download/v1.0.0/raydeeux.fuckglow.geode

### Your mod source code

https://github.com/RayDeeUx/FuckGlow/

### Your mod description

Hides as many sources of glow from Geometry Dash as the user's operating system will allow (due to Geode's binding limitations).

To anyone with objections about the name of the mod, cope:
![image](https://github.com/geode-sdk/indexer/assets/51521765/baae3b43-69da-4605-9013-dda8104db39a)

**Comment by RayDeeUx** [comment]
wait shit hold on i need to redo the mod json

**Comment by RayDeeUx** [comment]
@poweredbypie

> Also is there a reason why there are conditionals for Windows and Android? As far as I know this code isn't platform-specific at all so I'm not sure why you restricted it

wanted to cross-platform as much of this mod as possible but that meant limiting some features to specific platforms. the decisions were made solely based on the parts github actions failed at

> The correct syntax for checking if one of many macros is defined is:
gonna apply that syntax in a bit, give me a few hours

> `<insert poweredbypie code cleanup here>`
will also try that in a bit n a few hours 😅

**Comment by RayDeeUx** [comment]
(code quality-related issues resolved, by the time you read this the binary will have been updated)

**Comment by RayDeeUx** [comment]
binary updated

**Comment by altalk23** [comment]
sure ig

**Comment by altalk23** [comment]
!accept
