### ISSUE TITLE
Add NoLevelRefresh

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#818]
### Your mod link

https://github.com/RayDeeUx/NoLevelRefresh/releases/download/v1.0.0/raydeeux.nolevelrefresh.geode

### Your mod source code

https://github.com/RayDeeUx/NoLevelRefresh

### Your mod description

[Windows only] Hides the level refresh button if you have TheSillyDoggo's "More Level Tags" mod installed, because that one crash has yet to be fixed.

**Comment by altalk23** [comment]
!accept
