### ISSUE TITLE
fixed backup mod :)

### ISSUE THREAD

**Issue by abb2k** [geode-sdk/indexer#819]
### Your mod link

https://github.com/abb2k/Backup/releases/download/Backup_v1.0.3/abb2k.backup.geode

### Your mod source code

https://github.com/abb2k/Backup

### Your mod description

fixed my code, UI breaking on different resolutions and auto backups! also added android support!! :D

**Comment by matcool** [comment]
wont work on android

**Comment by abb2k** [comment]
updated

**Comment by Fleeym** [comment]
!accept
