### ISSUE TITLE
GDDP Integration (Updated)

### ISSUE THREAD

**Issue by Minemaker0430** [geode-sdk/indexer#821]
### Your mod link

https://github.com/Minemaker0430/GDDPIntegration/releases/download/v1-beta/minemaker0430.gddp_integration.geode

### Your mod source code

https://github.com/Minemaker0430/GDDPIntegration

### Your mod description

Adds a new menu to the creator layer that currently shows all Main GDDP Tiers and the requirements to complete them.

**Comment by Fleeym** [comment]
you should start targeting a beta on the next release, it won't break now

**Comment by Fleeym** [comment]
!accept
