### ISSUE TITLE
Blending Glow v1.0.2

### ISSUE THREAD

**Issue by flurrybun** [geode-sdk/indexer#826]
### Your mod link

https://github.com/flurrybun/blending-glow/releases/download/v1.0.2/ninkaz.blending_glow.geode

### Your mod source code

https://github.com/flurrybun/blending-glow

### Your mod description

makes the player's glow blending like how it was pre-2.2

**Comment by Fleeym** [comment]
don't use "*" for gd version, use the actual version

**Comment by flurrybun** [comment]
sure thing. updated it to now target windows 2.204, android 2.205, and mac 2.200

https://github.com/flurrybun/blending-glow/releases/download/v1.1.1/ninkaz.blending_glow.geode

**Comment by altalk23** [comment]
edit your original issue or make a new issue with the geode file

**Comment by Cvolton** [comment]
!accept
