### ISSUE TITLE
Update Geode Contributors (v1.1.1)

### ISSUE THREAD

**Issue by Uproxide** [geode-sdk/indexer#828]
### Your mod link

https://github.com/Uproxide/Geode-Contributors/releases/download/v1.1.1/uproxide.geodedevelopers.geode

### Your mod source code

https://github.com/Uproxide/Geode-Contributors/

### Your mod description

my mod blows up mats house
(read the changelog (fixed))

**Comment by Fleeym** [comment]
why are you targeting "*" on all platforms?

**Comment by Uproxide** [comment]
> why are you targeting "*" on all platforms?

i fixed it @Fleeym

**Comment by Fleeym** [comment]
!accept
