### ISSUE TITLE
Add AntiLobotomy

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#829]
### Your mod link

https://github.com/RayDeeUx/AntiLobotomy/releases/download/v1.0.0/raydeeux.antilobotomy.geode

### Your mod source code

https://github.com/RayDeeUx/AntiLobotomy

### Your mod description

Disables difficulty faces, SFX, and Song triggers from loading in levels related to lobotomies.

Since this is done based on level name, there is no one-size-fits-all-solution.
There will not be a setting to apply this mod to all levels regardless of its name.

**Comment by altalk23** [comment]
!accept
