### ISSUE TITLE
Update GDDP Integration (v1.0.0-beta.2)

### ISSUE THREAD

**Issue by Minemaker0430** [geode-sdk/indexer#846]
### Your mod link

https://github.com/Minemaker0430/GDDPIntegration/releases/download/v1-beta.2/minemaker0430.gddp_integration.geode

### Your mod source code

https://github.com/Minemaker0430/GDDPIntegration

### Your mod description

Added Legacy Packs, changed method of obtaining Pack Data to Async, and added an Alternate Button Texture

**Comment by matcool** [comment]
!accept
