### ISSUE TITLE
Add Level Info in Pause Menu

### ISSUE THREAD

**Issue by Weebifying** [geode-sdk/indexer#850]
### Your mod link

https://github.com/Weebifying/lvlinfo-in-pause-geode/releases/download/v1.0.0/weebify.level_info_in_pause_menu.geode

### Your mod source code

https://github.com/Weebifying/lvlinfo-in-pause-geode

### Your mod description

i went to your home last night with your mom

**Comment by Weebifying** [comment]
had to build manually :pensive:

**Comment by altalk23** [comment]
!accept
