### ISSUE TITLE
Add Clean Startpos

### ISSUE THREAD

**Issue by blueblock6** [geode-sdk/indexer#863]
### Your mod link

https://github.com/blueblock6/CleanStartpos/releases/download/1.0.0/blueblock6.cleanstartpos.geode

### Your mod source code

https://github.com/blueblock6/CleanStartpos

### Your mod description

Puts all the Startpos options on one page

![example](https://raw.githubusercontent.com/blueblock6/CleanStartpos/master/resources/example.png)

**Comment by RayDeeUx** [comment]
@thesillydoggo wake up you've got competition; this one's looking far more compact tbh

**Comment by matcool** [comment]
!accept
