### ISSUE TITLE
Update Level Info in Pause Menu to v1.0.1

### ISSUE THREAD

**Issue by Weebifying** [geode-sdk/indexer#864]
### Your mod link

https://github.com/Weebifying/lvlinfo-in-pause-geode/releases/download/v1.0.1/weebify.level_info_in_pause_menu.geode

### Your mod source code

https://github.com/Weebifying/lvlinfo-in-pause-geode

### Your mod description

compat with clicksound!!

**Comment by Cvolton** [comment]
!accept
