### ISSUE TITLE
Update to "hide pause menu hack" to v1.1.1

### ISSUE THREAD

**Issue by EKVgd** [geode-sdk/indexer#872]
### Your mod link

https://github.com/EKVgd/hidePauseMenuHack/releases/download/v1.1.1/ekv.hidePauseMenuHack.geode

### Your mod source code

https://github.com/EKVgd/hidePauseMenuHack

### Your mod description

**v1.1.1**

- fixed conflicts with other mods
- fixed minor bugs
- added slider for position of the button

**Comment by Cvolton** [comment]
!accept
