### ISSUE TITLE
Remove "Demonlist User Info"

### ISSUE THREAD

**Issue by elnexreal** [geode-sdk/indexer#878]
### Your mod link

https://github.com/elnexreal/DemonlistInfo/releases/download/1.0.0/elnexreal.demonlistinfo.geode

### Your mod description

Remove the mod from the index, im not going to maintain it

**Comment by matcool** [comment]
thats not gonna work, you gotta ask us to remove it

**Comment by elnexreal** [comment]
> thats not gonna work, you gotta ask us to remove it

can you remove it? 🥺
