### ISSUE TITLE
GodLikeFaces mod bug fix update

### ISSUE THREAD

**Issue by AdyaGMD** [geode-sdk/indexer#880]
### Your mod link

https://github.com/AdyaGMD/GodLikeFaces/releases/download/releasev1.1.1/adyagd.godlikefaces.geode

### Your mod source code

https://github.com/AdyaGMD/GodLikeFaces/

**Comment by matcool** [comment]
nice version

**Comment by AdyaGMD** [comment]
I fixed it after it

**Comment by matcool** [comment]
can u edit the version to trigger the action again
