### ISSUE TITLE
Fix CleanerMenu (Update 2.0.0 -> 2.0.1)

### ISSUE THREAD

**Issue by 29cmb** [geode-sdk/indexer#895]
### Your mod link

https://github.com/29cmb/CleanMenu/releases/download/2.204-6/devcmb.cleanermenu.geode

### Your mod source code

https://github.com/29cmb/CleanMenu
 
### Your mod description

A mod which repositions multiple items on the GD menus

**Comment by 29cmb** [comment]
Android support removed and mod.json updated

**Comment by matcool** [comment]
!accept
