### ISSUE TITLE
Add Spinoff Subtitles

### ISSUE THREAD

**Issue by iristraa** [geode-sdk/indexer#896]
### Your mod link

https://github.com/iristraa/SpinoffSubtitles/releases/download/v1.0.2/iristraa.spinoffsubtitles.geode

### Your mod source code

https://github.com/iristraa/SpinoffSubtitles

### Your mod description

Adds subtexts from the spinoff games to the main menu.

**Comment by Cvolton** [comment]
node ids dependency isnt required since it only edits menulayer, which is one of the 2 layers whose node ids are covered by geode itself (the other one being loadinglayer)

**Comment by Cvolton** [comment]
!accept
