### ISSUE TITLE
Custom Name (1.2.2)

### ISSUE THREAD

**Issue by coopeeo** [geode-sdk/indexer#897]
### Your mod link

https://github.com/coopeeo/customname-geodemod/releases/download/1.2.2/coopeeo.customname.geode

### Your mod source code

https://github.com/coopeeo/customname-geodemod/

### Your mod description

Make yourself have your own name. (Only appears for yourself)

Also Fixes error when running the mod on beta.17

**Comment by coopeeo** [comment]
may a developer review my mod real quick?
the version currently on Geode Index (1.1.5) is broken on Geode 2.0.0-beta.17.
Also mac support.
\- Thanks, Coop

**Comment by matcool** [comment]
!accept

**Comment by coopeeo** [comment]
Thanks!
