### ISSUE TITLE
Add AutoSong 1.0.0

### ISSUE THREAD

**Issue by Uproxide** [geode-sdk/indexer#898]
### Your mod link

https://github.com/Uproxide/AutoSong-Geode/releases/download/1.0.0/uproxide.autosong.geode

### Your mod source code

https://github.com/Uproxide/AutoSong-Geode/

### Your mod description

My mod makes everyone happy and dance!
(automatically downloads a levels song)

**Comment by Uproxide** [comment]
no clue i was seeing if it would fix the needing to open it twice for levels with multiple songs/sfx

**Comment by altalk23** [comment]
yeah no please dont sleep on main thread 👍

**Comment by Uproxide** [comment]
I'll fix aug h

**Comment by Uproxide** [comment]
updated @altalk23

**Comment by Cvolton** [comment]
!accept
