### ISSUE TITLE
Update Click Sounds (v1.4.1 -> v1.4.2)

### ISSUE THREAD

**Issue by coopeeo** [geode-sdk/indexer#905]
### Your mod link

https://github.com/BeatACVR/geode-clicksound/releases/download/Release-v1.4.2/beat.click-sound.geode

### Your mod source code

https://github.com/BeatACVR/geode-clicksound/

### Your mod description

> Plays a sound whenever you click (or optionally release) in Geometry Dash.

## New in this update!
* Requirements: Geode v2.0.0-beta.17 / Node-IDs v1.3.0
* .m4a audio support added! (.ogg is still the best audio format to use for custom sounds.)
* 'Spacebar 2' useful click sound added! (ty tonysburger!)
* 'Click 3' useful click sound added! (ty probank!)

***I made this issue on behalf of @BeatACVR***

**Comment by matcool** [comment]
!accept
