### ISSUE TITLE
Update YouTubers -> 1.0.1

### ISSUE THREAD

**Issue by LXanii** [geode-sdk/indexer#906]
### Your mod link

https://github.com/LXanii/GD-YouTubers/releases/download/1.0.1/xanii.youtubers.geode

### Your mod source code

https://github.com/LXanii/GD-YouTubers

### Your mod description

// Fixed bug with badge loading
// Added support for other systems

**Comment by Capeling** [comment]
gas

**Comment by matcool** [comment]
!accept
