### ISSUE TITLE
update for backup mod :)

### ISSUE THREAD

**Issue by abb2k** [geode-sdk/indexer#913]
### Your mod link

https://github.com/abb2k/Backup/releases/download/Backup_v1.0.5/abb2k.backup.geode

### Your mod source code

https://github.com/abb2k/Backup

### Your mod description

improved backup exporting and importing stuff (old exported backups will not works anymore) and removed exporting and importing backups from android, this might be supported in the future but idk

**Comment by matcool** [comment]
!accept
