### ISSUE TITLE
Ingamelistmod update

### ISSUE THREAD

**Issue by AdyaGMD** [geode-sdk/indexer#914]
### Your mod link

https://github.com/AdyaGMD/IngameListMod/releases/download/release-v1.1.2/adyagd.ingamelistmod.geode

### Your mod source code

https://github.com/AdyaGMD/IngameListMod

**Comment by matcool** [comment]
nice mod.json

**Comment by Cvolton** [comment]
me when version 1.1.2 is impostor and is actually 1.1.1...

**Comment by matcool** [comment]
fix ur version brah
