### ISSUE TITLE
Update Click Sounds (v1.4.2 -> v1.4.3)

### ISSUE THREAD

**Issue by coopeeo** [geode-sdk/indexer#925]
### Your mod link

https://github.com/BeatACVR/geode-clicksound/releases/download/Release-v1.4.3/beat.click-sound.geode

### Your mod source code

https://github.com/BeatACVR/geode-clicksound

### Your mod description

> Plays a sound whenever you click (or optionally release) in Geometry Dash.

## New in this update!
* Requirements: Geode v2.0.0-beta.17 / Node-IDs v1.3.0 (added last update)
* 'Click Sound' is now 'Click Sounds'
* .flac audio support added! (.ogg is still the best audio format to use for custom sounds.)
* 'Joe Biden Soda' meme click sound added! :3

***I made this issue on behalf of @BeatACVR***

**Comment by coopeeo** [comment]
this is also a test on my geode index mod update detector thingy YAY

**Comment by matcool** [comment]
!accept
