### ISSUE TITLE
update menuBG Customizer

### ISSUE THREAD

**Issue by jojo989** [geode-sdk/indexer#927]
### Your mod link

https://github.com/jojo989/menuBG-customizer/releases/download/idk2/jojo989.main_menu_bg_customizer.geode

### Your mod source code

https://github.com/jojo989/menuBG-customizer

### Your mod description

idk

**Comment by matcool** [comment]
pretty meh code but whatever

**Comment by matcool** [comment]
!accept

**Comment by jojo989** [comment]
> pretty meh code but whatever

ikr 😭😭
