### ISSUE TITLE
Update Flashlight 1.0.2 -> 1.0.3

### ISSUE THREAD

**Issue by LXanii** [geode-sdk/indexer#929]
### Your mod link

https://github.com/LXanii/Flashlight-Mod/releases/download/1.0.3/xanii.flashlight.geode

### Your mod source code

https://github.com/LXanii/Flashlight-Mod/

### Your mod description

// Added Opacity slider
// Added support for Android64 & Android32

**Comment by matcool** [comment]
!accept
