### ISSUE TITLE
Add BSOD On Death

### ISSUE THREAD

**Issue by Igbalabanov** [geode-sdk/indexer#93]
### Your mod link

https://github.com/Igbalabanov/GDMods/releases/download/v1.0.0/chs000.bsodondeath.geode

**Comment by altalk23** [comment]
right now only verified users can use the new system

**Comment by Igbalabanov** [comment]
So am I supposed to wait until it is otherwise?

**Comment by altalk23** [comment]
Nope, just made you verified. We're changing the system so that only new users will undergo checks, and then they can add normally. You are still expected to follow the guidelines though, and we will take action where we see needed.
