### ISSUE TITLE
Add Globed Mobile

### ISSUE THREAD

**Issue by dudonbatongd** [geode-sdk/indexer#931]
### Your mod link

https://github.com/dudonbatongd/GlobedMobile/releases/tag/untagged-b1e95faeb9140ac299a7

### Your mod source code

https://github.com/dudonbatongd/GlobedMobile

### Your mod description

!!working not on all devices!!

**Comment by dankmeme01** [comment]
i did not consent

**Comment by CdcOnGitHub** [comment]
consent isnt real

**Comment by Weebifying** [comment]
what are you cooking

**Comment by HJfod** [comment]
This person has been blocked from the geode-sdk organization for high suspicion of attempting to get a ratted mod on the Geode index. **Do not download the attached file unless you know how to do security research.**

**Comment by TechStudent10** [comment]
this is a menu layer mod apparently LOL

**Comment by CdcOnGitHub** [comment]
its just the windows globed version and android textureldr

**Comment by RayDeeUx** [comment]
lol denied

**Comment by iristraa** [comment]
L bozo
