### ISSUE TITLE
Add Pause menu zoom

### ISSUE THREAD

**Issue by SaiOwO** [geode-sdk/indexer#932]
### Your mod link

https://github.com/SaiOwO/Pause-menu-zoom/releases/download/Release/elsai.pause_menu_zoom.geode

### Your mod source code

https://github.com/SaiOwO/Pause-menu-zoom

### Your mod description

In pause menu you can scroll your mouse to zoom in and zoom out, also you can click and drag to move the camera

**Comment by matcool** [comment]
!accept
