### ISSUE TITLE
Update LoadingScreenTweaks

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#934]
### Your mod link

https://github.com/RayDeeUx/LoadingScreenTweaks/releases/download/v1.1.0/raydeeux.loadingscreentweaks.geode

### Your mod source code

https://github.com/RayDeeUx/LoadingScreenTweaks

### Your mod description

Updated to use @geode-sdk's Node IDs instead of grabbing by index.
Still supported on Windows, macOS, and Android.

**Comment by Cvolton** [comment]
loadinglayer ids are set by geode directly, the node ids dependency is not needed

**Comment by RayDeeUx** [comment]
binary updated to reflect that

**Comment by Cvolton** [comment]
!accept
