### ISSUE TITLE
Update Click Sounds (1.4.3 --> 1.4.4)

### ISSUE THREAD

**Issue by coopeeo** [geode-sdk/indexer#942]
### Your mod link

https://github.com/BeatACVR/geode-clicksound/releases/download/Release-v1.4.4/beat.click-sound.geode

### Your mod source code

https://github.com/BeatACVR/geode-clicksound/

### Your mod description

> Plays a sound whenever you click (or optionally release) in Geometry Dash.

## New in this update!
* New Requirements: Geode v2.0.0-beta.19 / Node-IDs v1.4.0
* 'Water on the hill' meme click sound added!
* 'Viper Space Bar' useful click sound added! (ty viper!)
* 'Click/Release 5' useful click sound added! (ty main!)

***I made this issue on behalf of @BeatACVR***

**Comment by matcool** [comment]
!accept
