### ISSUE TITLE
Copyright remover for main levels

### ISSUE THREAD

**Issue by SaiOwO** [geode-sdk/indexer#945]
### Your mod link

https://github.com/SaiOwO/Copyright-remover-for-main-levels/releases/download/Release/elsai.copyright_remover_for_main_levels.geode

### Your mod source code

https://github.com/SaiOwO/Copyright-remover-for-main-levels

### Your mod description

Add a option to change the main songs to a piano version

**Comment by matcool** [comment]
!accept
