### ISSUE TITLE
Hide Profile Button

### ISSUE THREAD

**Issue by Bigmancozmo** [geode-sdk/indexer#946]
### Your mod link

https://github.com/Bigmancozmo/Hide-Profile-Button/releases/download/v1.0.0/bigmancozmo.hide_profile_button.geode

### Your mod source code

https://github.com/Bigmancozmo/Hide-Profile-Button/

### Your mod description

Hides the profile name and icon from the MenuLayer.

**Comment by matcool** [comment]
good one

**Comment by cgytrus** [comment]
i do it all the time no worries 🔥
