### ISSUE TITLE
Update: Stat Changes 1.1.1

### ISSUE THREAD

**Issue by RedLime** [geode-sdk/indexer#949]
### Your mod link

https://github.com/RedLime/Stat-Changes-Geode/releases/download/1.1.1/redlime.statchanges.geode

### Your mod source code

https://github.com/RedLime/Stat-Changes-Geode

### Your mod description

- Support MacOS
- Fixed crash when profile has closed or changed the scene

**Comment by Cvolton** [comment]
!accept
