### ISSUE TITLE
Add RussianRoulette Mod

### ISSUE THREAD

**Issue by Nova1500** [geode-sdk/indexer#950]
### Your mod link

https://github.com/Nova1500/geode-russian-roulette/releases/download/1.0.0/nova3954.geode-russian-roulette.geode

### Your mod source code

https://github.com/Nova1500/geode-russian-roulette/

### Your mod description

My mod adds a 1/1000 chance that the level will reset every time the player jumps.

**Comment by altalk23** [comment]
honestly after the bsod on death incident i am very skeptical about accepting destructive mods
@matcool

**Comment by Fleeym** [comment]
I agree, IMO this shouldn't be on the index
