### ISSUE TITLE
Add 𝓕𝓻𝓮𝓪𝓴𝔂 𝓜𝓸𝓭𝓮

### ISSUE THREAD

**Issue by LXanii** [geode-sdk/indexer#955]
### Your mod link

https://github.com/LXanii/Freaky-Mode/releases/download/1.0.0/xanii.freaky_mode.geode

### Your mod source code

https://github.com/LXanii/Freaky-Mode

### Your mod description

𝓛𝓮𝓽𝓼 𝓖𝓮𝓽 𝓕𝓻𝓮𝓪𝓴𝔂

**Comment by FigmentBoy** [comment]
!accept
