### ISSUE TITLE
Add GDLite

### ISSUE THREAD

**Issue by YellowCat98** [geode-sdk/indexer#986]
### Your mod link

https://github.com/YellowCat98/GDLite/releases/download/wgat/yellowcat98.gdlite.geode

### Your mod source code

https://github.com/YellowCat98/GDLite

### Your mod description

This mod turns the game into geometry dash lite, it's purely cosmetic and doesn't block you from full version GD features, also adds a "GDLite. Free Trial" in PlayLayer, but its at the bottom and unnoticeable so it doesn't distract the player

**Comment by matcool** [comment]
i can assure that you do not support any gd version

**Comment by YellowCat98** [comment]
> i can assure that you do not support any gd version

mb it's meant for 2.204 on pc i should've probably set did that instead of all gd versions 😭

**Comment by Fleeym** [comment]
oh new index is gonna be fun

**Comment by iristraa** [comment]
oh no

**Comment by altalk23** [comment]
you still have not fixed the gd version i see

**Comment by YellowCat98** [comment]
> you still have not fixed the gd version i see

fixed now

**Comment by Cvolton** [comment]
!accept
