### ISSUE TITLE
Add MoveAudioVisualizer

### ISSUE THREAD

**Issue by RayDeeUx** [geode-sdk/indexer#987]
### Your mod link

https://github.com/RayDeeUx/MoveAudioVisualizer/releases/download/v1.0.0/raydeeux.moveaudiovisualizer.geode

### Your mod source code

https://github.com/RayDeeUx/MoveAudioVisualizer

### Your mod description

# MoveAudioVisualizer

Moves the Audio Visualizer towards the bottom of the screen, or to a position of your choice.

Demo:
![demoOne](https://github.com/geode-sdk/indexer/assets/51521765/1258bff0-71a4-4af1-855a-7a46254c4350)

Other Geode-compatible mods featured to make the UI as cramped as possible for this demonstration:
- MegaHack v8 by Absolute, available at https://absolllute.com for $5 USD
- Globed by dankmeme01, available on the Geode index with more information at https://geode-sdk.org/mods/dankmeme.globed2/
- Channel Viewer by NyakoFox, available on the Geode index with more information at https://geode-sdk.org/mods/nyakofox.channelviewer/

Featured level: "Dash but i edited it" by https://github.com/GDColon: https://gdbrowser.com/99585022

Settings for "RayDeeUx mode", in case you want to replicate them youself:
- Music Visualizer X Position: `[your screen width] * 0.25`
- Music Visualizer Y Position: `15`
- Music Visualizer Rotation + Scale: `270` degrees at `0.75`x scale
- SFX Visualizer X Position: `[your screen width] * 0.75`
- SFX Visualizer Y Position: `15`
- SFX Visualizer Rotation + Scale: `90` degrees at `0.75`x scale

**Comment by altalk23** [comment]
god we seriously need playlayer node ids

**Comment by altalk23** [comment]
!accept
