### ISSUE TITLE
Add "Auto priority to high" (v1.0.0)

### ISSUE THREAD

**Issue by elnexreal** [geode-sdk/indexer#989]
### Your mod link

https://github.com/elnexreal/autoSetPriority/releases/download/1.0.0/elnexreal.auto_priority.geode

### Your mod source code

https://github.com/elnexreal/autoSetPriority

### Your mod description

Sets the priority to high when opening the game (only windows)

**Comment by altalk23** [comment]
this couldve been prob made a "*" with a on_mod Loaded or an execute block but this works as well ig

**Comment by altalk23** [comment]
!accept
