### ISSUE TITLE
Update Spinoff Subtitles

### ISSUE THREAD

**Issue by iristraa** [geode-sdk/indexer#991]
### Your mod link

https://github.com/iristraa/SpinoffSubtitles/releases/download/v1.1.0/iristraa.spinoffsubtitles.geode

### Your mod source code

https://github.com/iristraa/SpinoffSubtitles

### Your mod description

Adds the subtexts seen in the spinoff games (Lite, Meltdown, World, Subzero)

**Comment by altalk23** [comment]
!accept
