### ISSUE TITLE
Add "Transparent BG"(v1.0.0)

### ISSUE THREAD

**Issue by Naxrin** [geode-sdk/indexer#993]
### Your mod link

https://github.com/Naxrin/Transparent-BG-Geode/releases/download/stable/naxrin.transparent.geode

### Your mod source code

https://github.com/Naxrin/Transparent-BG-Geode

### Your mod description

My mod removes the stupid blue blending from the background image "GJ_GradientBG-hd.png" and let us enjoy more with our picked images of anime porn, similar to Transparent BG of Mega Hack v7 on gd2.113 does. Transparent List is looked into yet.

**Comment by matcool** [comment]
mod relies heavily on nodeids but doesnt have it as a dependency..

**Comment by Naxrin** [comment]
> mod relies heavily on nodeids but doesnt have it as a dependency..

ok fixed just now. Now geode should have dependency warning without node-ids enabled.

**Comment by altalk23** [comment]
you should edit the release with the new geode file

**Comment by Naxrin** [comment]
> you should edit the release with the new geode file

I've deleted the previous file and uploaded the new one. The current link is still available and the release file should be replaced already i guess.

**Comment by altalk23** [comment]
try to not replace releases but whatever ig its fine since its not on the index yet

**Comment by altalk23** [comment]
!accept
