### ISSUE TITLE
Better Menu Update Beta.12 -> Beta.13

### ISSUE THREAD

**Issue by MuhXd** [geode-sdk/indexer#996]
### Your mod link

https://github.com/MuhXd/BetterMenuMod/releases/download/v1.0.4-beta.13/muhammadgames.bettermenu.geode

### Your mod source code

https://github.com/MuhXd/BetterMenuMod

### Your mod description

Better Menu Update

# New setting
* Add disable close button
* Mac Support is Back!
# Extra info
## 2.2 Mac Build Version
**2.200**
## 2.2 Windows Build Version
**2.204**
## 2.2 Android build version
**2.205**

**Comment by altalk23** [comment]
!accept
